Repository tensorflow/datasets, pull requests merged in 2019-12, with the labels that each got.

#1245 Automated documentation update
  docs/catalog/abstract_reasoning.md
  docs/catalog/celeb_a_hq.md
  docs/catalog/cifar10_corrupted.md
  docs/catalog/curated_breast_imaging_ddsm.md
  docs/catalog/diabetic_retinopathy_detection.md
  docs/catalog/i_naturalist2017.md
  docs/catalog/image_label_folder.md
  docs/catalog/imagenet2012.md
  docs/catalog/imagenet2012_corrupted.md
  docs/catalog/math_dataset.md
  docs/catalog/newsroom.md
  docs/catalog/resisc45.md
  docs/catalog/wikihow.md
  docs/catalog/wikipedia.md
  docs/catalog/wmt14_translate.md
  docs/catalog/wmt15_translate.md
  docs/catalog/wmt16_translate.md
  docs/catalog/wmt17_translate.md
  docs/catalog/wmt18_translate.md
  docs/catalog/wmt19_translate.md
  docs/catalog/wmt_t2t_translate.md
  docs/catalog/xsum.md
  tensorflow_datasets/testing/metadata/cnn_dailymail/bytes/2.0.0/article.text.bytes
  tensorflow_datasets/testing/metadata/cnn_dailymail/bytes/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/cnn_dailymail/bytes/2.0.0/highlights.text.bytes
  tensorflow_datasets/testing/metadata/cnn_dailymail/plain_text/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/cnn_dailymail/subwords32k/2.0.0/article.text.subwords
  tensorflow_datasets/testing/metadata/cnn_dailymail/subwords32k/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/cnn_dailymail/subwords32k/2.0.0/highlights.text.subwords
  tensorflow_datasets/testing/metadata/i_naturalist2017/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/i_naturalist2017/0.1.0/image.image.json
  tensorflow_datasets/testing/metadata/i_naturalist2017/0.1.0/label.labels.txt
  tensorflow_datasets/testing/metadata/i_naturalist2017/0.1.0/supercategory.labels.txt
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#1250 update billsum 3.0
  tensorflow_datasets/summarization/billsum.py
  tensorflow_datasets/testing/test_data/fake_examples/billsum/ca_test_data_final_OFFICIAL.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/billsum/us_test_data_final_OFFICIAL.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/billsum/us_train_data_final_OFFICIAL.jsonl
  tensorflow_datasets/url_checksums/billsum.txt
Labels: cla: no

#1258 fix broken link to setup.py, resolves #1257
  docs/add_dataset.md
Labels: cla: yes

#1255 Fix numbers in Oxford Flowers 102 description
  tensorflow_datasets/image/oxford_flowers102.py
Labels: cla: yes

#1253 Add a dataset "scicite"
  docs/add_dataset.md
  tensorflow_datasets/image/oxford_flowers102.py
  tensorflow_datasets/testing/test_data/fake_examples/scicite/scicite/dev.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/scicite/scicite/test.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/scicite/scicite/train.jsonl
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/scicite.py
  tensorflow_datasets/text/scicite_test.py
  tensorflow_datasets/url_checksums/scicite.txt
Labels: cla: no

#1260 Add MANUAL_DOWNLOAD_INSTRUCTIONS for C4.
  tensorflow_datasets/text/c4.py
Labels: cla: no

#1256 update gigaword
  tensorflow_datasets/summarization/gigaword.py
Labels: cla: no

#1262 Handle cases when TriviaQA examples are missing the SearchResults or EntityPages field.
  tensorflow_datasets/text/trivia_qa.py
Labels: cla: yes

#1267 Use static python_version dependency configuration in setup.py
  setup.py
Labels: cla: yes

#1268 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/billsum.md
  docs/catalog/c4.md
  docs/catalog/gigaword.md
  docs/catalog/overview.md
  docs/catalog/oxford_flowers102.md
  docs/catalog/scicite.md
  docs/catalog/wikipedia.md
  tensorflow_datasets/testing/metadata/billsum/3.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/gigaword/1.2.0/dataset_info.json
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/scicite/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/scicite/1.0.0/label.labels.txt
  tensorflow_datasets/testing/metadata/scicite/1.0.0/label2.labels.txt
  tensorflow_datasets/testing/metadata/scicite/1.0.0/source.labels.txt
  tensorflow_datasets/testing/metadata/supported.txt
  tensorflow_datasets/testing/metadata/ucf101/ucf101_1/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/ucf101/ucf101_1/2.0.0/label.labels.txt
  tensorflow_datasets/testing/metadata/ucf101/ucf101_1/2.0.0/video.image.json
  tensorflow_datasets/testing/metadata/ucf101/ucf101_1_256/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/ucf101/ucf101_1_256/2.0.0/label.labels.txt
  tensorflow_datasets/testing/metadata/ucf101/ucf101_1_256/2.0.0/video.image.json
  tensorflow_datasets/testing/metadata/ucf101/ucf101_2/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/ucf101/ucf101_2/2.0.0/label.labels.txt
  tensorflow_datasets/testing/metadata/ucf101/ucf101_2/2.0.0/video.image.json
  tensorflow_datasets/testing/metadata/ucf101/ucf101_3/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/ucf101/ucf101_3/2.0.0/label.labels.txt
  tensorflow_datasets/testing/metadata/ucf101/ucf101_3/2.0.0/video.image.json
Labels: cla: no

#1273 Fix python_version in PY2 backport deps.
  setup.py
Labels: cla: no

#1274 Automated documentation update
  docs/api_docs/python/tfds.md
Labels: cla: no

#1275 Reduce memory usage during trivia_qa preparation.
  tensorflow_datasets/testing/test_data/fake_examples/trivia_qa/qa/web-dev.json
  tensorflow_datasets/testing/test_data/fake_examples/trivia_qa/qa/web-test-without-answers.json
  tensorflow_datasets/testing/test_data/fake_examples/trivia_qa/qa/web-train.json
  tensorflow_datasets/testing/test_data/fake_examples/trivia_qa/triviaqa-unfiltered/unfiltered-web-dev.json
  tensorflow_datasets/testing/test_data/fake_examples/trivia_qa/triviaqa-unfiltered/unfiltered-web-test-without-answers.json
  tensorflow_datasets/testing/test_data/fake_examples/trivia_qa/triviaqa-unfiltered/unfiltered-web-train.json
  tensorflow_datasets/text/trivia_qa.py
  tensorflow_datasets/text/triviaqa_test.py
Labels: cla: no

#1282 Automated documentation update
  docs/api_docs/python/tfds/download/GenerateMode.md
  docs/api_docs/python/tfds/testing/DatasetBuilderTestCase/failureException.md
Labels: cla: no

#1281 Make it possible to use deep_weeds dataset v1 (needs to sync back in time to prepare).
  tensorflow_datasets/image/deep_weeds.py
Labels: cla: no

#1283 Add a tfds.ReadConfig to customize input pipelines hyper-parameters
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/registered.py
  tensorflow_datasets/core/registered_test.py
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/tfrecords_reader_test.py
  tensorflow_datasets/core/utils/read_config.py
  tensorflow_datasets/public_api.py
Labels: cla: no

#1287 fixing issues with not-recognized ZIP file in aeslc
  tensorflow_datasets/summarization/aeslc.py
Labels: cla: no

#1289 Add Jigsaw/Civil Comments data to TFDS.
  tensorflow_datasets/testing/test_data/fake_examples/civil_comments/test_private_expanded.csv
  tensorflow_datasets/testing/test_data/fake_examples/civil_comments/test_public_expanded.csv
  tensorflow_datasets/testing/test_data/fake_examples/civil_comments/train.csv
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/civil_comments.py
  tensorflow_datasets/text/civil_comments_test.py
  tensorflow_datasets/url_checksums/civil_comments.txt
Labels: cla: no

#1286 Automated documentation update
  docs/catalog/deep_weeds.md
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#1261 Add Imagenette to TensorFlow datasets
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/imagenette.py
  tensorflow_datasets/image/imagenette_labels.txt
  tensorflow_datasets/image/imagenette_test.py
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette-160/train/n01440764/tmp5lv8zrdz.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette-160/train/n01440764/tmpifc5foma.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette-160/train/n02102040/tmprnsy7g1j.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette-160/train/n02102040/tmpwfx16ir6.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette-160/val/n01440764/tmpohpuq1x0.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette-160/val/n01440764/tmpp_tbvklv.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette-160/val/n02102040/tmpr9myntdm.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette-160/val/n02102040/tmpu_x1o3mz.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette-320/train/n01440764/tmp98ubjb0h.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette-320/train/n01440764/tmpazdnui51.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette-320/train/n02102040/tmpgl2yxn7r.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette-320/train/n02102040/tmpqaunr87h.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette-320/val/n01440764/tmpqt4zag9p.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette-320/val/n01440764/tmptj1vbo17.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette-320/val/n02102040/tmpwocr6y31.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette-320/val/n02102040/tmpxkvifki1.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette/train/n01440764/tmp5u067tf2.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette/train/n01440764/tmp8t02u64i.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette/train/n02102040/tmp2yx3_5e7.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette/train/n02102040/tmp90njxo8f.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette/val/n01440764/tmpcj90c60p.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette/val/n01440764/tmpevnrvuwl.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette/val/n02102040/tmpfqs_w6ml.JPEG
  tensorflow_datasets/testing/test_data/fake_examples/imagenette/imagenette/val/n02102040/tmphxfcg70o.JPEG
  tensorflow_datasets/url_checksums/imagenette.txt
Labels: almost_ready_to_merge, being_merged, cla: yes

#1293 Automated documentation update
  docs/api_docs/python/_toc.yaml
  docs/api_docs/python/index.md
  docs/api_docs/python/tfds.md
  docs/api_docs/python/tfds/ReadConfig.md
  docs/api_docs/python/tfds/_api_cache.json
  docs/api_docs/python/tfds/core/BeamBasedBuilder.md
  docs/api_docs/python/tfds/core/DatasetBuilder.md
  docs/api_docs/python/tfds/core/GeneratorBasedBuilder.md
  docs/api_docs/python/tfds/load.md
  docs/api_docs/python/tfds/testing/DummyDatasetSharedGenerator.md
  docs/api_docs/python/tfds/testing/DummyMnist.md
  docs/catalog/_toc.yaml
  docs/catalog/civil_comments.md
  docs/catalog/imagenette.md
  docs/catalog/overview.md
  docs/catalog/oxford_iiit_pet.md
  tensorflow_datasets/testing/metadata/civil_comments/0.9.0/dataset_info.json
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#1248 Add validation splits to the food101 dataset
  tensorflow_datasets/image/food101.py
  tensorflow_datasets/image/food101_test.py
  tensorflow_datasets/testing/test_data/fake_examples/food101/food-101/images/cheese_plate/007.jpg
  tensorflow_datasets/testing/test_data/fake_examples/food101/food-101/images/cheese_plate/008.jpg
  tensorflow_datasets/testing/test_data/fake_examples/food101/food-101/images/cheesecake/005.jpg
  tensorflow_datasets/testing/test_data/fake_examples/food101/food-101/images/cheesecake/006.jpg
  tensorflow_datasets/testing/test_data/fake_examples/food101/food-101/meta/test.json
  tensorflow_datasets/testing/test_data/fake_examples/food101/food-101/meta/train.json
Labels: being_merged, cla: yes

#1210 Beam tfrecords writer. Issue #677. Issue #737.
  docs/beam_datasets.md
  tensorflow_datasets/audio/nsynth.py
  tensorflow_datasets/audio/nsynth_test.py
  tensorflow_datasets/core/_sharded_files.py
  tensorflow_datasets/core/_sharded_files_test.py
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_beam_test.py
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/shuffle.py
  tensorflow_datasets/core/shuffle_test.py
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/tfrecords_reader_test.py
  tensorflow_datasets/core/tfrecords_writer.py
  tensorflow_datasets/core/tfrecords_writer_test.py
  tensorflow_datasets/image/abstract_reasoning.py
  tensorflow_datasets/image/abstract_reasoning_test.py
  tensorflow_datasets/image/bigearthnet.py
  tensorflow_datasets/image/bigearthnet_test.py
  tensorflow_datasets/testing/test_data/fake_examples/wikipedia/enwiki_fake2.xml
  tensorflow_datasets/text/c4.py
  tensorflow_datasets/text/c4_test.py
  tensorflow_datasets/text/wikipedia.py
  tensorflow_datasets/text/wikipedia_test.py
Labels: cla: no

#1294 Update NSynth f0 and loudness computations for consistency with ddsp lib.
  tensorflow_datasets/audio/nsynth.py
Labels: cla: no

#1296 wikipedia dataset: remove hz language, there are no articles.
  tensorflow_datasets/text/wikipedia.py
Labels: cla: no

#1295 Add explicit attrs version
  setup.py
Labels: cla: no

#1303 Run calc_loudness op in a session.
  tensorflow_datasets/audio/nsynth.py
  tensorflow_datasets/audio/nsynth_test.py
  tensorflow_datasets/testing/test_data/fake_examples/nsynth/gansynth_splits.csv
Labels: cla: no

#1305 Fix missing label.txt file from setup.py for ImagenetResized
  setup.py
Labels: cla: no
