Repository tensorflow/datasets, pull requests merged in 2019-04, with the labels that each got.

#396 add the checksum file for the Oxford-IIIT pet dataset.
  tensorflow_datasets/url_checksums/oxford_iiit_pet.txt
Labels: cla: no

#399 Log if dataset is already available in our GCS bucket
  tensorflow_datasets/core/constants.py
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/utils/gcs_utils.py
  tensorflow_datasets/core/utils/gcs_utils_test.py
  tensorflow_datasets/testing/test_case.py
Labels: cla: no

#400 Disable Py3 tests for beam
  tensorflow_datasets/core/dataset_builder_beam_test.py
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: no

#401 Make Wikipedia redirect filter more robust.
  tensorflow_datasets/text/wikipedia.py
Labels: cla: no

#402 Log if dataset is already available in our GCS bucket (redux)
  tensorflow_datasets/core/constants.py
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/utils/gcs_utils.py
  tensorflow_datasets/core/utils/gcs_utils_test.py
  tensorflow_datasets/testing/test_case.py
Labels: cla: no

#410 Fix setup.py
  setup.py
Labels: cla: no

#411 Add WMT15 and WMT support for subword tokenization.
  tensorflow_datasets/translate/__init__.py
  tensorflow_datasets/translate/wmt.py
  tensorflow_datasets/translate/wmt15.py
  tensorflow_datasets/url_checksums/wmt15_translate.txt
Labels: cla: no

#403 Fix cats_vs_dogs dataset on Windows
  tensorflow_datasets/image/cats_vs_dogs.py
Labels: cla: yes

#417 Add WMT16.
  tensorflow_datasets/translate/__init__.py
  tensorflow_datasets/translate/wmt.py
  tensorflow_datasets/translate/wmt16.py
  tensorflow_datasets/translate/wmt18.py
  tensorflow_datasets/url_checksums/wmt16_translate.txt
Labels: cla: no

#422 SUN397 dataset updated to v1.1.0.
  tensorflow_datasets/image/sun.py
  tensorflow_datasets/testing/sun397.py
  tensorflow_datasets/testing/test_data/fake_examples/sun397/SUN397.tar.gz
Labels: cla: no

#420 FeaturesDict doc: use output instead of target
  tensorflow_datasets/core/features/feature.py
Labels: cla: yes

#429 Increment WMT19 version since a missing subset was added to RU-EN (commoncrawl).
  tensorflow_datasets/translate/wmt19.py
Labels: cla: no

#424 Update europarl_v8 name in WMT17.
  tensorflow_datasets/translate/wmt15.py
  tensorflow_datasets/translate/wmt17.py
Labels: cla: no

#428 Allow disabling builder tests with empty list
  tensorflow_datasets/core/lazy_imports_test.py
  tensorflow_datasets/image/imagenet2012_corrupted_test.py
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: no

#430 Fix TF 1.12 decode_image bug
  tensorflow_datasets/image/sun.py
Labels: cla: no

#395 Support video features that are decoded using ffmpeg
  tensorflow_datasets/core/features/video_feature.py
  tensorflow_datasets/core/features/video_feature_test.py
  tensorflow_datasets/testing/test_data/video.json
  tensorflow_datasets/testing/test_data/video.mkv
Labels: cla: no

#409 Add the UCF-101 dataset to tfds
  tensorflow_datasets/testing/test_data/fake_examples/ucf101/splits/ucfTrainTestlist/testlist01.txt
  tensorflow_datasets/testing/test_data/fake_examples/ucf101/splits/ucfTrainTestlist/trainlist01.txt
  tensorflow_datasets/testing/test_data/fake_examples/ucf101/videos/UCF101/v_Archery_g08_c04.avi
  tensorflow_datasets/testing/test_data/fake_examples/ucf101/videos/UCF101/v_Archery_g09_c03.avi
  tensorflow_datasets/testing/test_data/fake_examples/ucf101/videos/UCF101/v_Nunchucks_g08_c05.avi
  tensorflow_datasets/testing/test_data/fake_examples/ucf101/videos/UCF101/v_Nunchucks_g09_c05.avi
  tensorflow_datasets/testing/test_data/fake_examples/ucf101/videos/UCF101/v_Nunchucks_g09_c06.avi
  tensorflow_datasets/url_checksums/ucf101.txt
  tensorflow_datasets/video/__init__.py
  tensorflow_datasets/video/ucf101.py
  tensorflow_datasets/video/ucf101_labels.txt
  tensorflow_datasets/video/ucf101_test.py
Labels: cla: no

#355 Adds the Smallnorb data set.
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/smallnorb.py
  tensorflow_datasets/image/smallnorb_test.py
  tensorflow_datasets/testing/smallnorb.py
  tensorflow_datasets/testing/smallnorb_test.py
  tensorflow_datasets/testing/test_data/fake_examples/smallnorb/smallnorb-5x01235x9x18x6x2x96x96-testing-cat.mat
  tensorflow_datasets/testing/test_data/fake_examples/smallnorb/smallnorb-5x01235x9x18x6x2x96x96-testing-dat.mat
  tensorflow_datasets/testing/test_data/fake_examples/smallnorb/smallnorb-5x01235x9x18x6x2x96x96-testing-info.mat
  tensorflow_datasets/testing/test_data/fake_examples/smallnorb/smallnorb-5x46789x9x18x6x2x96x96-training-cat.mat
  tensorflow_datasets/testing/test_data/fake_examples/smallnorb/smallnorb-5x46789x9x18x6x2x96x96-training-dat.mat
  tensorflow_datasets/testing/test_data/fake_examples/smallnorb/smallnorb-5x46789x9x18x6x2x96x96-training-info.mat
  tensorflow_datasets/url_checksums/smallnorb.txt
Labels: cla: no

#427 Internal
  tensorflow_datasets/core/utils/gcs_utils.py
Labels: cla: no

#432 Update Beam doc
  docs/_book.yaml
  docs/add_dataset.md
  docs/beam_datasets.md
Labels: cla: no

#446 change number of shards to 1 for oxford_pet_iiit_dataset.
  tensorflow_datasets/image/oxford_iiit_pet.py
Labels: cla: no

#383 Use TFDV to compute statistics in TFDS
  setup.py
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/dataset_info_test.py
Labels: cla: no

#451 Add CNN/DailyMail summarization dataset.
  tensorflow_datasets/testing/test_data/fake_examples/cnn_dailymail/all_test.txt
  tensorflow_datasets/testing/test_data/fake_examples/cnn_dailymail/all_train.txt
  tensorflow_datasets/testing/test_data/fake_examples/cnn_dailymail/all_val.txt
  tensorflow_datasets/testing/test_data/fake_examples/cnn_dailymail/cnn/stories/4a3e4cbfaa28b1b37428a54adc321aaa43509d69.story
  tensorflow_datasets/testing/test_data/fake_examples/cnn_dailymail/cnn/stories/5e7fa7cab7be33b6097b4c23affc67770d7f32f9.story
  tensorflow_datasets/testing/test_data/fake_examples/cnn_dailymail/cnn/stories/be1b6a7ba1888ccbe1783a603f84c54f63de1807.story
  tensorflow_datasets/testing/test_data/fake_examples/cnn_dailymail/cnn/stories/cf8293c3fa4465255e2021c467a1d663061c52ab.story
  tensorflow_datasets/testing/test_data/fake_examples/cnn_dailymail/dailymail/stories/479965b88839575fd65a1bd14c703523b6e2f437.story
  tensorflow_datasets/testing/test_data/fake_examples/cnn_dailymail/dailymail/stories/610fac8b33220bbef756d9423883c9003fa589f8.story
  tensorflow_datasets/testing/test_data/fake_examples/cnn_dailymail/dailymail/stories/ce7b8f6c6f9cea8689dc45bade4686e1fcfc732a.story
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/cnn_dailymail.py
  tensorflow_datasets/text/cnn_dailymail_test.py
  tensorflow_datasets/url_checksums/cnn_dailymail.txt
Labels: cla: no

#421 misc utils renaming and import fixes.
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/proto/__init__.py
  tensorflow_datasets/core/utils/__init__.py
  tensorflow_datasets/core/utils/tqdm_utils.py
Labels: cla: no

#455 Use TFDV to compute statistics in TFDS
  setup.py
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/dataset_info_test.py
Labels: cla: no

#449 Minor comment update for map_fn with sequence connectors
  tensorflow_datasets/core/features/sequence_feature.py
Labels: cla: no

#426 Ingested GLUE into TFDS
  tensorflow_datasets/testing/test_data/fake_examples/glue/CoLA/dev.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/CoLA/test.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/CoLA/train.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/MNLI/dev_matched.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/MNLI/dev_mismatched.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/MNLI/test_matched.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/MNLI/test_mismatched.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/MNLI/train.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/MRPC/mrpc_dev_ids.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/MRPC/msr_paraphrase_test.txt
  tensorflow_datasets/testing/test_data/fake_examples/glue/MRPC/msr_paraphrase_train.txt
  tensorflow_datasets/testing/test_data/fake_examples/glue/QNLI/dev.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/QNLI/test.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/QNLI/train.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/QQP/dev.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/QQP/test.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/QQP/train.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/RTE/dev.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/RTE/test.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/RTE/train.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/SST-2/dev.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/SST-2/test.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/SST-2/train.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/STS-B/dev.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/STS-B/test.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/STS-B/train.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/WNLI/dev.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/WNLI/test.tsv
  tensorflow_datasets/testing/test_data/fake_examples/glue/WNLI/train.tsv
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/glue.py
  tensorflow_datasets/text/glue_test.py
  tensorflow_datasets/url_checksums/glue.txt
Labels: cla: no

#452 Imagenet: Download archives from website, no longer requires manual download.
  tensorflow_datasets/image/imagenet.py
  tensorflow_datasets/image/imagenet2012_corrupted_test.py
  tensorflow_datasets/image/imagenet_test.py
  tensorflow_datasets/url_checksums/imagenet2012.txt
Labels: cla: no

#458 Add offset option to the dataset split
  docs/splits.md
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_utils.py
  tensorflow_datasets/core/dataset_utils_test.py
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/core/splits_test.py
Labels: cla: no

#464 Clarify doc to use the create_new_dataset script
  docs/add_dataset.md
Labels: cla: no

#443 Fixes#442 : Corrected the Path for testing Directory
  docs/add_dataset.md
Labels: cla: yes

#465 Add support for beam liquid sharding.
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_beam_test.py
Labels: cla: no

#459 Adding Schema.org annotations to Tensorflow Datasets via microdata format. Closes #85.
  docs/datasets.md
  tensorflow_datasets/scripts/document_datasets.py
  tensorflow_datasets/scripts/document_datasets_test.py
Labels: cla: no

#463 Add `version` param to `load`, fails if given version cannot be satisfied.
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/registered.py
  tensorflow_datasets/core/registered_test.py
  tensorflow_datasets/core/utils/version.py
  tensorflow_datasets/core/utils/version_test.py
Labels: cla: no

#469 New version of the Diabetic Retinopathy dataset:
  tensorflow_datasets/image/diabetic_retinopathy_detection.py
  tensorflow_datasets/image/diabetic_retinopathy_detection_test.py
  tensorflow_datasets/testing/test_data/fake_examples/diabetic_retinopathy_detection/README.md
  tensorflow_datasets/testing/test_data/fake_examples/diabetic_retinopathy_detection/retinopathy_solution.csv
  tensorflow_datasets/url_checksums/diabetic_retinopathy_detection.txt
Labels: cla: no

#453 Update OpenImagesV4 dataset.
  tensorflow_datasets/image/open_images.py
  tensorflow_datasets/image/open_images_classes_all.txt
  tensorflow_datasets/image/open_images_classes_boxable.txt
  tensorflow_datasets/image/open_images_classes_trainable.txt
  tensorflow_datasets/image/open_images_test.py
  tensorflow_datasets/testing/open_images.py
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/class_descriptions.csv
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/s3-tar_test_sha2.tar
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/s3-tar_train_sha1_0.tar
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/s3-tar_train_sha1_1.tar
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/s3-tar_train_sha1_2.tar
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/s3-tar_train_sha1_3.tar
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/s3-tar_train_sha1_4.tar
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/s3-tar_train_sha1_5.tar
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/s3-tar_train_sha1_6.tar
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/s3-tar_train_sha1_7.tar
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/s3-tar_train_sha1_8.tar
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/s3-tar_train_sha1_9.tar
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/s3-tar_train_sha1_a.tar
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/s3-tar_train_sha1_b.tar
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/s3-tar_train_sha1_c.tar
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/s3-tar_train_sha1_d.tar
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/s3-tar_train_sha1_e.tar
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/s3-tar_train_sha1_f.tar
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/s3-tar_validation_sha3.tar
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/test-annotations-bbox.csv
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/test-human-labels.csv
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/test-machine-labels.csv
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/train-annotations-bbox.csv
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/train-human-labels.csv
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/train-machine-labels.csv
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/validation-annotations-bbox.csv
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/validation-human-labels.csv
  tensorflow_datasets/testing/test_data/fake_examples/open_images_v4/validation-machine-labels.csv
Labels: cla: no

#474 Rollback due tests failing.
  tensorflow_datasets/image/diabetic_retinopathy_detection.py
  tensorflow_datasets/image/diabetic_retinopathy_detection_test.py
  tensorflow_datasets/testing/test_data/fake_examples/diabetic_retinopathy_detection/README.md
  tensorflow_datasets/testing/test_data/fake_examples/diabetic_retinopathy_detection/retinopathy_solution.csv
  tensorflow_datasets/url_checksums/diabetic_retinopathy_detection.txt
Labels: cla: no

#461 Add second citation for CNN/DailyMail summarization dataset.
  tensorflow_datasets/text/cnn_dailymail.py
Labels: cla: no

#476 Add - to the accepted config name characters and escape curly braces in error message.
  tensorflow_datasets/core/registered.py
Labels: cla: no

#381 Add datasets support to kaggle downloader
  tensorflow_datasets/core/download/kaggle.py
Labels: cla: yes

#466 Refactored MultiNLI to use ClassLabel feature and exposed both matched and mismatched validation sets.
  tensorflow_datasets/testing/test_data/fake_examples/multi_nli/multinli_1.0/multinli_1.0_dev_matched.txt
  tensorflow_datasets/testing/test_data/fake_examples/multi_nli/multinli_1.0/multinli_1.0_dev_mismatched.txt
  tensorflow_datasets/text/multi_nli.py
  tensorflow_datasets/text/multi_nli_test.py
Labels: cla: no

#475 Fix regex for parsing builder input string and fix error message.
  tensorflow_datasets/core/registered_test.py
Labels: cla: no

#479 Version of DiabeticRetinopathyDetection should be 2.0.0, not 0.2.0.
  tensorflow_datasets/image/diabetic_retinopathy_detection.py
Labels: cla: no

#480 Refactored MNLI on GLUE to have matched and mismatched splits.
  tensorflow_datasets/text/glue.py
  tensorflow_datasets/text/glue_test.py
Labels: cla: no

#482 Add warning about Beam using DatasetBuilder methods
  docs/beam_datasets.md
Labels: cla: no

#450 Add ParaCrawl corpus to TFDS.
  tensorflow_datasets/testing/test_data/fake_examples/para_crawl/en-hu.bicleaner07.txt
  tensorflow_datasets/translate/__init__.py
  tensorflow_datasets/translate/para_crawl.py
  tensorflow_datasets/translate/para_crawl_test.py
  tensorflow_datasets/url_checksums/para_crawl.txt
Labels: cla: no

#444 Fixes#390 Linted Image, Scripts & Structred Directory
  tensorflow_datasets/image/dsprites.py
  tensorflow_datasets/image/oxford_iiit_pet.py
  tensorflow_datasets/image/shapes3d.py
  tensorflow_datasets/image/smallnorb.py
  tensorflow_datasets/image/smallnorb_test.py
  tensorflow_datasets/image/voc.py
  tensorflow_datasets/scripts/__init__.py
  tensorflow_datasets/scripts/download_and_prepare.py
  tensorflow_datasets/structured/titanic.py
Labels: cla: yes

#477 SplitGenerator arguments modified in add_dataset.md
  docs/add_dataset.md
Labels: cla: yes

#484 Adds the abstract reasoning data set.
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/abstract_reasoning.py
  tensorflow_datasets/image/abstract_reasoning_test.py
  tensorflow_datasets/testing/abstract_reasoning.py
  tensorflow_datasets/testing/test_data/fake_examples/abstract_reasoning/attr.rel.pairs.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/abstract_reasoning/attr.rels.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/abstract_reasoning/attrs.line.type.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/abstract_reasoning/attrs.pairs.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/abstract_reasoning/attrs.shape.color.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/abstract_reasoning/extrapolation.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/abstract_reasoning/interpolation.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/abstract_reasoning/neutral.tar.gz
Labels: cla: no

#491 Fix Voc2017 which wasn't providing the same results
  tensorflow_datasets/image/voc.py
Labels: cla: no

#492 Fix document_datasets crash
  tensorflow_datasets/scripts/document_datasets.py
Labels: cla: no

#496 Fix the output_shapes and output_types attributes of a tf.data.Dataset.
  tensorflow_datasets/core/dataset_info.py
Labels: cla: no

#498 Rollback output_shapes commit
  tensorflow_datasets/core/dataset_info.py
Labels: cla: no

#502 Make gcs_files access more efficient with a prefix
  tensorflow_datasets/core/utils/gcs_utils.py
Labels: cla: no

#497 internal
  tensorflow_datasets/core/tf_compat.py
Labels: cla: no

#495 Update GCS documentation
  docs/_book.yaml
  docs/gcs.md
Labels: cla: no

#494 Fix configs in diabetic_retinopathy_detection. Images were not being rescaled.
  tensorflow_datasets/image/diabetic_retinopathy_detection.py
Labels: cla: no

#507 Add checksums to ImageNet corrupted
  tensorflow_datasets/url_checksums/imagenet2012_corrupted.txt
Labels: cla: no

#508 Expose tfds.is_dataset_on_gcs
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/utils/gcs_utils.py
  tensorflow_datasets/core/utils/gcs_utils_test.py
  tensorflow_datasets/public_api.py
  tensorflow_datasets/testing/test_case.py
Labels: cla: no

#509 Add load kwarg to check for dataset on GCS.
  tensorflow_datasets/core/registered.py
Labels: cla: no

#511 Remove CSV from file_format_adapter.
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/file_format_adapter.py
  tensorflow_datasets/core/file_format_adapter_test.py
Labels: cla: no

#513 Minor doc update for Cycle GAN
  tensorflow_datasets/image/cycle_gan.py
Labels: cla: no

#488 Added Parameters for Proxy Configuration #275
  tensorflow_datasets/core/download/downloader.py
Labels: cla: yes, enhancement

#516 Update doc
  docs/api_docs/python/_toc.yaml
  docs/api_docs/python/index.md
  docs/api_docs/python/tfds.md
  docs/api_docs/python/tfds/_api_cache.json
  docs/api_docs/python/tfds/file_adapter.md
  docs/api_docs/python/tfds/file_adapter/CSVAdapter.md
  docs/api_docs/python/tfds/file_adapter/FileFormatAdapter.md
  docs/api_docs/python/tfds/is_dataset_on_gcs.md
  docs/api_docs/python/tfds/load.md
  docs/datasets.md
Labels: cla: no

#515 Add Oxford 102 Category Flowers dataset.
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/oxford_flowers102.py
  tensorflow_datasets/image/oxford_flowers102_test.py
  tensorflow_datasets/testing/test_data/fake_examples/oxford_flowers102/imagelabels.mat
  tensorflow_datasets/testing/test_data/fake_examples/oxford_flowers102/images/jpg/image_00001.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_flowers102/images/jpg/image_00002.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_flowers102/images/jpg/image_00003.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_flowers102/images/jpg/image_00004.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_flowers102/images/jpg/image_00005.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_flowers102/images/jpg/image_00006.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_flowers102/images/jpg/image_00007.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_flowers102/images/jpg/image_00008.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_flowers102/images/jpg/image_00009.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_flowers102/images/jpg/image_00010.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_flowers102/setid.mat
  tensorflow_datasets/url_checksums/oxford_flowers102.txt
Labels: cla: no

#445 example checksum: handle nested objects
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: yes, enhancement

#512 document https://groups.google.com/forum/#!forum/tensorflow-datasets-public-announce group.
  README.md
Labels: cla: no

#520 Update doc
  docs/api_docs/python/tfds/_api_cache.json
  docs/api_docs/python/tfds/units.md
  docs/datasets.md
Labels: cla: no

#521 Fix encoding error on python2.
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: no

#506 Add Groove to TFDS.
  setup.py
  tensorflow_datasets/audio/__init__.py
  tensorflow_datasets/audio/groove.py
  tensorflow_datasets/audio/groove_test.py
  tensorflow_datasets/core/lazy_imports.py
  tensorflow_datasets/core/lazy_imports_test.py
  tensorflow_datasets/testing/test_data/fake_examples/groove/drummer3/session1/23_jazz_120_beat_4-4.mid
  tensorflow_datasets/testing/test_data/fake_examples/groove/drummer3/session1/23_jazz_120_beat_4-4.wav
  tensorflow_datasets/testing/test_data/fake_examples/groove/drummer3/session1/44_rock_120_beat_4-4.mid
  tensorflow_datasets/testing/test_data/fake_examples/groove/drummer3/session1/44_rock_120_beat_4-4.wav
  tensorflow_datasets/testing/test_data/fake_examples/groove/drummer7/session1/3_rock_86_fill_4-4.mid
  tensorflow_datasets/testing/test_data/fake_examples/groove/drummer7/session1/3_rock_86_fill_4-4.wav
  tensorflow_datasets/testing/test_data/fake_examples/groove/drummer7/session2/116_jazz-fusion_96_fill_4-4.mid
  tensorflow_datasets/testing/test_data/fake_examples/groove/info.csv
Labels: cla: no

#522 Rollback Groove
  setup.py
  tensorflow_datasets/audio/__init__.py
  tensorflow_datasets/audio/groove.py
  tensorflow_datasets/audio/groove_test.py
  tensorflow_datasets/core/lazy_imports.py
  tensorflow_datasets/core/lazy_imports_test.py
  tensorflow_datasets/testing/test_data/fake_examples/groove/drummer3/session1/23_jazz_120_beat_4-4.mid
  tensorflow_datasets/testing/test_data/fake_examples/groove/drummer3/session1/23_jazz_120_beat_4-4.wav
  tensorflow_datasets/testing/test_data/fake_examples/groove/drummer3/session1/44_rock_120_beat_4-4.mid
  tensorflow_datasets/testing/test_data/fake_examples/groove/drummer3/session1/44_rock_120_beat_4-4.wav
  tensorflow_datasets/testing/test_data/fake_examples/groove/drummer7/session1/3_rock_86_fill_4-4.mid
  tensorflow_datasets/testing/test_data/fake_examples/groove/drummer7/session1/3_rock_86_fill_4-4.wav
  tensorflow_datasets/testing/test_data/fake_examples/groove/drummer7/session2/116_jazz-fusion_96_fill_4-4.mid
  tensorflow_datasets/testing/test_data/fake_examples/groove/info.csv
Labels: cla: no

#514 Add unsupervised part of the Large Movie Review Dataset.
  tensorflow_datasets/testing/test_data/fake_examples/imdb_reviews/README.md
  tensorflow_datasets/testing/test_data/fake_examples/imdb_reviews/aclImdb/train/unsup/0_0.txt
  tensorflow_datasets/testing/test_data/fake_examples/imdb_reviews/aclImdb/train/unsup/123_0.txt
  tensorflow_datasets/testing/test_data/fake_examples/imdb_reviews/aclImdb/train/unsup/77_0.txt
  tensorflow_datasets/testing/test_data/fake_examples/imdb_reviews/aclImdb_v1.tar.gz
  tensorflow_datasets/text/imdb.py
  tensorflow_datasets/text/imdb_test.py
Labels: cla: no

#524 Test features are pickable (for Beam). Fix where needed.
  setup.py
  tensorflow_datasets/core/features/image_feature.py
  tensorflow_datasets/core/features/sequence_feature.py
  tensorflow_datasets/core/features/text/text_encoder.py
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no

#527 extractor: no more distinction between TAR and TAR_GZ, they are interchangeable.
  tensorflow_datasets/core/download/extractor.py
  tensorflow_datasets/core/download/resource.py
Labels: cla: no

#525 AbstractReasoning: use Video Feature.
  tensorflow_datasets/image/abstract_reasoning.py
Labels: cla: no

#529 Update doc
  docs/api_docs/python/tfds/_api_cache.json
  docs/api_docs/python/tfds/features/Image.md
  docs/api_docs/python/tfds/features/Sequence.md
  docs/api_docs/python/tfds/features/Video.md
  docs/datasets.md
Labels: cla: no
