Repository tensorflow/datasets, pull requests merged in 2019-08, with the labels that each got.

#837 Fix some minor typos in Beam dataset docs.
  docs/beam_datasets.md
Labels: cla: no

#842 Fix wrong url doc with stanford_dogs
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/download/checksums.py
  tensorflow_datasets/core/visualization.py
  tensorflow_datasets/image/stanford_dogs.py
Labels: cla: no

#846 Rename lazy_imports -> lazy_imports_lib to fix Kokoro tests
  docs/add_dataset.md
  docs/api_docs/python/tfds/core/lazy_imports.md
  tensorflow_datasets/core/__init__.py
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/features/audio_feature.py
  tensorflow_datasets/core/file_format_adapter.py
  tensorflow_datasets/core/lazy_imports_lib.py
  tensorflow_datasets/core/lazy_imports_lib_test.py
  tensorflow_datasets/core/visualization.py
  tensorflow_datasets/testing/colorectal_histology.py
Labels: cla: no

#848 Add cifar10-c extra corruptions.
  tensorflow_datasets/image/cifar10_corrupted.py
Labels: cla: no

#855 Automated documentation update
  docs/api_docs/python/_toc.yaml
  docs/api_docs/python/index.md
  docs/api_docs/python/tfds.md
  docs/api_docs/python/tfds/_api_cache.json
  docs/api_docs/python/tfds/download.md
  docs/api_docs/python/tfds/download/add_checksums_dir.md
  docs/api_docs/python/tfds/show_examples.md
  docs/api_docs/python/tfds/testing/DatasetBuilderTestCase.md
  docs/api_docs/python/tfds/testing/FeatureExpectationsTestCase.md
  docs/api_docs/python/tfds/testing/SubTestCase.md
  docs/api_docs/python/tfds/testing/TestCase.md
  docs/datasets.md
Labels: cla: no

#852 Fix line endings for URL checksum files on Windows
  tensorflow_datasets/core/download/checksums.py
Labels: cla: no

#860 Automated documentation update
  docs/datasets.md
Labels: cla: no

#857 Increase resisc45 version
  tensorflow_datasets/image/resisc45.py
  tensorflow_datasets/image/resisc45_test.py
Labels: cla: no

#850 Update Sun397 dataset with new configs.
  tensorflow_datasets/image/sun.py
  tensorflow_datasets/image/sun397_tfds_te.txt
  tensorflow_datasets/image/sun397_tfds_tr.txt
  tensorflow_datasets/image/sun397_tfds_va.txt
  tensorflow_datasets/image/sun_test.py
  tensorflow_datasets/testing/test_data/fake_examples/sun397/Partitions/Testing_01.txt
  tensorflow_datasets/testing/test_data/fake_examples/sun397/Partitions/Training_01.txt
  tensorflow_datasets/testing/test_data/fake_examples/sun397/SUN397.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/sun397/sun397_tfds_te.txt
  tensorflow_datasets/testing/test_data/fake_examples/sun397/sun397_tfds_tr.txt
  tensorflow_datasets/testing/test_data/fake_examples/sun397/sun397_tfds_va.txt
  tensorflow_datasets/url_checksums/sun397.txt
Labels: cla: no

#872 Automated documentation update
  docs/datasets.md
Labels: cla: no

#875 show_examples support for datasets with multiple image features.
  tensorflow_datasets/core/visualization.py
Labels: cla: no

#866 TFDS: util decorator to drop key for non S3 versions. Issue #737.
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#865 TFDS: use drop_key_if_not_s3 decorator on all builders supporting S3. Issue #737.
  tensorflow_datasets/image/caltech.py
  tensorflow_datasets/image/cats_vs_dogs.py
  tensorflow_datasets/image/cbis_ddsm.py
  tensorflow_datasets/image/celeba.py
  tensorflow_datasets/image/celebahq.py
  tensorflow_datasets/image/chexpert.py
  tensorflow_datasets/image/cifar.py
  tensorflow_datasets/image/clevr.py
  tensorflow_datasets/image/coco2014_legacy.py
  tensorflow_datasets/image/colorectal_histology.py
  tensorflow_datasets/image/cycle_gan.py
  tensorflow_datasets/image/diabetic_retinopathy_detection.py
  tensorflow_datasets/image/downsampled_imagenet.py
  tensorflow_datasets/image/dsprites.py
  tensorflow_datasets/image/dtd.py
  tensorflow_datasets/image/eurosat.py
  tensorflow_datasets/image/flowers.py
  tensorflow_datasets/image/horses_or_humans.py
  tensorflow_datasets/image/imagenet.py
  tensorflow_datasets/image/imagenet2012_corrupted.py
  tensorflow_datasets/image/lsun.py
  tensorflow_datasets/image/mnist.py
  tensorflow_datasets/image/omniglot.py
  tensorflow_datasets/image/open_images.py
  tensorflow_datasets/image/oxford_flowers102.py
  tensorflow_datasets/image/oxford_iiit_pet.py
  tensorflow_datasets/image/patch_camelyon.py
  tensorflow_datasets/image/pet_finder.py
  tensorflow_datasets/image/quickdraw.py
  tensorflow_datasets/image/rock_paper_scissors.py
  tensorflow_datasets/image/shapes3d.py
  tensorflow_datasets/image/smallnorb.py
  tensorflow_datasets/image/so2sat.py
  tensorflow_datasets/image/sun.py
  tensorflow_datasets/image/svhn.py
  tensorflow_datasets/image/uc_merced.py
  tensorflow_datasets/image/voc.py
  tensorflow_datasets/video/bair_robot_pushing.py
Labels: cla: no

#867 TFDS: librispeech: Add S3 version. Issue #737.
  tensorflow_datasets/audio/librispeech.py
  tensorflow_datasets/audio/librispeech_test.py
Labels: cla: no

#868 TFDS: groove: Add S3 version. Issue #737.
  tensorflow_datasets/audio/groove.py
  tensorflow_datasets/audio/groove_test.py
Labels: cla: no

#869 TFDS: nsynth: Add S3 version. Issue #737.
  tensorflow_datasets/audio/nsynth.py
  tensorflow_datasets/audio/nsynth_test.py
Labels: cla: no

#863 Add remaining Imagenet-C corruptions + extra corruptions.
  tensorflow_datasets/image/corruptions.py
  tensorflow_datasets/image/imagenet2012_corrupted.py
Labels: cla: no

#881 Rename tab.
  docs/_book.yaml
Labels: cla: no

#882 Increase number of shards in Wikipedia to allow increased read parallelism.
  tensorflow_datasets/text/wikipedia.py
Labels: cla: no

#879 Fix DatasetBuilderTestCase fake example dir path
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: yes

#877 TFDS: cifar10_corrupted: Add S3 version. Issue #737.
  tensorflow_datasets/image/cifar10_corrupted.py
  tensorflow_datasets/image/cifar10_corrupted_test.py
Labels: cla: no

#880 Add Visual Domain Decathlon datasets.
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/visual_domain_decathlon.py
  tensorflow_datasets/image/visual_domain_decathlon_test.py
  tensorflow_datasets/testing/test_data/fake_examples/visual_domain_decathlon/aircraft.tar
  tensorflow_datasets/testing/test_data/fake_examples/visual_domain_decathlon/decathlon-1.0/annotations/aircraft_test_stripped.json
  tensorflow_datasets/testing/test_data/fake_examples/visual_domain_decathlon/decathlon-1.0/annotations/aircraft_train.json
  tensorflow_datasets/testing/test_data/fake_examples/visual_domain_decathlon/decathlon-1.0/annotations/aircraft_val.json
  tensorflow_datasets/testing/test_data/fake_examples/visual_domain_decathlon/decathlon-1.0/annotations/imagenet12_test_stripped.json
  tensorflow_datasets/testing/test_data/fake_examples/visual_domain_decathlon/decathlon-1.0/annotations/imagenet12_train.json
  tensorflow_datasets/testing/test_data/fake_examples/visual_domain_decathlon/decathlon-1.0/annotations/imagenet12_val.json
  tensorflow_datasets/testing/test_data/fake_examples/visual_domain_decathlon/imagenet12.tar
  tensorflow_datasets/url_checksums/visual_domain_decathlon.txt
Labels: cla: no

#876 TFDS: image_folder: Add S3 version. Issue #737.
  tensorflow_datasets/image/image_folder.py
  tensorflow_datasets/image/image_folder_test.py
Labels: cla: no

#886 Add missing DATASET_FILES to setup.py.
  setup.py
Labels: cla: no

#878 TFDS: mnist_corrupted: Add S3 version. Issue #737.
  tensorflow_datasets/image/mnist_corrupted.py
  tensorflow_datasets/image/mnist_corrupted_test.py
Labels: cla: no

#889 Add config to Diabetic Retinopathy with the preprocessing used by the winner of the Kaggle competition in 2015.
  tensorflow_datasets/image/diabetic_retinopathy_detection.py
Labels: cla: no

#885 Enable Imagenet corruptions on Imagenet training set
  tensorflow_datasets/image/imagenet2012_corrupted.py
  tensorflow_datasets/image/imagenet2012_corrupted_test.py
Labels: cla: no

#895 Fix Visual Decathlon's ImageNet url checksum.
  tensorflow_datasets/url_checksums/visual_domain_decathlon.txt
Labels: cla: no

#888 Fix broken link on README.md.
  docs/README.md
Labels: cla: yes

#891 Add missing citations
  tensorflow_datasets/image/cycle_gan.py
  tensorflow_datasets/image/downsampled_imagenet.py
Labels: cla: yes

#894 Automated documentation update
  docs/api_docs/python/tfds/load.md
  docs/api_docs/python/tfds/testing/DatasetBuilderTestCase.md
  docs/api_docs/python/tfds/testing/FeatureExpectationsTestCase.md
  docs/api_docs/python/tfds/testing/SubTestCase.md
  docs/api_docs/python/tfds/testing/TestCase.md
  docs/catalog/caltech_birds2010.md
  docs/catalog/caltech_birds2011.md
  docs/catalog/diabetic_retinopathy_detection.md
  docs/catalog/imagenet2012_corrupted.md
  docs/catalog/visual_domain_decathlon.md
Labels: cla: no

#898 Automated documentation update
  docs/api_docs/python/index.md
  docs/api_docs/python/tfds/_api_cache.json
  docs/api_docs/python/tfds/features/Image.md
  docs/catalog/_toc.yaml
  docs/catalog/cycle_gan.md
  docs/catalog/downsampled_imagenet.md
  docs/catalog/lfw.md
  docs/catalog/overview.md
  docs/catalog/visual_domain_decathlon.md
Labels: cla: no

#887 do not shuffle files by default on train split anymore.
  tensorflow_datasets/core/registered.py
  tensorflow_datasets/image/image_folder.py
Labels: cla: no

#902 fix tests.
  tensorflow_datasets/core/registered_test.py
Labels: cla: no

#398 MIT Scene Parse 150 dataset
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/scene_parse_150.py
  tensorflow_datasets/image/scene_parse_150_test.py
  tensorflow_datasets/testing/test_data/fake_examples/scene_parse150/annotations/training/image_0.png
  tensorflow_datasets/testing/test_data/fake_examples/scene_parse150/annotations/training/image_1.png
  tensorflow_datasets/testing/test_data/fake_examples/scene_parse150/annotations/training/image_2.png
  tensorflow_datasets/testing/test_data/fake_examples/scene_parse150/annotations/validation/image_3.png
  tensorflow_datasets/testing/test_data/fake_examples/scene_parse150/annotations/validation/image_4.png
  tensorflow_datasets/testing/test_data/fake_examples/scene_parse150/annotations/validation/image_5.png
  tensorflow_datasets/testing/test_data/fake_examples/scene_parse150/images/training/image_0.jpg
  tensorflow_datasets/testing/test_data/fake_examples/scene_parse150/images/training/image_1.jpg
  tensorflow_datasets/testing/test_data/fake_examples/scene_parse150/images/training/image_2.jpg
  tensorflow_datasets/testing/test_data/fake_examples/scene_parse150/images/validation/image_3.jpg
  tensorflow_datasets/testing/test_data/fake_examples/scene_parse150/images/validation/image_4.jpg
  tensorflow_datasets/testing/test_data/fake_examples/scene_parse150/images/validation/image_5.jpg
Labels: being_merged, cla: yes, dataset request

#903 Fix docstring typo in tfds feature.py
  tensorflow_datasets/core/features/feature.py
Labels: cla: no

#913 More explicit error messages with tfds.show_examples
  tensorflow_datasets/core/visualization.py
Labels: cla: no

#915 Add test util to mock datasets
  tensorflow_datasets/testing/__init__.py
  tensorflow_datasets/testing/mocking.py
  tensorflow_datasets/testing/mocking_test.py
Labels: cla: no

#912 Minor notebook updates
  docs/overview.ipynb
Labels: cla: no

#909 Update datasets link
  docs/add_dataset.md
  docs/api_docs/python/tfds.md
  docs/overview.ipynb
  docs/release_notes.md
  tensorflow_datasets/__init__.py
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#917 Minor docstring typo fix
  tensorflow_datasets/testing/mocking.py
Labels: cla: no

#916 Improve Image feature connector doc
  tensorflow_datasets/core/features/image_feature.py
Labels: cla: no

#914 Fix Visual Domain Decathlon dataset labels.
  tensorflow_datasets/image/visual_domain_decathlon.py
Labels: cla: no

#901 TFDS: shuffle.py: fix bug in struct packing/unpacking formats. Issue #896.
  tensorflow_datasets/core/shuffle.py
  tensorflow_datasets/core/shuffle_test.py
Labels: cla: no

#920 Change python version for notebook.
  docs/overview.ipynb
Labels: cla: no

#919 Update docstring links.
  tensorflow_datasets/__init__.py
Labels: cla: no

#825 Coil100
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/coil100.py
  tensorflow_datasets/image/coil100_test.py
  tensorflow_datasets/testing/coil100.py
  tensorflow_datasets/testing/test_data/fake_examples/coil100/obj1_0.png
  tensorflow_datasets/testing/test_data/fake_examples/coil100/obj1_10.png
  tensorflow_datasets/testing/test_data/fake_examples/coil100/obj1_15.png
  tensorflow_datasets/testing/test_data/fake_examples/coil100/obj1_20.png
  tensorflow_datasets/testing/test_data/fake_examples/coil100/obj1_5.png
  tensorflow_datasets/url_checksums/coil100.txt
Labels: cla: yes, dataset request

#922 Add missing "Split" in code example.
  tensorflow_datasets/core/splits.py
Labels: cla: no

#925 Automated documentation update
  docs/api_docs/python/_toc.yaml
  docs/api_docs/python/index.md
  docs/api_docs/python/tfds.md
  docs/api_docs/python/tfds/_api_cache.json
  docs/api_docs/python/tfds/core/SplitBase.md
  docs/api_docs/python/tfds/disable_progress_bar.md
  docs/api_docs/python/tfds/features/FeatureConnector.md
  docs/api_docs/python/tfds/features/Image.md
  docs/api_docs/python/tfds/load.md
  docs/api_docs/python/tfds/testing.md
  docs/api_docs/python/tfds/testing/mock_data.md
  docs/catalog/_toc.yaml
  docs/catalog/aflw2k3d.md
  docs/catalog/coil100.md
  docs/catalog/gap.md
  docs/catalog/overview.md
  docs/catalog/scene_parse150.md
  docs/catalog/visual_domain_decathlon.md
  docs/catalog/wikipedia.md
Labels: cla: no

#900 do not shuffle files by default on train split anymore.
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/registered.py
  tensorflow_datasets/core/registered_test.py
Labels: cla: no

#930 Update `tfds.load()` callers to specify `shuffle_files=True` when necessary.
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/video/moving_sequence.py
Labels: cla: no

#933 Update eurosat versions.
  tensorflow_datasets/image/eurosat.py
  tensorflow_datasets/image/eurosat_test.py
Labels: cla: no

#932 Automated documentation update
  docs/api_docs/python/tfds/core/BeamBasedBuilder.md
  docs/api_docs/python/tfds/core/DatasetBuilder.md
  docs/api_docs/python/tfds/core/GeneratorBasedBuilder.md
  docs/api_docs/python/tfds/load.md
  docs/api_docs/python/tfds/testing/DummyDatasetSharedGenerator.md
  docs/api_docs/python/tfds/testing/DummyMnist.md
  docs/catalog/_toc.yaml
  docs/catalog/deep_weeds.md
  docs/catalog/malaria.md
  docs/catalog/overview.md
  docs/catalog/stanford_online_products.md
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/stanford_online_products/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/stanford_online_products/1.0.0/image.image.json
  tensorflow_datasets/testing/metadata/stanford_online_products/1.0.0/super_class_id.labels.txt
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#934 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/eurosat.md
  docs/catalog/malaria.md
  docs/catalog/multi_nli_mismatch.md
  docs/catalog/overview.md
  docs/catalog/stanford_online_products.md
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#938 fix key collision in the datasets
  tensorflow_datasets/text/lm1b.py
  tensorflow_datasets/text/trivia_qa.py
Labels: cla: no

#937 Updated couple datasets to read using GFile api.
  tensorflow_datasets/image/caltech_birds.py
  tensorflow_datasets/image/cars196.py
  tensorflow_datasets/image/stanford_dogs.py
Labels: cla: no

#939 Automated documentation update
  docs/api_docs/python/tfds/disable_progress_bar.md
  docs/api_docs/python/tfds/features/text/SubwordTextEncoder.md
  docs/api_docs/python/tfds/features/text/TokenTextEncoder.md
  docs/api_docs/python/tfds/features/text/Tokenizer.md
  docs/api_docs/python/tfds/load.md
  tensorflow_datasets/testing/metadata/malaria/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/malaria/1.0.0/image.image.json
  tensorflow_datasets/testing/metadata/malaria/1.0.0/label.labels.txt
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/multi_nli_mismatch/plain_text/0.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#843 Updated SuperGLUE and added two new tasks
  tensorflow_datasets/testing/test_data/fake_examples/super_glue/BoolQ/test.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/super_glue/BoolQ/train.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/super_glue/BoolQ/val.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/super_glue/MultiRC/test.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/super_glue/MultiRC/train.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/super_glue/MultiRC/val.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/super_glue/ReCoRD/test.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/super_glue/ReCoRD/train.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/super_glue/ReCoRD/val.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/super_glue/WiC/test.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/super_glue/WiC/train.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/super_glue/WiC/val.jsonl
  tensorflow_datasets/text/super_glue.py
  tensorflow_datasets/text/super_glue_test.py
  tensorflow_datasets/url_checksums/super_glue.txt
Labels: cla: no

#940 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/caltech_birds2010.md
  docs/catalog/cars196.md
  docs/catalog/cmaterdb.md
  docs/catalog/malaria.md
  docs/catalog/multi_nli_mismatch.md
  docs/catalog/overview.md
  docs/catalog/super_glue.md
  docs/catalog/the300w_lp.md
  tensorflow_datasets/testing/metadata/caltech_birds2010/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/caltech_birds2010/0.1.0/image.image.json
  tensorflow_datasets/testing/metadata/caltech_birds2010/0.1.0/segmentation_mask.image.json
  tensorflow_datasets/testing/metadata/cars196/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/cars196/1.0.0/image.image.json
  tensorflow_datasets/testing/metadata/cars196/1.0.0/label.labels.txt
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/supported.txt
  tensorflow_datasets/testing/metadata/the300w_lp/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/the300w_lp/1.0.0/image.image.json
  tensorflow_datasets/testing/metadata/trivia_qa/1.0.0/dataset_info.json
Labels: cla: no

#941 Update `save_metadata` to remove slashes from feature keys.
  tensorflow_datasets/core/features/features_dict.py
  tensorflow_datasets/core/features/features_test.py
Labels: cla: no

#944 updating stanford_dogs to use gfile for reading files.
  tensorflow_datasets/image/stanford_dogs.py
Labels: cla: no

#946 Fix tfds super_glue version
  tensorflow_datasets/text/super_glue.py
Labels: cla: no

#947 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/cars196.md
  docs/catalog/cmaterdb.md
  docs/catalog/overview.md
  docs/catalog/places365_small.md
  docs/catalog/stanford_dogs.md
  docs/catalog/super_glue.md
  docs/catalog/the300w_lp.md
  tensorflow_datasets/testing/metadata/lm1b/bytes/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/lm1b/bytes/1.0.0/text.text.bytes
  tensorflow_datasets/testing/metadata/lm1b/plain_text/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/lm1b/subwords32k/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/lm1b/subwords32k/1.0.0/text.text.subwords
  tensorflow_datasets/testing/metadata/lm1b/subwords8k/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/lm1b/subwords8k/1.0.0/text.text.subwords
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/stanford_dogs/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/stanford_dogs/0.1.0/image.image.json
  tensorflow_datasets/testing/metadata/stanford_dogs/0.1.0/label.labels.txt
  tensorflow_datasets/testing/metadata/super_glue/boolq/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/super_glue/boolq/1.0.0/label.labels.txt
  tensorflow_datasets/testing/metadata/super_glue/record/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#948 Remove test label from place365 + windows compatibility
  tensorflow_datasets/image/categories_places365.txt
  tensorflow_datasets/image/places365_small.py
Labels: cla: no

#953 Automated documentation update
  docs/catalog/places365_small.md
  docs/catalog/super_glue.md
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/super_glue/boolq/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/super_glue/boolq/1.0.1/label.labels.txt
  tensorflow_datasets/testing/metadata/super_glue/cb/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/super_glue/cb/1.0.1/label.labels.txt
  tensorflow_datasets/testing/metadata/super_glue/copa/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/super_glue/copa/1.0.1/label.labels.txt
  tensorflow_datasets/testing/metadata/super_glue/multirc/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/super_glue/multirc/1.0.1/label.labels.txt
  tensorflow_datasets/testing/metadata/super_glue/record/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/super_glue/rte/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/super_glue/rte/1.0.1/label.labels.txt
  tensorflow_datasets/testing/metadata/super_glue/wic/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/super_glue/wic/1.0.1/label.labels.txt
  tensorflow_datasets/testing/metadata/super_glue/wsc.fixed/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/super_glue/wsc.fixed/1.0.1/label.labels.txt
  tensorflow_datasets/testing/metadata/super_glue/wsc/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/super_glue/wsc/1.0.1/label.labels.txt
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#954 Add EMNIST clarification on image orientation.
  tensorflow_datasets/image/mnist.py
Labels: cla: no

#958 Automated documentation update
  docs/catalog/emnist.md
  docs/catalog/places365_small.md
  docs/catalog/super_glue.md
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#956 Minor doc update
  docs/add_dataset.md
Labels: cla: no
