Repository tensorflow/datasets, pull requests merged in 2019-03, with the labels that each got.

#106 Fix inaccurate arg description for TranslationVariableLanguages.
  tensorflow_datasets/core/features/translation_feature.py
Labels: cla: no

#96 Update README.md
  README.md
Labels: cla: yes

#105 Merge of PR #96
  README.md
Labels: cla: no

#108 adding instructions on how to use Google Cloud Storage as data_dir.
  docs/README.md
  docs/gcs.md
Labels: cla: no

#110 internal change
  tensorflow_datasets/core/registered.py
  tensorflow_datasets/scripts/document_datasets.py
Labels: cla: no

#112 Merge of PR #100
  docs/datasets.md
Labels: cla: no

#115 Update ALL doc
  tensorflow_datasets/core/splits.py
Labels: cla: no

#100 Update dataset list
  docs/datasets.md
Labels: cla: yes

#111 improving the speed of the doc generator test.
  docs/datasets.md
  tensorflow_datasets/scripts/document_datasets.py
Labels: cla: no

#114 Update subsplits doc to point out that it is not deterministic
  docs/splits.md
Labels: cla: no

#109 typo in rock_paper_scissors.py
  tensorflow_datasets/image/rock_paper_scissors.py
Labels: cla: yes

#132 Internal change
  docs/datasets.md
  tensorflow_datasets/scripts/download_and_prepare.py
Labels: cla: no

#133 download_and_prepare: fix bug, if no datasets is given, prepare them all.
  tensorflow_datasets/scripts/download_and_prepare.py
Labels: cla: no

#126 Add "tf_flowers" to "image" dataset table.
  docs/datasets.md
Labels: cla: yes, documentation

#131 Fix docstring in accordance with the docs.
  tensorflow_datasets/image/celeba.py
Labels: cla: yes, documentation

#134 new auto-generated version of datasets.md
  docs/datasets.md
Labels: cla: no

#137 auto-generated datasets.md file.
  docs/datasets.md
Labels: cla: no

#144 improving the collaborator.md file
  CONTRIBUTING.md
Labels: cla: no

#150 Add bz2 extraction support
  setup.py
  tensorflow_datasets/core/download/extractor.py
  tensorflow_datasets/core/download/extractor_test.py
  tensorflow_datasets/core/download/resource.py
  tensorflow_datasets/core/download/resource_test.py
  tensorflow_datasets/testing/test_data/archives/foo.csv.bz2
Labels: cla: no

#151 Add ability to automatically write a LICENSE file with a dataset.
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/dataset_info_test.py
  tensorflow_datasets/core/proto/dataset_info.proto
  tensorflow_datasets/core/proto/dataset_info_generated_pb2.py
  tensorflow_datasets/testing/test_data/dataset_info/mnist/1.0.0/dataset_info.json
Labels: cla: no

#159 Added missing quickdraw_labels.txt file to setup.py.
  setup.py
Labels: cla: no

#160 Added kmnist dataset.
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/mnist.py
  tensorflow_datasets/image/mnist_test.py
  tensorflow_datasets/testing/mnist.py
  tensorflow_datasets/testing/test_data/fake_examples/kmnist/test-image
  tensorflow_datasets/testing/test_data/fake_examples/kmnist/test-label
  tensorflow_datasets/testing/test_data/fake_examples/kmnist/train-image
  tensorflow_datasets/testing/test_data/fake_examples/kmnist/train-label
Labels: cla: yes

#162 Remove unused import
  tensorflow_datasets/core/download/download_manager.py
Labels: cla: yes

#164 Update gcs docs.
  docs/gcs.md
Labels: cla: no

#168 Update add_dataset.md
  docs/add_dataset.md
Labels: cla: yes, documentation

#173 Support generating configs in parallel
  tensorflow_datasets/scripts/download_and_prepare.py
Labels: cla: no

#195 Fix download_and_prepare.py for single-config case
  tensorflow_datasets/scripts/download_and_prepare.py
Labels: cla: no

#197 Public: Added ftp support for TFDS
  tensorflow_datasets/core/download/downloader.py
  tensorflow_datasets/core/download/downloader_test.py
Labels: cla: no

#199 Added numpy to required packages
  setup.py
Labels: cla: yes

#218 Internal merge of #199
  setup.py
Labels: cla: no

#226 Fix spelling error in download_and_prepare
  tensorflow_datasets/scripts/download_and_prepare.py
Labels: cla: no

#229 tfds download_and_prepare: log config being used.
  tensorflow_datasets/scripts/download_and_prepare.py
Labels: cla: no

#219 Adds support for EXAMPLE_DIR config to tfds tests.
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: no

#244 Fixes#243: Fixed Typo in Horses Humans Script
  tensorflow_datasets/testing/horses_or_humans.py
Labels: cla: yes

#249 Check that tested configs are valid; fix tests
  setup.py
  tensorflow_datasets/audio/librispeech_test.py
  tensorflow_datasets/testing/dataset_builder_testing.py
  tensorflow_datasets/testing/horses_or_humans.py
  tensorflow_datasets/translate/ted_hrlr_test.py
Labels: cla: no

#247 Download manager: store checksums in code, instead of info files.
  docs/add_dataset.md
  setup.py
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/download/checksums.py
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/download_manager_test.py
  tensorflow_datasets/core/proto/dataset_info.proto
  tensorflow_datasets/core/proto/dataset_info_generated_pb2.py
  tensorflow_datasets/scripts/download_and_prepare.py
  tensorflow_datasets/url_checksums/bair_robot_pushing_small.txt
  tensorflow_datasets/url_checksums/cats_vs_dogs.txt
  tensorflow_datasets/url_checksums/celeb_a.txt
  tensorflow_datasets/url_checksums/celeb_a_hq.txt
  tensorflow_datasets/url_checksums/cifar10.txt
  tensorflow_datasets/url_checksums/cifar100.txt
  tensorflow_datasets/url_checksums/coco2014.txt
  tensorflow_datasets/url_checksums/colorectal_histology.txt
  tensorflow_datasets/url_checksums/colorectal_histology_large.txt
  tensorflow_datasets/url_checksums/diabetic_retinopathy_detection.txt
  tensorflow_datasets/url_checksums/fashion_mnist.txt
  tensorflow_datasets/url_checksums/flores_translate_neen.txt
  tensorflow_datasets/url_checksums/flores_translate_sien.txt
  tensorflow_datasets/url_checksums/horses_or_humans.txt
  tensorflow_datasets/url_checksums/imagenet2012.txt
  tensorflow_datasets/url_checksums/imdb_reviews.txt
  tensorflow_datasets/url_checksums/kmnist.txt
  tensorflow_datasets/url_checksums/lm1b.txt
  tensorflow_datasets/url_checksums/lsun.txt
  tensorflow_datasets/url_checksums/mnist.txt
  tensorflow_datasets/url_checksums/moving_mnist.txt
  tensorflow_datasets/url_checksums/multi_nli.txt
  tensorflow_datasets/url_checksums/nsynth.txt
  tensorflow_datasets/url_checksums/omniglot.txt
  tensorflow_datasets/url_checksums/open_images_v4.txt
  tensorflow_datasets/url_checksums/quickdraw_bitmap.txt
  tensorflow_datasets/url_checksums/rock_paper_scissors.txt
  tensorflow_datasets/url_checksums/squad.txt
  tensorflow_datasets/url_checksums/starcraft_video.txt
  tensorflow_datasets/url_checksums/svhn_cropped.txt
  tensorflow_datasets/url_checksums/ted_hrlr_translate.txt
  tensorflow_datasets/url_checksums/ted_multi_translate.txt
  tensorflow_datasets/url_checksums/tf_flowers.txt
  tensorflow_datasets/url_checksums/titanic.txt
  tensorflow_datasets/url_checksums/wmt_translate_ende.txt
  tensorflow_datasets/url_checksums/wmt_translate_enfr.txt
Labels: cla: no

#272 fix bug in checksums recording (last overwrites others).
  tensorflow_datasets/core/download/checksums.py
  tensorflow_datasets/core/download/download_manager.py
Labels: cla: no

#273 Fixes bug where height/width were ignored in get_random_picture.
  tensorflow_datasets/testing/fake_data_utils.py
Labels: cla: no

#277 Expose DatasetBuilder.data_dir.
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#276 Adds Caltech-101. Includes only the image-level labels, and not the bounding boxes.
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/caltech.py
  tensorflow_datasets/image/caltech101_labels.txt
  tensorflow_datasets/image/caltech_test.py
  tensorflow_datasets/testing/caltech.py
  tensorflow_datasets/testing/test_data/fake_examples/caltech101/3_ObjectCategories/accordion/image_0001.jpg
  tensorflow_datasets/testing/test_data/fake_examples/caltech101/3_ObjectCategories/accordion/image_0002.jpg
  tensorflow_datasets/testing/test_data/fake_examples/caltech101/3_ObjectCategories/airplanes/image_0001.jpg
  tensorflow_datasets/testing/test_data/fake_examples/caltech101/3_ObjectCategories/airplanes/image_0002.jpg
  tensorflow_datasets/testing/test_data/fake_examples/caltech101/3_ObjectCategories/anchor/image_0001.jpg
  tensorflow_datasets/testing/test_data/fake_examples/caltech101/3_ObjectCategories/anchor/image_0002.jpg
  tensorflow_datasets/url_checksums/caltech101.txt
Labels: cla: no

#281 Public: Simplify Flores to have 2 configs instead of 2 classes.
  tensorflow_datasets/translate/__init__.py
  tensorflow_datasets/translate/flores.py
  tensorflow_datasets/translate/flores_neen.py
  tensorflow_datasets/translate/flores_sien.py
Labels: cla: no

#296 Disable WMT in preparation for rewrite (#254)
  docs/datasets.md
  tensorflow_datasets/translate/wmt.py
  tensorflow_datasets/translate/wmt_ende.py
  tensorflow_datasets/translate/wmt_enfr.py
Labels: cla: no

#297 Update documentation
  docs/api_docs/python/tfds/Split.md
  docs/api_docs/python/tfds/_api_cache.json
  docs/api_docs/python/tfds/core/DatasetBuilder.md
  docs/api_docs/python/tfds/core/DatasetInfo.md
  docs/api_docs/python/tfds/core/GeneratorBasedBuilder.md
  docs/api_docs/python/tfds/download/DownloadConfig.md
  docs/api_docs/python/tfds/download/DownloadManager.md
  docs/api_docs/python/tfds/download/ExtractMethod.md
  docs/api_docs/python/tfds/features/Audio.md
  docs/api_docs/python/tfds/features/BBoxFeature.md
  docs/api_docs/python/tfds/features/FeatureConnector.md
  docs/api_docs/python/tfds/features/Image.md
  docs/api_docs/python/tfds/features/Sequence.md
  docs/api_docs/python/tfds/features/SequenceDict.md
  docs/api_docs/python/tfds/features/Tensor.md
  docs/api_docs/python/tfds/features/Video.md
  docs/api_docs/python/tfds/file_adapter/TFRecordExampleAdapter.md
  docs/api_docs/python/tfds/testing/DatasetBuilderTestCase.md
  docs/api_docs/python/tfds/testing/DummyDatasetSharedGenerator.md
  docs/api_docs/python/tfds/testing/DummyMnist.md
  docs/api_docs/python/tfds/testing/FeatureExpectationsTestCase.md
  docs/api_docs/python/tfds/testing/TestCase.md
  docs/datasets.md
Labels: cla: no

#316 Add missing url checksums.
  tensorflow_datasets/url_checksums/starcraft_video.txt
Labels: cla: no

#315 Remove borgcron and url_checksums files of datasets merged into flores.
  tensorflow_datasets/url_checksums/flores.txt
  tensorflow_datasets/url_checksums/flores_translate_sien.txt
Labels: cla: no

#295 Always move downloaded files to same location, simplify logic. Closes: #274.
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/download_manager_test.py
  tensorflow_datasets/core/download/downloader.py
  tensorflow_datasets/core/download/downloader_test.py
  tensorflow_datasets/core/download/extractor.py
  tensorflow_datasets/core/download/extractor_test.py
  tensorflow_datasets/core/download/resource.py
  tensorflow_datasets/core/download/resource_test.py
Labels: cla: no

#171 Add a BeamBuilder to support big dataset generation
  docs/beam_datasets.md
  oss_scripts/oss_pip_install.sh
  setup.py
  tensorflow_datasets/core/__init__.py
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_beam_test.py
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/file_format_adapter.py
  tensorflow_datasets/core/lazy_imports.py
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: no

#333 Add missing url checksums.
  tensorflow_datasets/url_checksums/starcraft_video.txt
Labels: cla: no

#334 do not memoize checksums file reading.
  tensorflow_datasets/core/download/checksums.py
Labels: cla: no

#335 Adds the dSprites data set.
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/dsprites.py
  tensorflow_datasets/image/dsprites_test.py
  tensorflow_datasets/testing/dsprites.py
  tensorflow_datasets/testing/test_data/fake_examples/dsprites/dsprites_ndarray_co1sh3sc6or40x32y32_64x64.hdf5
  tensorflow_datasets/url_checksums/dsprites.txt
Labels: cla: no

#325 Added "%d" format specifier
  tensorflow_datasets/image/cats_vs_dogs.py
Labels: cla: yes

#253 Add script to print num configs
  tensorflow_datasets/scripts/print_num_configs.py
Labels: cla: no

#341 Update MNIST URL to CVDF mirror.
  tensorflow_datasets/image/mnist.py
  tensorflow_datasets/url_checksums/mnist.txt
Labels: cla: no

#287 typo fixes in md and py files
  docs/api_docs/python/tfds/core/SplitBase.md
  docs/api_docs/python/tfds/core/lazy_imports.md
  docs/api_docs/python/tfds/features/FeaturesDict.md
  docs/api_docs/python/tfds/features/Sequence.md
  docs/api_docs/python/tfds/features/Video.md
  docs/api_docs/python/tfds/features/text/Tokenizer.md
  docs/api_docs/python/tfds/file_adapter/TFRecordExampleAdapter.md
  docs/api_docs/python/tfds/testing/DatasetBuilderTestCase.md
  docs/api_docs/python/tfds/testing/FeatureExpectationsTestCase.md
  docs/api_docs/python/tfds/testing/TestCase.md
  tensorflow_datasets/core/features/feature.py
  tensorflow_datasets/core/features/sequence_feature.py
  tensorflow_datasets/core/features/text/text_encoder.py
  tensorflow_datasets/core/file_format_adapter.py
  tensorflow_datasets/core/lazy_imports.py
  tensorflow_datasets/core/splits.py
Labels: cla: yes

#319 Update the download and prepare script for Beam compatibility
  tensorflow_datasets/scripts/download_and_prepare.py
Labels: cla: no

#345 Doc update instruction for new FeatureConnector
  docs/add_dataset.md
Labels: cla: no

#347 Closes #142. No need for it.
  CONTRIBUTING.md
Labels: cla: no

#348 Add send for review step in add_dataset.md
  docs/add_dataset.md
Labels: cla: no

#344 Add missing kernelspecs to tensorflow-dataset notebooks.
  docs/_index.ipynb
  docs/overview.ipynb
Labels: cla: no

#343 Add PASCAL VOC 2007 dataset to Tensorflow Datasets.
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/voc.py
  tensorflow_datasets/image/voc_test.py
  tensorflow_datasets/testing/test_data/fake_examples/voc2007/VOCdevkit/VOC2007/Annotations/000000.xml
  tensorflow_datasets/testing/test_data/fake_examples/voc2007/VOCdevkit/VOC2007/Annotations/000001.xml
  tensorflow_datasets/testing/test_data/fake_examples/voc2007/VOCdevkit/VOC2007/Annotations/000002.xml
  tensorflow_datasets/testing/test_data/fake_examples/voc2007/VOCdevkit/VOC2007/Annotations/000003.xml
  tensorflow_datasets/testing/test_data/fake_examples/voc2007/VOCdevkit/VOC2007/Annotations/000004.xml
  tensorflow_datasets/testing/test_data/fake_examples/voc2007/VOCdevkit/VOC2007/Annotations/000005.xml
  tensorflow_datasets/testing/test_data/fake_examples/voc2007/VOCdevkit/VOC2007/ImageSets/Main/test.txt
  tensorflow_datasets/testing/test_data/fake_examples/voc2007/VOCdevkit/VOC2007/ImageSets/Main/train.txt
  tensorflow_datasets/testing/test_data/fake_examples/voc2007/VOCdevkit/VOC2007/ImageSets/Main/val.txt
  tensorflow_datasets/testing/test_data/fake_examples/voc2007/VOCdevkit/VOC2007/JPEGImages/000000.jpg
  tensorflow_datasets/testing/test_data/fake_examples/voc2007/VOCdevkit/VOC2007/JPEGImages/000001.jpg
  tensorflow_datasets/testing/test_data/fake_examples/voc2007/VOCdevkit/VOC2007/JPEGImages/000002.jpg
  tensorflow_datasets/testing/test_data/fake_examples/voc2007/VOCdevkit/VOC2007/JPEGImages/000003.jpg
  tensorflow_datasets/testing/test_data/fake_examples/voc2007/VOCdevkit/VOC2007/JPEGImages/000004.jpg
  tensorflow_datasets/testing/test_data/fake_examples/voc2007/VOCdevkit/VOC2007/JPEGImages/000005.jpg
  tensorflow_datasets/testing/voc2007.py
  tensorflow_datasets/url_checksums/voc2007.txt
Labels: cla: no

#338 Adds 'shapes3d' data set.
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/shapes3d.py
  tensorflow_datasets/image/shapes3d_test.py
  tensorflow_datasets/testing/shapes3d.py
  tensorflow_datasets/testing/test_data/fake_examples/shapes3d/3dshapes.h5
  tensorflow_datasets/url_checksums/shapes3d.txt
Labels: cla: no

#271 Corrupted Cifar10 dataset.
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/cifar10_corrupted.py
  tensorflow_datasets/image/cifar10_corrupted_test.py
  tensorflow_datasets/testing/test_data/fake_examples/cifar10_corrupted/CIFAR-10-C/elastic_transform.npy
  tensorflow_datasets/testing/test_data/fake_examples/cifar10_corrupted/CIFAR-10-C/labels.npy
  tensorflow_datasets/url_checksums/cifar10_corrupted.txt
Labels: cla: no

#360 updated dataset.md
  docs/datasets.md
Labels: cla: no

#321 Dataset Template Generator Script #320
  tensorflow_datasets/scripts/generate_dataset_template.py
Labels: cla: yes

#346 Add all LSUN categories and update URLs
  tensorflow_datasets/image/lsun.py
  tensorflow_datasets/url_checksums/lsun.txt
Labels: cla: no

#368 Speed and space improvements on extractor.iter_tar.
  tensorflow_datasets/core/download/extractor.py
  tensorflow_datasets/core/download/extractor_test.py
  tensorflow_datasets/core/download/resource.py
Labels: cla: no

#369 Add --module_import to download_and_prepare for non-TFDS datasets
  tensorflow_datasets/scripts/download_and_prepare.py
Labels: cla: no

#380 Update versions of images datasets where encoded string was stripped
  tensorflow_datasets/image/cats_vs_dogs.py
  tensorflow_datasets/image/imagenet.py
  tensorflow_datasets/image/open_images.py
Labels: cla: no

#378 Fixed error in example code for add_dataset script
  docs/add_dataset.md
Labels: cla: yes

#362 Converted quickdraw citation to bibtex format
  tensorflow_datasets/image/quickdraw.py
Labels: cla: yes

#329 Reference added for "as_dataset_kwargs"
  tensorflow_datasets/core/registered.py
Labels: cla: yes, documentation

#290 Add documentation about class names
  README.md
Labels: cla: yes, documentation

#366 Add DTD dataset to Tensorflow Datasets.
  tensorflow_datasets/image/dtd.py
  tensorflow_datasets/image/dtd_key_attributes.txt
  tensorflow_datasets/image/dtd_test.py
  tensorflow_datasets/testing/dtd.py
  tensorflow_datasets/testing/test_data/fake_examples/dtd/dtd/images/chequered/chequered_0000.jpg
  tensorflow_datasets/testing/test_data/fake_examples/dtd/dtd/images/chequered/chequered_0001.jpg
  tensorflow_datasets/testing/test_data/fake_examples/dtd/dtd/images/crosshatched/crosshatched_0001.jpg
  tensorflow_datasets/testing/test_data/fake_examples/dtd/dtd/images/dotted/dotted_0000.jpg
  tensorflow_datasets/testing/test_data/fake_examples/dtd/dtd/images/pleated/pleated_0002.jpg
  tensorflow_datasets/testing/test_data/fake_examples/dtd/dtd/images/polka-dotted/polka-dotted_0002.jpg
  tensorflow_datasets/testing/test_data/fake_examples/dtd/dtd/images/sprinkled/sprinkled_0001.jpg
  tensorflow_datasets/testing/test_data/fake_examples/dtd/dtd/images/striped/striped_0000.jpg
  tensorflow_datasets/testing/test_data/fake_examples/dtd/dtd/images/waffled/waffled_0002.jpg
  tensorflow_datasets/testing/test_data/fake_examples/dtd/dtd/images/woven/woven_0000.jpg
  tensorflow_datasets/testing/test_data/fake_examples/dtd/dtd/images/wrinkled/wrinkled_0000.jpg
  tensorflow_datasets/testing/test_data/fake_examples/dtd/dtd/labels/test1.txt
  tensorflow_datasets/testing/test_data/fake_examples/dtd/dtd/labels/train1.txt
  tensorflow_datasets/testing/test_data/fake_examples/dtd/dtd/labels/val1.txt
  tensorflow_datasets/url_checksums/dtd.txt
Labels: cla: no

#352 ignore dangerous paths in archives, instead of raising. Closes #267.
  tensorflow_datasets/core/download/extractor.py
  tensorflow_datasets/core/download/extractor_test.py
  tensorflow_datasets/testing/test_data/archives/absolute_path.tar
Labels: cla: no

#387 Missing import in image/__init__.py to include DTD dataset.
  tensorflow_datasets/image/__init__.py
Labels: cla: no

#375 BEGIN PUBLIC
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/sun.py
  tensorflow_datasets/image/sun397_labels.txt
  tensorflow_datasets/image/sun_test.py
  tensorflow_datasets/testing/sun397.py
  tensorflow_datasets/testing/test_data/fake_examples/sun397/SUN397.tar.gz
  tensorflow_datasets/url_checksums/sun397.txt
Labels: cla: no

#386 Add code style to docs.
  docs/add_dataset.md
Labels: cla: yes

#382 Fix format render issue
  docs/api_docs/python/tfds/features/ClassLabel.md
Labels: cla: yes

#75 Use hosted datasets if available
  tensorflow_datasets/core/constants.py
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/utils/gcs_utils.py
  tensorflow_datasets/core/utils/gcs_utils_test.py
  tensorflow_datasets/testing/test_case.py
Labels: cla: yes

#384 add Oxford-IIIT Pet dataset with image-level semantic labels only.
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/oxford_iiit_pet.py
  tensorflow_datasets/image/oxford_iiit_pet_test.py
  tensorflow_datasets/testing/oxford_iiit_pet.py
  tensorflow_datasets/testing/test_data/fake_examples/oxford_iiit_pet/annotations/test.txt
  tensorflow_datasets/testing/test_data/fake_examples/oxford_iiit_pet/annotations/trainval.txt
  tensorflow_datasets/testing/test_data/fake_examples/oxford_iiit_pet/images/image000.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_iiit_pet/images/image001.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_iiit_pet/images/image002.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_iiit_pet/images/image003.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_iiit_pet/images/image004.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_iiit_pet/images/image005.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_iiit_pet/images/image006.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_iiit_pet/images/image007.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_iiit_pet/images/image008.jpg
  tensorflow_datasets/testing/test_data/fake_examples/oxford_iiit_pet/images/image009.jpg
Labels: cla: no
