Repository tensorflow/datasets, pull requests merged in 2020-09, with the labels that each got.

#2380 Remove the _set_top_level() attribute.
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/features/top_level_feature.py
  tensorflow_datasets/core/features/top_level_feature_test.py
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no

#2376 Catch error on windows when gs:// isn't present
  tensorflow_datasets/core/utils/gcs_utils.py
Labels: cla: no

#2359 Save/load metadata when FeatureConnector config is saved
  tensorflow_datasets/core/features/class_label_feature.py
  tensorflow_datasets/core/features/feature.py
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no

#2381 Add performance and splits doc
  docs/performances.md
  docs/splits.md
  tensorflow_datasets/core/splits.py
Labels: cla: no

#2344 Remove legacy Py2 code
  oss_scripts/oss_tests.sh
  tensorflow_datasets/core/lazy_imports_lib.py
  tensorflow_datasets/core/lazy_imports_lib_test.py
  tensorflow_datasets/image_classification/imagenet2012_corrupted_test.py
Labels: cla: no

#2374 Better tfds.as_dataframe display for big arrays.
  tensorflow_datasets/core/features/feature.py
Labels: cla: no

#2351 Better open source workflow for contributors
  CONTRIBUTING.md
  README.md
  docs/overview.ipynb
  oss_scripts/oss_pip_install.sh
  setup.py
  tensorflow_datasets/.pylintrc
  tensorflow_datasets/.style.yapf
  tensorflow_datasets/.vscode/settings.json
  tensorflow_datasets/core/folder_dataset/image_folder_test.py
  tensorflow_datasets/core/folder_dataset/translate_folder_test.py
  tensorflow_datasets/core/registered_test.py
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/core/visualization/show_examples_test.py
  tensorflow_datasets/image_classification/cbis_ddsm.py
  tensorflow_datasets/pytest.ini
  tensorflow_datasets/scripts/documentation/document_datasets_test.py
Labels: cla: no

#2358 Remove deprecated tfds.core.disallow_positional_args
  setup.py
  tensorflow_datasets/core/__init__.py
  tensorflow_datasets/core/api_utils.py
  tensorflow_datasets/core/api_utils_test.py
Labels: cla: no

#2353 Expose `builder.url_infos` property to get the download urls from a dataset
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/download/checksums.py
  tensorflow_datasets/core/download/download_manager.py
Labels: cla: no

#2354 Script to detect Dead URLs
  tensorflow_datasets/scripts/cleanup/url_status_checker.py
Labels: cla: yes, tfds:ready_to_merge

#2395 Fix typo in url_status_checker
  tensorflow_datasets/scripts/cleanup/url_status_checker.py
Labels: cla: no

#2405 Fix gfile which does not support Pathlib for TF < 2.3
  tensorflow_datasets/scripts/cleanup/delete_old_versions.py
Labels: cla: no

#2394 Update RegisteredDataset
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/load.py
  tensorflow_datasets/core/registered.py
  tensorflow_datasets/core/registered_test.py
Labels: cla: no

#2377 Fix reraise error message.
  tensorflow_datasets/core/example_serializer.py
  tensorflow_datasets/core/folder_dataset/image_folder.py
  tensorflow_datasets/core/lazy_imports_lib.py
  tensorflow_datasets/core/lazy_imports_lib_test.py
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/core/utils/py_utils_test.py
Labels: cla: no

#2408 Fix tfds.load with multiple registered data_dir
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/load.py
  tensorflow_datasets/core/registered_test.py
Labels: cla: no

#2388 Fix MockFs exists function bug
  tensorflow_datasets/testing/test_utils.py
  tensorflow_datasets/testing/test_utils_test.py
Labels: cla: yes, community:please_review

#2407 Cleanup debug statements
  tensorflow_datasets/core/utils/py_utils.py
Labels: cla: no

#2409 Remove tfds.features.text.Xyz from the public API.
  tensorflow_datasets/core/features/__init__.py
Labels: cla: no

#2412 Fix catalog generation for dataset-as-folder datasets
  tensorflow_datasets/scripts/documentation/document_datasets.py
Labels: cla: no

#2411 Fix typing annotation crash for generate_visualization
  tensorflow_datasets/scripts/documentation/generate_visualization.py
Labels: cla: no

#2415 Remove tfds.features.text.Xyz from the public API.
  tensorflow_datasets/core/features/__init__.py
Labels: cla: no

#2416 Remove tfds.features.text.Xyz from the public API.
  tensorflow_datasets/core/features/__init__.py
Labels: cla: no

#2414 Fix as_numpy_iterator for TF 1.15 compatibility
  tensorflow_datasets/core/read_only_builder_test.py
Labels: cla: no

#2417 Move hidden documentation to https://www.tensorflow.org/datasets/api_docs/python/tfds/features
  tensorflow_datasets/core/features/__init__.py
  tensorflow_datasets/core/features/feature.py
Labels: cla: no

#2430 Fix a typo in the overview docs
  docs/overview.ipynb
Labels: cla: yes

#2432 Fix doc determinism by using dict instead of set
  tensorflow_datasets/scripts/documentation/dataset_markdown_builder.py
Labels: cla: no

#2436 Add conftest.py for pytest
  tensorflow_datasets/conftest.py
Labels: cla: no

#2437 Adjust books to account for changed to the tensorflow_docs api_generator.
  docs/_book.yaml
Labels: cla: no

#2439 Move list_versions to utils and make Version hashable
  tensorflow_datasets/core/utils/version.py
  tensorflow_datasets/core/utils/version_test.py
Labels: cla: no

#2441 Add mock_tf() and fix tf.io.gfile mocks
  tensorflow_datasets/core/download/download_manager_test.py
  tensorflow_datasets/testing/__init__.py
  tensorflow_datasets/testing/test_utils.py
  tensorflow_datasets/testing/test_utils_test.py
Labels: cla: no

#2433 Add core tab support for checksums
  tensorflow_datasets/core/download/checksums.py
Labels: author:kokoro_test_failed, cla: yes

#2442 Remove special case in datasets build_api_docs.
  tensorflow_datasets/scripts/documentation/build_api_docs.py
Labels: cla: no

#2444 Update PlantVillage URL
  tensorflow_datasets/image_classification/plant_village.py
  tensorflow_datasets/url_checksums/plant_village.txt
Labels: author:kokoro_test_failed, cla: yes

#2449 Add "Natural Questions Open" open domain QA dataset.
  tensorflow_datasets/question_answering/__init__.py
  tensorflow_datasets/question_answering/natural_questions_open.py
  tensorflow_datasets/question_answering/natural_questions_open_test.py
  tensorflow_datasets/testing/test_data/fake_examples/natural_questions_open/NQ-open.dev.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/natural_questions_open/NQ-open.train.jsonl
  tensorflow_datasets/url_checksums/natural_questions_open.txt
Labels: cla: no

#2438 update get_filename to match for non-quoted strings
  tensorflow_datasets/core/download/downloader.py
  tensorflow_datasets/core/download/downloader_test.py
Labels: cla: yes, tfds:is_reviewing

#2410 Remove support for TF 1.15
  oss_scripts/oss_tests.sh
  setup.py
  tensorflow_datasets/core/tf_compat.py
Labels: cla: no

#2459 Add `build` cmd in TFDS CLI
  tensorflow_datasets/scripts/cli/build.py
  tensorflow_datasets/scripts/cli/main.py
Labels: cla: yes

#2455 Support reading config for partial versioning
  tensorflow_datasets/core/load.py
  tensorflow_datasets/core/load_test.py
Labels: cla: yes

#2456 Fix tfds version for nightly release
  oss_scripts/oss_release.sh
Labels: cla: no

#2457 Disable compute statistics by default
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/dataset_info_test.py
  tensorflow_datasets/core/download/download_manager.py
Labels: cla: no

#2475 Raise error if input to even_splits is larger than 100
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/core/splits_test.py
Labels: cla: no

#2464 CleanUP
  tensorflow_datasets/image/bccd/bccd.py
  tensorflow_datasets/summarization/aeslc.py
  tensorflow_datasets/text/irc_disentanglement.py
Labels: cla: yes

#2471 Update dtd.py
  tensorflow_datasets/image_classification/dtd.py
Labels: cla: yes

#2469 clean up dataset code
  tensorflow_datasets/image_classification/oxford_flowers102.py
Labels: cla: yes

#2470 clean up dataset code for other datasets
  tensorflow_datasets/audio/spoken_digit/spoken_digit.py
  tensorflow_datasets/image_classification/oxford_iiit_pet.py
Labels: cla: yes

#2472 Cleanup code for Tedlium and cbis_ddsm
  tensorflow_datasets/audio/tedlium.py
  tensorflow_datasets/image_classification/cbis_ddsm.py
Labels: cla: yes

#2480 Fix error message format
  tensorflow_datasets/core/load.py
Labels: cla: no

#2481 Add `as_supervised` support for `tfds.as_dataframe`
  tensorflow_datasets/core/as_dataframe.py
  tensorflow_datasets/core/as_dataframe_test.py
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/visualization/show_examples.py
Labels: cla: no

#2473 Clean up code for Arc and Deep weeds datasets
  tensorflow_datasets/image/arc.py
  tensorflow_datasets/image_classification/deep_weeds.py
Labels: cla: yes

#2486 Cleanup IN_DEVELOPMENT property.
  tensorflow_datasets/core/load.py
  tensorflow_datasets/core/registered.py
  tensorflow_datasets/core/registered_test.py
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: no

#2483 Switch to standalone tifffile in tensorflow_datasets.
  setup.py
  tensorflow_datasets/core/lazy_imports_lib.py
  tensorflow_datasets/core/lazy_imports_lib_test.py
  tensorflow_datasets/image_classification/eurosat.py
Labels: cla: no

#2477 Update imagenet_v2 dataset
  tensorflow_datasets/image_classification/imagenet_v2.py
  tensorflow_datasets/image_classification/imagenet_v2_test.py
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency-format-val/125/3.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency-format-val/125/4.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency-format-val/125/5.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency-format-val/42/1.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency-format-val/42/2.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency-format-val/999/10.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency-format-val/999/6.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency-format-val/999/7.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency-format-val/999/8.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency-format-val/999/9.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold-0.7-format-val/125/3.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold-0.7-format-val/125/4.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold-0.7-format-val/125/5.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold-0.7-format-val/42/1.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold-0.7-format-val/42/2.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold-0.7-format-val/999/10.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold-0.7-format-val/999/6.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold-0.7-format-val/999/7.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold-0.7-format-val/999/8.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold-0.7-format-val/999/9.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-top-images-format-val/125/3.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-top-images-format-val/125/4.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-top-images-format-val/125/5.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-top-images-format-val/42/1.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-top-images-format-val/42/2.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-top-images-format-val/999/10.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-top-images-format-val/999/6.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-top-images-format-val/999/7.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-top-images-format-val/999/8.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-top-images-format-val/999/9.jpeg
  tensorflow_datasets/url_checksums/imagenet_v2.txt
Labels: cla: yes

#2485 Update tfds.find_builder_from_dir to support multiple data_dir
  tensorflow_datasets/core/constants.py
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/load.py
  tensorflow_datasets/core/load_test.py
Labels: cla: no

#2489 Fix nightly `__version__` to be PEP440 compliant
  setup.py
  tensorflow_datasets/version.py
Labels: cla: no

#2490 Fix or ignore some pytype errors.
  tensorflow_datasets/core/as_dataframe.py
Labels: cla: no

#2492 Fix PyPI nightly name
  setup.py
Labels: cla: no

#2323 Adding landing page calling for partners with external companies.
  docs/_book.yaml
  docs/community.md
Labels: cla: no
