Repository tensorflow/datasets, pull requests merged in 2020-10, with the labels that each got.

#2504 Adding release note field to DatasetBuilder and BuilderConfig
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/scripts/cli/new.py
Labels: cla: no

#2506 Add deprecation message when using `create_new_dataset`
  tensorflow_datasets/scripts/create_new_dataset.py
Labels: cla: no

#2493 Update `tfds.load` to load datasets from files without using original class.
  tensorflow_datasets/core/__init__.py
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/features/feature.py
  tensorflow_datasets/core/load.py
  tensorflow_datasets/core/read_only_builder.py
  tensorflow_datasets/core/read_only_builder_test.py
  tensorflow_datasets/core/registered_test.py
Labels: cla: no

#2509 Update release notes - 1
  tensorflow_datasets/audio/groove.py
  tensorflow_datasets/audio/vctk.py
  tensorflow_datasets/image/abstract_reasoning.py
  tensorflow_datasets/image/binarized_mnist.py
  tensorflow_datasets/image_classification/imagenet.py
Labels: cla: yes, tfds:ready_to_merge

#2507 Fix/2503 allow images with 4 channels
  tensorflow_datasets/core/features/image_feature.py
  tensorflow_datasets/core/features/image_feature_test.py
Labels: author:kokoro_test_failed, cla: yes

#2514 F or release notes 1
  tensorflow_datasets/video/bair_robot_pushing.py
  tensorflow_datasets/video/ucf101.py
Labels: cla: yes, tfds:ready_to_merge

#2515 Update deprecated argument for map_fn
  tensorflow_datasets/core/features/feature.py
Labels: cla: no

#2518 Split test_utils into feature_test_cases.py
  tensorflow_datasets/testing/__init__.py
  tensorflow_datasets/testing/dataset_builder_testing.py
  tensorflow_datasets/testing/feature_test_case.py
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no

#2520 Add setup_teardown.py to share setup between pytest/unittest
  tensorflow_datasets/conftest.py
  tensorflow_datasets/testing/setup_teardown.py
  tensorflow_datasets/testing/test_case.py
Labels: cla: no

#2530 Fix comment in ANLI dataset.
  tensorflow_datasets/text/anli.py
Labels: cla: no

#2519 Additional mock gfile API fixes
  tensorflow_datasets/core/constants.py
  tensorflow_datasets/testing/test_utils.py
  tensorflow_datasets/testing/test_utils_test.py
Labels: cla: no

#2445 Update DatasetBuilder to use version.list_all_versions
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#2512 Update release notes - 4
  tensorflow_datasets/image_classification/cbis_ddsm.py
  tensorflow_datasets/image_classification/cifar10_corrupted.py
  tensorflow_datasets/image_classification/colorectal_histology.py
  tensorflow_datasets/image_classification/cycle_gan.py
  tensorflow_datasets/image_classification/deep_weeds.py
Labels: cla: yes, community:please_review

#2525 Update release notes - 8
  tensorflow_datasets/image_classification/rock_paper_scissors.py
  tensorflow_datasets/image_classification/smallnorb.py
  tensorflow_datasets/image_classification/so2sat.py
  tensorflow_datasets/image_classification/svhn.py
  tensorflow_datasets/image_classification/uc_merced.py
Labels: cla: yes, community:please_review

#2533 Update release notes - 12
  tensorflow_datasets/audio/nsynth.py
  tensorflow_datasets/image_classification/omniglot.py
  tensorflow_datasets/object_detection/open_images.py
  tensorflow_datasets/video/moving_mnist.py
Labels: cla: yes, tfds:ready_to_merge

#2526 Update release notes - 9
  tensorflow_datasets/object_detection/kitti.py
  tensorflow_datasets/structured/higgs.py
  tensorflow_datasets/structured/iris.py
  tensorflow_datasets/structured/titanic.py
  tensorflow_datasets/summarization/big_patent.py
Labels: cla: yes, community:please_review

#2527 Update release notes - 10
  tensorflow_datasets/summarization/cnn_dailymail.py
  tensorflow_datasets/summarization/xsum.py
  tensorflow_datasets/text/c4.py
  tensorflow_datasets/text/glue.py
  tensorflow_datasets/text/imdb.py
Labels: cla: yes, community:please_review

#2510 Update release notes - 2
  tensorflow_datasets/image/celeba.py
  tensorflow_datasets/image/celebahq.py
  tensorflow_datasets/image/clevr.py
  tensorflow_datasets/image/downsampled_imagenet.py
  tensorflow_datasets/image/dsprites.py
Labels: cla: yes, tfds:ready_to_merge

#2528 Update release notes - 11
  tensorflow_datasets/text/lm1b.py
  tensorflow_datasets/text/multi_nli.py
  tensorflow_datasets/text/wikipedia.py
  tensorflow_datasets/text/wikipedia_toxicity_subtypes.py
  tensorflow_datasets/translate/ted_hrlr.py
  tensorflow_datasets/video/starcraft.py
Labels: cla: yes, tfds:is_reviewing

#2523 Update release notes - 6
  tensorflow_datasets/image_classification/diabetic_retinopathy_detection.py
  tensorflow_datasets/image_classification/horses_or_humans.py
  tensorflow_datasets/image_classification/imagenet2012_corrupted.py
  tensorflow_datasets/image_classification/imagenet2012_real.py
  tensorflow_datasets/image_classification/imagenet2012_subset.py
Labels: cla: yes, tfds:is_reviewing

#2536 Improve debug message for audio file encoding (Fix #2513)
  tensorflow_datasets/core/features/audio_feature.py
Labels: cla: no

#2542 Update TFDS version to 4.0.0
  tensorflow_datasets/stable_versions.txt
  tensorflow_datasets/version.py
  tensorflow_datasets/version_stable.py
Labels: cla: no

#2543 Add Hellaswag dataset to TFDS.
  tensorflow_datasets/testing/test_data/fake_examples/hellaswag/hellaswag_test.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/hellaswag/hellaswag_train.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/hellaswag/hellaswag_val.jsonl
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/hellaswag.py
  tensorflow_datasets/text/hellaswag_test.py
  tensorflow_datasets/url_checksums/hellaswag.txt
Labels: cla: no

#2550 Add TFDS core values
  README.md
Labels: cla: no

#2555 Fix GCS access error when permission denied.
  tensorflow_datasets/core/utils/gcs_utils.py
Labels: cla: no

#2551 Fix GCS support for looking up existing versions
  tensorflow_datasets/core/utils/version.py
Labels: cla: yes, tfds:ready_to_merge

#2544 add config_description to the dataset_info.proto
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/proto/dataset_info.proto
  tensorflow_datasets/core/proto/dataset_info_generated_pb2.py
Labels: cla: yes, tfds:ready_to_merge

#2558 Update TF to 4.0.1
  tensorflow_datasets/stable_versions.txt
  tensorflow_datasets/version.py
  tensorflow_datasets/version_stable.py
Labels: cla: no

#2557 Remove disable_progress_bar from notebook
  docs/keras_example.ipynb
Labels: cla: no

#2563 Fix cityscape formatting
  tensorflow_datasets/image/cityscapes.py
Labels: cla: no

#2560 Update __init__.py
  tensorflow_datasets/proto/__init__.py
Labels: cla: yes, tfds:ready_to_merge

#2559 Minor spelling corrections for en-US
  docs/beam_datasets.md
  setup.py
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/download/downloader.py
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/utils/gcs_utils.py
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/scripts/cli/new.py
Labels: cla: yes, tfds:ready_to_merge

#2567 Allow to pass verify_ssl=False to DownloadConfig.
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/download_manager_test.py
  tensorflow_datasets/core/download/downloader.py
Labels: cla: no

#2484 Solve #2286. Download imagenet train/val splits alone
  tensorflow_datasets/image_classification/imagenet.py
Labels: cla: yes, tfds:ready_to_merge

#2570 Fix missing formatting arg in exception message.
  tensorflow_datasets/core/download/download_manager.py
Labels: cla: no

#2569 Design adjustment and Typo
  tensorflow_datasets/__init__.py
Labels: cla: yes, tfds:ready_to_merge

#2583 Add feedback section in the dataset creation workflow.
  docs/add_dataset.md
Labels: cla: no

#2575 Add pathlib protocol to type_utils, Fix 2562
  setup.py
  tensorflow_datasets/core/utils/type_utils.py
Labels: cla: no

#2576 Better resources compatibility
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/scripts/cleanup/refactor_dataset_as_folder.py
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: no

#2580 Add LAMBADA dataset
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/lambada/__init__.py
  tensorflow_datasets/text/lambada/checksums.tsv
  tensorflow_datasets/text/lambada/dummy_data/lambada_development_plain_text.txt
  tensorflow_datasets/text/lambada/dummy_data/lambada_test_plain_text.txt
  tensorflow_datasets/text/lambada/lambada.py
  tensorflow_datasets/text/lambada/lambada_test.py
Labels: cla: no, dataset request

#2581 Add story cloze dataset
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/story_cloze/__init__.py
  tensorflow_datasets/text/story_cloze/dummy_data/cloze_test_test__winter2018.csv
  tensorflow_datasets/text/story_cloze/dummy_data/cloze_test_val__winter2018.csv
  tensorflow_datasets/text/story_cloze/story_cloze.py
  tensorflow_datasets/text/story_cloze/story_cloze_test.py
Labels: cla: no, dataset request

#2565 Open source multilingual C4 (mC4).
  setup.py
  tensorflow_datasets/core/lazy_imports_lib.py
  tensorflow_datasets/core/lazy_imports_lib_test.py
  tensorflow_datasets/testing/test_data/fake_examples/c4/cc_0.warc.wet
  tensorflow_datasets/testing/test_data/fake_examples/c4/cc_0.warc.wet.gz
  tensorflow_datasets/testing/test_data/fake_examples/c4/cc_1.warc.wet
  tensorflow_datasets/testing/test_data/fake_examples/c4/cc_1.warc.wet.gz
  tensorflow_datasets/text/c4.py
  tensorflow_datasets/text/c4_test.py
  tensorflow_datasets/text/c4_utils.py
  tensorflow_datasets/text/c4_utils_test.py
  tensorflow_datasets/url_checksums/c4.txt
Labels: cla: no, dataset request

#2587 Fix resource paths issues in zip file.
  tensorflow_datasets/core/utils/__init__.py
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/core/utils/resource_utils.py
  tensorflow_datasets/core/utils/resource_utils_test.py
Labels: cla: no

#2566 DOC Fix indentation and displayed list numbers
  tensorflow_datasets/core/load.py
Labels: cla: yes, tfds:ready_to_merge

#2585 Add Pathlib compatibility to FeatureConnectors
  tensorflow_datasets/core/features/audio_feature.py
  tensorflow_datasets/core/features/audio_feature_test.py
  tensorflow_datasets/core/features/class_label_feature.py
  tensorflow_datasets/core/features/class_label_feature_test.py
  tensorflow_datasets/core/features/image_feature.py
  tensorflow_datasets/core/features/image_feature_test.py
  tensorflow_datasets/core/features/video_feature.py
  tensorflow_datasets/core/features/video_feature_test.py
  tensorflow_datasets/core/utils/type_utils.py
Labels: cla: no

#2572 Add feature.md to doc
  docs/_book.yaml
  docs/features.md
  tensorflow_datasets/core/features/__init__.py
Labels: cla: no

#2577 Make `tfds_path` return pathlib-like objects
  tensorflow_datasets/core/__init__.py
  tensorflow_datasets/core/decode/base_test.py
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/core/utils/type_utils.py
  tensorflow_datasets/image_classification/caltech.py
  tensorflow_datasets/image_classification/cbis_ddsm.py
  tensorflow_datasets/image_classification/dtd.py
  tensorflow_datasets/image_classification/food101.py
  tensorflow_datasets/image_classification/geirhos_conflict_stimuli.py
  tensorflow_datasets/image_classification/imagenet.py
  tensorflow_datasets/image_classification/imagenet2012_corrupted.py
  tensorflow_datasets/image_classification/imagenet2012_real.py
  tensorflow_datasets/image_classification/imagenet2012_subset.py
  tensorflow_datasets/image_classification/imagenet_a.py
  tensorflow_datasets/image_classification/imagenet_r.py
  tensorflow_datasets/image_classification/imagenet_resized.py
  tensorflow_datasets/image_classification/imagenet_v2.py
  tensorflow_datasets/image_classification/imagenette.py
  tensorflow_datasets/image_classification/imagewang.py
  tensorflow_datasets/image_classification/inaturalist.py
  tensorflow_datasets/image_classification/places365_small.py
  tensorflow_datasets/image_classification/plant_leaves.py
  tensorflow_datasets/image_classification/plantae_k.py
  tensorflow_datasets/image_classification/quickdraw.py
  tensorflow_datasets/image_classification/sun.py
  tensorflow_datasets/image_classification/vgg_face2.py
  tensorflow_datasets/object_detection/open_images.py
  tensorflow_datasets/scripts/documentation/document_datasets.py
  tensorflow_datasets/testing/dataset_builder_testing.py
  tensorflow_datasets/testing/fake_data_generation/caltech.py
  tensorflow_datasets/testing/fake_data_generation/curated_breast_imaging_ddsm.py
  tensorflow_datasets/testing/fake_data_generation/dtd.py
  tensorflow_datasets/testing/fake_data_generation/imagenet.py
  tensorflow_datasets/testing/fake_data_generation/open_images.py
  tensorflow_datasets/testing/fake_data_generation/smallnorb.py
  tensorflow_datasets/testing/fake_data_generation/sun397.py
  tensorflow_datasets/video/ucf101.py
Labels: cla: no

#2595 Fix importlib resources
  tensorflow_datasets/core/utils/resource_utils.py
Labels: cla: no

#2589 Cleanup resource usage for bigpatent
  tensorflow_datasets/summarization/big_patent.py
Labels: cla: no

#2596 Fix infinite recursion in _Path wrapper
  tensorflow_datasets/core/utils/resource_utils.py
  tensorflow_datasets/core/utils/resource_utils_test.py
Labels: cla: no

#2573 Add deprecated warning for add_checksums_dir
  tensorflow_datasets/core/deprecated/__init__.py
  tensorflow_datasets/core/download/checksums.py
Labels: cla: no

#2590 Rename tfds_dir -> tfds_write_path
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/dataset_info_test.py
  tensorflow_datasets/core/deprecated/text/subword_text_encoder_test.py
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/core/utils/py_utils_test.py
  tensorflow_datasets/core/utils/resource_utils.py
  tensorflow_datasets/core/utils/resource_utils_test.py
  tensorflow_datasets/scripts/cleanup/convert_nlp.py
  tensorflow_datasets/scripts/cleanup/metadata_cleanup.py
  tensorflow_datasets/scripts/cleanup/refactor_dataset_as_folder.py
  tensorflow_datasets/scripts/create_new_dataset.py
  tensorflow_datasets/scripts/documentation/build_catalog.py
  tensorflow_datasets/scripts/freeze_dataset_versions.py
Labels: cla: no

#2554 Add cleaned E2E dataset
  tensorflow_datasets/structured/__init__.py
  tensorflow_datasets/structured/e2e_cleaned.py
  tensorflow_datasets/structured/e2e_cleaned_test.py
  tensorflow_datasets/testing/test_data/fake_examples/e2e_cleaned/dev.csv
  tensorflow_datasets/testing/test_data/fake_examples/e2e_cleaned/test.csv
  tensorflow_datasets/testing/test_data/fake_examples/e2e_cleaned/train.csv
  tensorflow_datasets/url_checksums/e2e_cleaned.txt
Labels: cla: no, dataset request

#2599 Fix url bug in docs
  docs/overview.ipynb
Labels: cla: yes, tfds:ready_to_merge

#2607 Update checksums to uses resource path
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/download/checksums.py
  tensorflow_datasets/core/download/checksums_test.py
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/download_manager_test.py
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: no

#2606 Rename `import_testing_test` -> `import_public_api_test`
  tensorflow_datasets/import_public_api_test.py
  tensorflow_datasets/import_test.py
Labels: cla: no

#2610 Fix `zipfile.Path.joinpath` to be consistent with `pathlib.Path.joinpath`
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/utils/resource_utils.py
  tensorflow_datasets/core/utils/resource_utils_test.py
Labels: cla: no

#2603 Switch voxforge to a beam builder.
  tensorflow_datasets/audio/voxforge.py
  tensorflow_datasets/core/lazy_imports_lib.py
  tensorflow_datasets/testing/test_data/fake_examples/voxforge/www.repository.voxforge1.org/downloads/es/Trunk/Audio/Main/16kHz_16bit/speaker1-10-1.tgz
  tensorflow_datasets/testing/test_data/fake_examples/voxforge/www.repository.voxforge1.org/downloads/es/Trunk/Audio/Main/16kHz_16bit/speaker2-20-1.tgz
  tensorflow_datasets/testing/test_data/fake_examples/voxforge/www.repository.voxforge1.org/downloads/ru/Trunk/Audio/Main/16kHz_16bit/speaker3-30-1.tgz
  tensorflow_datasets/testing/test_data/fake_examples/voxforge/www.repository.voxforge1.org/downloads/ru/Trunk/Audio/Main/16kHz_16bit/speaker4-40-1.tgz
Labels: cla: no

#2609 Fix issue when dataset is detected twice
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#2602 Minor fix missing comma in docstring
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/load.py
Labels: cla: yes, community:please_review

#2615 Rename tfds.download.add_checksums_dir -> tfds.deprecated.add_checksums_dir
  tensorflow_datasets/scripts/download_and_prepare.py
Labels: cla: no

#2614 Add generic `tfds.core.make_path` util.
  tensorflow_datasets/core/__init__.py
  tensorflow_datasets/core/download/checksums.py
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/download_manager_test.py
  tensorflow_datasets/core/utils/__init__.py
  tensorflow_datasets/core/utils/generic_path.py
  tensorflow_datasets/core/utils/resource_utils.py
  tensorflow_datasets/core/utils/type_utils.py
  tensorflow_datasets/scripts/cleanup/metadata_cleanup.py
  tensorflow_datasets/scripts/cleanup/refactor_dataset_as_folder.py
  tensorflow_datasets/scripts/freeze_dataset_versions.py
Labels: cla: no

#2605 Minor fix in documentation
  tensorflow_datasets/image_classification/cats_vs_dogs.py
Labels: cla: yes, community:please_review

#2621 Minor comment clarification for `add_dataset`
  docs/add_dataset.md
Labels: cla: no

#2553 Add Wiki BIO dataset
  tensorflow_datasets/structured/__init__.py
  tensorflow_datasets/structured/wiki_bio.py
  tensorflow_datasets/structured/wiki_bio_test.py
  tensorflow_datasets/testing/test_data/fake_examples/wiki_bio/wikipedia-biography-dataset/test/test.box
  tensorflow_datasets/testing/test_data/fake_examples/wiki_bio/wikipedia-biography-dataset/test/test.id
  tensorflow_datasets/testing/test_data/fake_examples/wiki_bio/wikipedia-biography-dataset/test/test.nb
  tensorflow_datasets/testing/test_data/fake_examples/wiki_bio/wikipedia-biography-dataset/test/test.sent
  tensorflow_datasets/testing/test_data/fake_examples/wiki_bio/wikipedia-biography-dataset/test/test.title
  tensorflow_datasets/testing/test_data/fake_examples/wiki_bio/wikipedia-biography-dataset/train/train.box
  tensorflow_datasets/testing/test_data/fake_examples/wiki_bio/wikipedia-biography-dataset/train/train.id
  tensorflow_datasets/testing/test_data/fake_examples/wiki_bio/wikipedia-biography-dataset/train/train.nb
  tensorflow_datasets/testing/test_data/fake_examples/wiki_bio/wikipedia-biography-dataset/train/train.sent
  tensorflow_datasets/testing/test_data/fake_examples/wiki_bio/wikipedia-biography-dataset/train/train.title
  tensorflow_datasets/testing/test_data/fake_examples/wiki_bio/wikipedia-biography-dataset/valid/valid.box
  tensorflow_datasets/testing/test_data/fake_examples/wiki_bio/wikipedia-biography-dataset/valid/valid.id
  tensorflow_datasets/testing/test_data/fake_examples/wiki_bio/wikipedia-biography-dataset/valid/valid.nb
  tensorflow_datasets/testing/test_data/fake_examples/wiki_bio/wikipedia-biography-dataset/valid/valid.sent
  tensorflow_datasets/testing/test_data/fake_examples/wiki_bio/wikipedia-biography-dataset/valid/valid.title
  tensorflow_datasets/url_checksums/wiki_bio.txt
Labels: cla: no, dataset request

#2622 Clarify dataset_info.json not found error.
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/dataset_info_test.py
Labels: cla: no

#2620 Fix typing annotation for GPath.
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/utils/gpath.py
  tensorflow_datasets/core/utils/gpath_test.py
Labels: cla: no

#2626 Make Path on windows uses UTF-8 by default
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/download/checksums.py
  tensorflow_datasets/core/utils/__init__.py
  tensorflow_datasets/core/utils/generic_path.py
  tensorflow_datasets/core/utils/generic_path_test.py
  tensorflow_datasets/core/utils/gpath.py
  tensorflow_datasets/core/utils/gpath_test.py
  tensorflow_datasets/core/utils/resource_utils.py
  tensorflow_datasets/core/utils/resource_utils_test.py
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no

#2627 Minor typing annotation/pathlib update for read_path_json
  tensorflow_datasets/core/dataset_info.py
Labels: cla: no

#2635 Change phrasing of doc
  docs/contribute.md
Labels: cla: no

#2632 Update mC4 to remove languages with under 10k pages
  tensorflow_datasets/text/c4.py
Labels: cla: no

#2631 Add a `utils.docs`
  tensorflow_datasets/core/utils/__init__.py
  tensorflow_datasets/core/utils/docs.py
  tensorflow_datasets/core/utils/type_utils.py
Labels: cla: no

#2638 [C4] Only access the manual_dir when required to avoid throwing an error unnecessarily. Update the instructions to cover all configs.
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/text/c4.py
Labels: cla: no

#2630 Add doc decorators
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/public_api.py
Labels: cla: no

#2639 Internal
  tensorflow_datasets/image/cityscapes_test.py
Labels: cla: no

#2640 Fix manual instruction `dedent` for doc
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/scripts/documentation/dataset_markdown_builder.py
  tensorflow_datasets/text/c4.py
Labels: cla: no

#2633 Change splitlines() to split("\n") to avoid AssertionErrors caused by…
  tensorflow_datasets/translate/wmt.py
Labels: cla: yes

#2612 Add translate-train TyDi QA split to TFDS. Translations used are from the XTREME benchmark.
  tensorflow_datasets/question_answering/tydi_qa.py
  tensorflow_datasets/question_answering/tydi_qa_test.py
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/tydiqa.translate.train.en-ar.json
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/tydiqa.translate.train.en-bn.json
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/tydiqa.translate.train.en-fi.json
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/tydiqa.translate.train.en-id.json
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/tydiqa.translate.train.en-ko.json
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/tydiqa.translate.train.en-ru.json
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/tydiqa.translate.train.en-sw.json
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/tydiqa.translate.train.en-te.json
  tensorflow_datasets/url_checksums/tydi_qa.txt
Labels: cla: no

#2642 Updated URLS for deep_weeds
  tensorflow_datasets/image_classification/deep_weeds.py
  tensorflow_datasets/url_checksums/deep_weeds.txt
Labels: cla: yes, tfds:ready_to_merge

#2654 Minor to_write_path cleanup
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/dataset_info_test.py
  tensorflow_datasets/core/deprecated/text/subword_text_encoder_test.py
  tensorflow_datasets/core/utils/resource_utils.py
  tensorflow_datasets/core/utils/resource_utils_test.py
  tensorflow_datasets/testing/fake_data_generation/smallnorb.py
Labels: cla: no

#2646 Add Physical Interaction QA dataset.
  tensorflow_datasets/testing/test_data/fake_examples/piqa/physicaliqa-train-dev/dev-labels.lst
  tensorflow_datasets/testing/test_data/fake_examples/piqa/physicaliqa-train-dev/dev.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/piqa/physicaliqa-train-dev/train-labels.lst
  tensorflow_datasets/testing/test_data/fake_examples/piqa/physicaliqa-train-dev/train.jsonl
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/piqa.py
  tensorflow_datasets/text/piqa_test.py
  tensorflow_datasets/url_checksums/piqa.txt
Labels: cla: no

#2532 Accept bytes, instead of file object for tfds.features.Images.
  tensorflow_datasets/core/features/image_feature.py
  tensorflow_datasets/core/features/image_feature_test.py
  tensorflow_datasets/object_detection/waymo_open_dataset.py
Labels: cla: yes, tfds:ready_to_merge

#2657 Update imagenet_v2 checksums
  tensorflow_datasets/image_classification/imagenet_v2.py
  tensorflow_datasets/url_checksums/imagenet_v2.txt
Labels: cla: no

#2658 Minor doc fixes
  docs/add_dataset.md
Labels: cla: no

#2660 Internal
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/utils/py_utils.py
Labels: cla: no

#2650 Unify `tfds.core.GeneratorBasedBuilder` and `tfds.core.BeamBasedBuilder`.
  tensorflow_datasets/audio/voxforge.py
  tensorflow_datasets/core/__init__.py
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_beam_test.py
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/split_builder.py
  tensorflow_datasets/core/split_builder_test.py
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/core/tfrecords_writer.py
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no

#2653 Update docs for new Split generator API
  docs/add_dataset.md
  docs/beam_datasets.md
Labels: cla: no

#2663 Remove create_new_dataset.py in favour of `tfds new`
  tensorflow_datasets/scripts/create_new_dataset.py
Labels: cla: yes

#2664 Fix beam with config support Fix #2348
  tensorflow_datasets/scripts/download_and_prepare.py
Labels: cla: no

#2668 Make dl_manager.manual_dir returns a Path-like object.
  tensorflow_datasets/core/download/download_manager.py
Labels: cla: no

#2665 Do not query urls if filename already exists and add more filenames
  tensorflow_datasets/scripts/cleanup/url_filename_recorder.py
  tensorflow_datasets/url_checksums/celeb_a.txt
  tensorflow_datasets/url_checksums/librispeech.txt
  tensorflow_datasets/url_checksums/librispeech_lm.txt
  tensorflow_datasets/url_checksums/libritts.txt
  tensorflow_datasets/url_checksums/plant_leaves.txt
Labels: cla: no

#2669 Add PathLike compatibility to MockFs
  tensorflow_datasets/testing/test_utils.py
  tensorflow_datasets/testing/test_utils_test.py
Labels: cla: no
