Repository tensorflow/datasets, pull requests merged in 2020-03, with the labels that each got.

#1497 fix typo and missing link
  docs/performances.md
Labels: cla: yes, community:please_review

#1543 Attempt to fix Py3 release
  docs/overview.ipynb
  oss_scripts/oss_pip_install.sh
Labels: cla: no

#1518 Cleanup legacy split API for Groove dataset
  tensorflow_datasets/audio/groove.py
  tensorflow_datasets/audio/groove_test.py
Labels: cla: no

#1511 Dedupe lines within a page in C4.
  tensorflow_datasets/text/c4.py
  tensorflow_datasets/text/c4_utils.py
  tensorflow_datasets/text/c4_utils_test.py
Labels: cla: no

#1559 Update mnist, cifar version to deploy auto-caching
  tensorflow_datasets/core/utils/version.py
  tensorflow_datasets/image/cats_vs_dogs.py
  tensorflow_datasets/image/cifar.py
  tensorflow_datasets/image/mnist.py
Labels: cla: no

#1572 Internal change.
  tensorflow_datasets/image/so2sat.py
Labels: cla: no

#1582 Fixing citation for CFQ.
  tensorflow_datasets/text/cfq.py
Labels: cla: no

#1568 Update Typo
  tensorflow_datasets/image/cbis_ddsm.py
Labels: cla: yes, tfds:ready_to_merge

#1574 Deploy auto-caching to Mnist/Cifar
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/dataset_info_test.py
  tensorflow_datasets/image/cifar.py
  tensorflow_datasets/image/mnist.py
  tensorflow_datasets/testing/test_data/dataset_info/mnist/3.0.1/dataset_info.json
  tensorflow_datasets/testing/test_data/dataset_info/mnist/3.0.1/image.image.json
  tensorflow_datasets/testing/test_data/dataset_info/mnist_unlabeled/3.0.1/dataset_info.json
  tensorflow_datasets/testing/test_data/dataset_info/mnist_unlabeled/3.0.1/image.image.json
Labels: cla: no

#1589 Fix info.splits['train'].num_shards
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/core/splits_test.py
Labels: cla: no

#1594 Update Broken links
  docs/add_dataset.md
Labels: cla: yes, tfds:ready_to_merge

#1588 Adding full robonet and 128x128.
  tensorflow_datasets/url_checksums/robonet.txt
  tensorflow_datasets/video/robonet.py
Labels: cla: no

#1595 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/cfq.md
  docs/catalog/cifar10.md
  docs/catalog/cifar100.md
  docs/catalog/curated_breast_imaging_ddsm.md
  docs/catalog/fashion_mnist.md
  docs/catalog/kmnist.md
  docs/catalog/mnist.md
  docs/catalog/overview.md
  docs/catalog/robonet.md
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/robonet/robonet_64/3.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/robonet/robonet_64/3.0.0/video.image.json
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#1596 Minor doc template fix (better as_supervised link)
  tensorflow_datasets/scripts/templates/dataset.mako.md
Labels: cla: no

#1597 Add keras example to doc and doc updates
  README.md
  docs/_book.yaml
  docs/_index.ipynb
  docs/_index.yaml
  docs/keras_example.ipynb
  docs/overview.ipynb
Labels: cla: no

#1536 fix typo
  tensorflow_datasets/text/c4_utils.py
  tensorflow_datasets/text/c4_utils_test.py
Labels: cla: no

#1602 Update README.md
  README.md
Labels: cla: yes, tfds:please_review

#1608 Add Fake data utility for audio files
  tensorflow_datasets/testing/fake_data_utils.py
Labels: cla: yes, tfds:ready_to_merge

#1613 Switch Dataset to tf.compat.v2
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/dataset_utils.py
  tensorflow_datasets/core/file_format_adapter_test.py
  tensorflow_datasets/core/tfrecords_reader.py
Labels: cla: no

#1612 Switch tf.data to compat.v2 by default.
  CONTRIBUTING.md
  docs/add_dataset.md
  tensorflow_datasets/core/dataset_builder_beam_test.py
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/dataset_info_test.py
  tensorflow_datasets/core/dataset_utils_test.py
  tensorflow_datasets/core/decode/base_test.py
  tensorflow_datasets/core/features/audio_feature_test.py
  tensorflow_datasets/core/features/bounding_boxes_test.py
  tensorflow_datasets/core/features/class_label_feature_test.py
  tensorflow_datasets/core/features/features_test.py
  tensorflow_datasets/core/features/image_feature_test.py
  tensorflow_datasets/core/features/sequence_feature_test.py
  tensorflow_datasets/core/features/text_feature_test.py
  tensorflow_datasets/core/features/translation_feature_test.py
  tensorflow_datasets/core/features/video_feature_test.py
  tensorflow_datasets/core/file_format_adapter.py
  tensorflow_datasets/core/file_format_adapter_test.py
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/tfrecords_reader_test.py
  tensorflow_datasets/core/utils/tf_utils_test.py
  tensorflow_datasets/image/vgg_face2.py
  tensorflow_datasets/scripts/download_and_prepare.py
  tensorflow_datasets/summarization/opinosis.py
  tensorflow_datasets/testing/dataset_builder_testing.py
  tensorflow_datasets/testing/div2k.py
  tensorflow_datasets/testing/e2e_binary.py
  tensorflow_datasets/testing/flic.py
  tensorflow_datasets/testing/mocking_test.py
  tensorflow_datasets/testing/test_utils.py
  tensorflow_datasets/testing/test_utils_test.py
  tensorflow_datasets/text/cfq.py
  tensorflow_datasets/text/eraser_multi_rc.py
  tensorflow_datasets/text/math_dataset.py
  tensorflow_datasets/text/movie_rationales.py
  tensorflow_datasets/text/scan.py
  tensorflow_datasets/video/moving_sequence.py
  tensorflow_datasets/video/moving_sequence_test.py
Labels: cla: no

#1617 Internal
  tensorflow_datasets/import_testing_test.py
  tensorflow_datasets/public_api.py
Labels: cla: no

#1622 Rollback Dataset to tf.compat.v2
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/dataset_utils.py
  tensorflow_datasets/core/file_format_adapter_test.py
  tensorflow_datasets/core/tfrecords_reader.py
Labels: cla: no

#1615 Add Geirhos conflict stimuli dataset.
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/geirhos_conflict_stimuli.py
  tensorflow_datasets/image/geirhos_conflict_stimuli_test.py
  tensorflow_datasets/testing/test_data/fake_examples/geirhos_conflict_stimuli/mapping.txt
  tensorflow_datasets/testing/test_data/fake_examples/geirhos_conflict_stimuli/texture_vs_shape/texture-vs-shape-1b69c6a445c3348927139edb30a5134521fd4b03/stimuli/style-transfer-preprocessed-512/keyboard/keyboard1-knife1.png
  tensorflow_datasets/testing/test_data/fake_examples/geirhos_conflict_stimuli/texture_vs_shape/texture-vs-shape-1b69c6a445c3348927139edb30a5134521fd4b03/stimuli/style-transfer-preprocessed-512/knife/knife1-keyboard1.png
  tensorflow_datasets/url_checksums/geirhos_conflict_stimuli.txt
Labels: cla: no

#1628 Fix eager test since TF2 switch
  tensorflow_datasets/eager_not_enabled_by_default_test.py
Labels: cla: no

#1623 Add support for encoding audio features from file objects.
  tensorflow_datasets/core/features/audio_feature.py
  tensorflow_datasets/core/features/audio_feature_test.py
Labels: cla: no

#1625 Optimize libritts generator to avoid extracting huge tarballs, speeding up extraction.
  tensorflow_datasets/audio/libritts.py
  tensorflow_datasets/audio/libritts_test.py
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-clean.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-clean/LibriTTS/dev-clean/11/01/11_01.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-clean/LibriTTS/dev-clean/11/01/11_01_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-clean/LibriTTS/dev-clean/12/02/12_02.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-clean/LibriTTS/dev-clean/12/02/12_02_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-clean/LibriTTS/speakers.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-other.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-other/LibriTTS/dev-other/13/03/13_03.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-other/LibriTTS/dev-other/13/03/13_03_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-other/LibriTTS/dev-other/14/04/14_04.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-other/LibriTTS/dev-other/14/04/14_04_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-other/LibriTTS/speakers.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-clean.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-clean/LibriTTS/speakers.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-clean/LibriTTS/test-clean/15/05/15_05.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-clean/LibriTTS/test-clean/15/05/15_05_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-clean/LibriTTS/test-clean/16/06/16_06.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-clean/LibriTTS/test-clean/16/06/16_06_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-other.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-other/LibriTTS/speakers.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-other/LibriTTS/test-clean/17/07/17_07.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-other/LibriTTS/test-clean/17/07/17_07_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-other/LibriTTS/test-clean/18/08/18_08.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-other/LibriTTS/test-clean/18/08/18_08_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-100.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-100/LibriTTS/speakers.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-100/LibriTTS/train-clean-100/19/09/19_09.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-100/LibriTTS/train-clean-100/19/09/19_09_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-100/LibriTTS/train-clean-100/20/10/20_10.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-100/LibriTTS/train-clean-100/20/10/20_10_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-360.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-360/LibriTTS/speakers.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-360/LibriTTS/train-clean-360/21/11/21_11.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-360/LibriTTS/train-clean-360/21/11/21_11_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-360/LibriTTS/train-clean-360/22/12/22_12.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-360/LibriTTS/train-clean-360/22/12/22_12_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-other-500.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-other-500/LibriTTS/speakers.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-other-500/LibriTTS/train-other-500/23/13/23_13.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-other-500/LibriTTS/train-other-500/23/13/23_13_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-other-500/LibriTTS/train-other-500/24/14/24_14.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-other-500/LibriTTS/train-other-500/24/14/24_14_0000_000.wav
Labels: cla: no

#1627 Beam-ify the robonet dataset.
  tensorflow_datasets/core/features/video_feature.py
  tensorflow_datasets/video/robonet.py
Labels: cla: no

#1637 Fix pytests not running
  oss_scripts/oss_tests.sh
Labels: cla: no

#1643 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/geirhos_conflict_stimuli.md
  docs/catalog/libritts.md
  docs/catalog/overview.md
  docs/catalog/robonet.md
  docs/catalog/savee.md
  tensorflow_datasets/testing/metadata/geirhos_conflict_stimuli/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/geirhos_conflict_stimuli/1.0.0/image.image.json
  tensorflow_datasets/testing/metadata/geirhos_conflict_stimuli/1.0.0/shape_imagenet_labels.labels.txt
  tensorflow_datasets/testing/metadata/geirhos_conflict_stimuli/1.0.0/shape_label.labels.txt
  tensorflow_datasets/testing/metadata/geirhos_conflict_stimuli/1.0.0/texture_imagenet_labels.labels.txt
  tensorflow_datasets/testing/metadata/geirhos_conflict_stimuli/1.0.0/texture_label.labels.txt
  tensorflow_datasets/testing/metadata/libritts/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/libritts/1.0.1/metadata.json
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/robonet/robonet_128/3.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/robonet/robonet_128/3.0.0/video.image.json
  tensorflow_datasets/testing/metadata/robonet/robonet_sample_128/3.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/robonet/robonet_sample_128/3.0.0/video.image.json
  tensorflow_datasets/testing/metadata/robonet/robonet_sample_64/3.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/robonet/robonet_sample_64/3.0.0/video.image.json
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#1585 Add BLiMP dataset.
  tensorflow_datasets/testing/test_data/fake_examples/blimp/tough_vs_raising_1.jsonl
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/blimp.py
  tensorflow_datasets/text/blimp_test.py
  tensorflow_datasets/url_checksums/blimp.txt
Labels: cla: no

#1635 Reduce RAM requirements for loading CFQ data from over 40GB to around 4GB.
  tensorflow_datasets/text/cfq.py
Labels: cla: no

#1630 use correct script location
  docs/add_dataset.md
Labels: cla: yes, tfds:ready_to_merge

#1661 script update
  tensorflow_datasets/scripts/replace_fake_images.py
Labels: author:kokoro_test_failed, cla: yes

#1663 Automated documentation update
  docs/catalog/beans.md
  docs/catalog/big_patent.md
  docs/catalog/blimp.md
  docs/catalog/cfq.md
  tensorflow_datasets/testing/metadata/cfq/mcd1/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/cfq/mcd2/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/cfq/mcd3/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/cfq/query_complexity_split/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/cfq/query_pattern_split/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/cfq/question_complexity_split/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/cfq/question_pattern_split/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/cfq/random_split/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#1645 Update scientific_papers dataset links and checksums
  tensorflow_datasets/summarization/scientific_papers.py
  tensorflow_datasets/url_checksums/scientific_papers.txt
Labels: author:kokoro_test_failed, cla: yes

#1641 Add label names for oxford_flowers102
  tensorflow_datasets/image/oxford_flowers102.py
Labels: author:kokoro_test_failed, cla: yes

#1662 Hack to fix kokoro tests
  oss_scripts/oss_tests.sh
Labels: cla: no

#1665 Switch TFDS to tf.compat.v2.Dataset
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/dataset_utils.py
  tensorflow_datasets/core/file_format_adapter_test.py
  tensorflow_datasets/core/tf_compat.py
  tensorflow_datasets/core/tfrecords_reader.py
Labels: cla: no

#1677 Fix and cleanup tf_compat
  tensorflow_datasets/core/tf_compat.py
Labels: cla: no

#1676 Add Open Images Challenge 2019 dataset to TFDS.
  tensorflow_datasets/object_detection/__init__.py
  tensorflow_datasets/object_detection/open_images_challenge2019.py
  tensorflow_datasets/object_detection/open_images_challenge2019_beam.py
  tensorflow_datasets/object_detection/open_images_challenge2019_test.py
  tensorflow_datasets/testing/test_data/fake_examples/open_images_challenge2019_detection/challenge-2019-classes-description-500.csv
  tensorflow_datasets/testing/test_data/fake_examples/open_images_challenge2019_detection/challenge-2019-label500-hierarchy.json
  tensorflow_datasets/testing/test_data/fake_examples/open_images_challenge2019_detection/challenge-2019-train-detection-bbox.csv
  tensorflow_datasets/testing/test_data/fake_examples/open_images_challenge2019_detection/challenge-2019-train-detection-human-imagelabels.csv
  tensorflow_datasets/testing/test_data/fake_examples/open_images_challenge2019_detection/test.zip
  tensorflow_datasets/testing/test_data/fake_examples/open_images_challenge2019_detection/train_00.zip
  tensorflow_datasets/testing/test_data/fake_examples/open_images_challenge2019_detection/train_01.zip
  tensorflow_datasets/testing/test_data/fake_examples/open_images_challenge2019_detection/train_02.zip
  tensorflow_datasets/testing/test_data/fake_examples/open_images_challenge2019_detection/train_03.zip
  tensorflow_datasets/testing/test_data/fake_examples/open_images_challenge2019_detection/train_04.zip
  tensorflow_datasets/testing/test_data/fake_examples/open_images_challenge2019_detection/train_05.zip
  tensorflow_datasets/testing/test_data/fake_examples/open_images_challenge2019_detection/train_06.zip
  tensorflow_datasets/testing/test_data/fake_examples/open_images_challenge2019_detection/train_07.zip
  tensorflow_datasets/testing/test_data/fake_examples/open_images_challenge2019_detection/train_08.zip
  tensorflow_datasets/testing/test_data/fake_examples/open_images_challenge2019_detection/validation-detection-bbox.csv
  tensorflow_datasets/testing/test_data/fake_examples/open_images_challenge2019_detection/validation-detection-human-imagelabels.csv
  tensorflow_datasets/testing/test_data/fake_examples/open_images_challenge2019_detection/validation.zip
  tensorflow_datasets/url_checksums/open_images_challenge2019_detection.txt
Labels: cla: no

#1685 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/open_images_challenge2019_detection.md
  docs/catalog/overview.md
  docs/catalog/oxford_flowers102.md
  docs/catalog/scientific_papers.md
  docs/catalog/so2sat.md
  docs/catalog/waymo_open_dataset.md
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/oxford_flowers102/2.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/oxford_flowers102/2.1.0/image.image.json
  tensorflow_datasets/testing/metadata/oxford_flowers102/2.1.0/label.labels.txt
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#1686 Add warning to ask people to migrate to Python3
  tensorflow_datasets/core/tf_compat.py
Labels: cla: no

#1659 Add CREMA-D to tensorflow datasets
  tensorflow_datasets/audio/__init__.py
  tensorflow_datasets/audio/crema_d.py
  tensorflow_datasets/audio/crema_d_test.py
  tensorflow_datasets/testing/test_data/fake_examples/crema_d/1000_AA_HAP_XX.wav
  tensorflow_datasets/testing/test_data/fake_examples/crema_d/1001_AA_HAP_XX.wav
  tensorflow_datasets/testing/test_data/fake_examples/crema_d/1002_AA_ANG_XX.wav
  tensorflow_datasets/testing/test_data/fake_examples/crema_d/1003_AA_FEA_XX.wav
  tensorflow_datasets/testing/test_data/fake_examples/crema_d/summary_table.csv
  tensorflow_datasets/url_checksums/crema_d.txt
Labels: cla: no

#1700 Allow to load previous scientific_papers dataset
  docs/datasets_versioning.md
  tensorflow_datasets/summarization/scientific_papers.py
Labels: cla: no

#1675 Adding class balanced 1% of ImageNet subset, which was used for semi-supervised learning evaluation in SimCLR paper (https://arxiv.org/abs/2002.05709).
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/imagenet2012_subset.py
  tensorflow_datasets/image/imagenet2012_subset_test.py
  tensorflow_datasets/testing/test_data/fake_examples/imagenet2012_subset/1percent.txt
  tensorflow_datasets/testing/test_data/fake_examples/imagenet2012_subset/ILSVRC2012_img_train.tar
  tensorflow_datasets/testing/test_data/fake_examples/imagenet2012_subset/ILSVRC2012_img_val.tar
  tensorflow_datasets/url_checksums/imagenet2012_subset.txt
Labels: cla: no

#1687 Internal
  tensorflow_datasets/testing/test_data/fake_examples/wiki40b/dev/en_examples-00000-of-00001
  tensorflow_datasets/testing/test_data/fake_examples/wiki40b/test/en_examples-00000-of-00001
  tensorflow_datasets/testing/test_data/fake_examples/wiki40b/train/en_examples-00000-of-00001
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/wiki40b.py
  tensorflow_datasets/text/wiki40b_test.py
Labels: cla: no

#1693 Print error message in registered.py for datasets not updated in pip package.
  tensorflow_datasets/core/registered.py
Labels: author:kokoro_test_failed, cla: yes

#1697 Update lazy_imports_lib.py
  tensorflow_datasets/core/lazy_imports_lib.py
Labels: author:kokoro_test_failed, cla: yes

#1703 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/crema_d.md
  docs/catalog/imagenette.md
  docs/catalog/open_images_challenge2019_detection.md
  docs/catalog/overview.md
  docs/catalog/scientific_papers.md
  docs/catalog/waymo_open_dataset.md
  tensorflow_datasets/testing/metadata/crema_d/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/crema_d/1.0.0/label.labels.txt
  tensorflow_datasets/testing/metadata/imagenette/160px-v2/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/imagenette/160px-v2/0.1.0/image.image.json
  tensorflow_datasets/testing/metadata/imagenette/160px-v2/0.1.0/label.labels.txt
  tensorflow_datasets/testing/metadata/imagenette/320px-v2/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/imagenette/320px-v2/0.1.0/image.image.json
  tensorflow_datasets/testing/metadata/imagenette/320px-v2/0.1.0/label.labels.txt
  tensorflow_datasets/testing/metadata/imagenette/full-size-v2/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/imagenette/full-size-v2/0.1.0/image.image.json
  tensorflow_datasets/testing/metadata/imagenette/full-size-v2/0.1.0/label.labels.txt
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/open_images_challenge2019_detection/200k/1.0.0/bobjects-label.labels.txt
  tensorflow_datasets/testing/metadata/open_images_challenge2019_detection/200k/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/open_images_challenge2019_detection/200k/1.0.0/image.image.json
  tensorflow_datasets/testing/metadata/open_images_challenge2019_detection/200k/1.0.0/objects-label.labels.txt
  tensorflow_datasets/testing/metadata/open_images_challenge2019_detection/300k/1.0.0/bobjects-label.labels.txt
  tensorflow_datasets/testing/metadata/open_images_challenge2019_detection/300k/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/open_images_challenge2019_detection/300k/1.0.0/image.image.json
  tensorflow_datasets/testing/metadata/open_images_challenge2019_detection/300k/1.0.0/objects-label.labels.txt
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#1705 Fix beam.DoFn classes.
  tensorflow_datasets/object_detection/open_images_challenge2019_beam.py
Labels: cla: no

#1711 Add "id" field to the CIFAR datasets, for the user convenience.
  tensorflow_datasets/image/cifar.py
Labels: cla: no

#1720 Revert Cifar change
  tensorflow_datasets/image/cifar.py
Labels: cla: no

#1713 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/beans.md
  docs/catalog/big_patent.md
  docs/catalog/crema_d.md
  docs/catalog/imagenet2012_subset.md
  docs/catalog/imagenette.md
  docs/catalog/overview.md
  docs/catalog/wiki40b.md
  tensorflow_datasets/testing/metadata/missing.txt
Labels: cla: no

#1721 Update crema_d_test.py
  tensorflow_datasets/audio/crema_d_test.py
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: yes, community:please_review

#1727 Automated documentation update
  docs/catalog/beans.md
  docs/catalog/big_patent.md
  docs/catalog/cifar10.md
  docs/catalog/cifar100.md
  docs/catalog/imagenet2012_subset.md
  docs/catalog/overview.md
  docs/catalog/scientific_papers.md
  docs/catalog/wiki40b.md
  tensorflow_datasets/testing/metadata/cifar10/3.0.2/dataset_info.json
  tensorflow_datasets/testing/metadata/cifar10/3.0.2/image.image.json
  tensorflow_datasets/testing/metadata/cifar10/3.0.2/label.labels.txt
  tensorflow_datasets/testing/metadata/cifar100/3.0.2/coarse_label.labels.txt
  tensorflow_datasets/testing/metadata/cifar100/3.0.2/dataset_info.json
  tensorflow_datasets/testing/metadata/cifar100/3.0.2/image.image.json
  tensorflow_datasets/testing/metadata/cifar100/3.0.2/label.labels.txt
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/scientific_papers/arxiv/1.1.1/dataset_info.json
  tensorflow_datasets/testing/metadata/scientific_papers/pubmed/1.1.1/dataset_info.json
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#1728 Refactor visualisation util
  tensorflow_datasets/core/visualization.py
  tensorflow_datasets/core/visualization/__init__.py
  tensorflow_datasets/core/visualization/image_visualizer.py
  tensorflow_datasets/core/visualization/show_examples.py
  tensorflow_datasets/core/visualization/show_examples_test.py
  tensorflow_datasets/core/visualization/visualizer.py
  tensorflow_datasets/public_api.py
Labels: cla: no

#1723 changed a way of loading proto file for Waymo dataset.
  tensorflow_datasets/object_detection/waymo_open_dataset.py
  tensorflow_datasets/proto/__init__.py
  tensorflow_datasets/proto/waymo_dataset_generated_pb2.py
Labels: cla: no

#1729 Move fake data generation script to a separate folder
  docs/add_dataset.md
  tensorflow_datasets/testing/fake_data_generation/abstract_reasoning.py
  tensorflow_datasets/testing/fake_data_generation/arc.py
  tensorflow_datasets/testing/fake_data_generation/bair_robot_pushing.py
  tensorflow_datasets/testing/fake_data_generation/beans.py
  tensorflow_datasets/testing/fake_data_generation/binarized_mnist.py
  tensorflow_datasets/testing/fake_data_generation/caltech.py
  tensorflow_datasets/testing/fake_data_generation/cassava.py
  tensorflow_datasets/testing/fake_data_generation/cats_vs_dogs.py
  tensorflow_datasets/testing/fake_data_generation/cifar.py
  tensorflow_datasets/testing/fake_data_generation/cityscapes.py
  tensorflow_datasets/testing/fake_data_generation/clevr.py
  tensorflow_datasets/testing/fake_data_generation/coil100.py
  tensorflow_datasets/testing/fake_data_generation/colorectal_histology.py
  tensorflow_datasets/testing/fake_data_generation/curated_breast_imaging_ddsm.py
  tensorflow_datasets/testing/fake_data_generation/div2k.py
  tensorflow_datasets/testing/fake_data_generation/dsprites.py
  tensorflow_datasets/testing/fake_data_generation/dtd.py
  tensorflow_datasets/testing/fake_data_generation/e2e_binary.py
  tensorflow_datasets/testing/fake_data_generation/flic.py
  tensorflow_datasets/testing/fake_data_generation/horses_or_humans.py
  tensorflow_datasets/testing/fake_data_generation/imagenet.py
  tensorflow_datasets/testing/fake_data_generation/imagenet_resized.py
  tensorflow_datasets/testing/fake_data_generation/kitti.py
  tensorflow_datasets/testing/fake_data_generation/lost_and_found.py
  tensorflow_datasets/testing/fake_data_generation/lsun.py
  tensorflow_datasets/testing/fake_data_generation/malaria.py
  tensorflow_datasets/testing/fake_data_generation/mnist.py
  tensorflow_datasets/testing/fake_data_generation/open_images.py
  tensorflow_datasets/testing/fake_data_generation/oxford_iiit_pet.py
  tensorflow_datasets/testing/fake_data_generation/patch_camelyon.py
  tensorflow_datasets/testing/fake_data_generation/rock_paper_scissors.py
  tensorflow_datasets/testing/fake_data_generation/shapes3d.py
  tensorflow_datasets/testing/fake_data_generation/smallnorb.py
  tensorflow_datasets/testing/fake_data_generation/smallnorb_test.py
  tensorflow_datasets/testing/fake_data_generation/starcraft.py
  tensorflow_datasets/testing/fake_data_generation/sun397.py
  tensorflow_datasets/testing/fake_data_generation/voc2007.py
Labels: cla: no

#1726 [glue/mnli] fix typo
  tensorflow_datasets/text/glue.py
Labels: author:kokoro_test_failed, cla: yes

#1735 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/beans.md
  docs/catalog/big_patent.md
  docs/catalog/cifar10.md
  docs/catalog/cifar100.md
  docs/catalog/glue.md
  docs/catalog/overview.md
  docs/catalog/tedlium.md
  docs/catalog/wiki40b.md
  tensorflow_datasets/testing/metadata/missing.txt
Labels: cla: no

#1736 Bump CREPE version w/ fix for NSynth and bump NSynth version.
  setup.py
  tensorflow_datasets/audio/nsynth.py
Labels: cla: no

#1740 Update splits.md
  docs/splits.md
Labels: cla: yes, community:please_review

#1743 Add `sample_rate` property to `tfds.features.Audio`.
  tensorflow_datasets/audio/librispeech.py
  tensorflow_datasets/audio/libritts.py
  tensorflow_datasets/audio/ljspeech.py
  tensorflow_datasets/audio/speech_commands.py
  tensorflow_datasets/audio/tedlium.py
  tensorflow_datasets/core/features/audio_feature.py
  tensorflow_datasets/core/features/audio_feature_test.py
Labels: cla: no

#1738 Update tfrecords_reader.py
  tensorflow_datasets/core/tfrecords_reader.py
Labels: cla: yes

#1748 Update Audio feature to support float and update corresponding datasets
  tensorflow_datasets/audio/groove.py
  tensorflow_datasets/audio/nsynth.py
  tensorflow_datasets/core/features/audio_feature.py
  tensorflow_datasets/core/features/audio_feature_test.py
Labels: cla: no

#1760 Add sample rate metadata to savee and crema_d datasets.
  tensorflow_datasets/audio/crema_d.py
  tensorflow_datasets/audio/savee.py
Labels: cla: no

#1764 Fix bug sun397 dataset.
  tensorflow_datasets/image_classification/sun.py
Labels: cla: no

#1759 Add VoxCeleb1 to tensorflow datasets
  tensorflow_datasets/audio/__init__.py
  tensorflow_datasets/audio/voxceleb.py
  tensorflow_datasets/audio/voxceleb_test.py
  tensorflow_datasets/testing/test_data/fake_examples/voxceleb/iden_split.txt
  tensorflow_datasets/testing/test_data/fake_examples/voxceleb/vox_dev_wav.zip
  tensorflow_datasets/url_checksums/voxceleb.txt
Labels: cla: no

#1732 Fix flag name in error message.
  tensorflow_datasets/core/download/checksums.py
Labels: cla: no

#1767 Adding STL-10 to tensorflow datasets.
  tensorflow_datasets/image_classification/__init__.py
  tensorflow_datasets/image_classification/stl10.py
  tensorflow_datasets/image_classification/stl10_test.py
  tensorflow_datasets/testing/fake_data_generation/stl10.py
  tensorflow_datasets/testing/test_data/fake_examples/stl10/stl10_binary/class_names.txt
  tensorflow_datasets/testing/test_data/fake_examples/stl10/stl10_binary/test_X.bin
  tensorflow_datasets/testing/test_data/fake_examples/stl10/stl10_binary/test_y.bin
  tensorflow_datasets/testing/test_data/fake_examples/stl10/stl10_binary/train_X.bin
  tensorflow_datasets/testing/test_data/fake_examples/stl10/stl10_binary/train_y.bin
  tensorflow_datasets/testing/test_data/fake_examples/stl10/stl10_binary/unlabeled_X.bin
  tensorflow_datasets/url_checksums/stl10.txt
Labels: cla: no

#1778 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/beans.md
  docs/catalog/big_patent.md
  docs/catalog/imagenet_resized.md
  docs/catalog/overview.md
  docs/catalog/stl10.md
  docs/catalog/voxceleb.md
  docs/catalog/wiki40b.md
  tensorflow_datasets/testing/metadata/missing.txt
Labels: cla: no

#1779 Make DownloadManager pickle-able.
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/download_manager_test.py
Labels: cla: no
