Repository tensorflow/datasets, pull requests merged in 2020-01, with the labels that each got.

#1146 Added Dep of Tensorflow_io.lmdb to LSUN
  oss_scripts/oss_tests.sh
  setup.py
  tensorflow_datasets/core/lazy_imports_lib.py
  tensorflow_datasets/image/lsun.py
Labels: cla: no

#1319 Fix indentation in README
  README.md
Labels: cla: yes

#1332 fixed some minor typos
  docs/add_dataset.md
Labels: being_merged, cla: yes

#1328 make sure to use gfile instead of os.path.exists.
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: no

#1327 Fix 404 link in docs/add_dataset.md
  docs/add_dataset.md
Labels: cla: yes

#1330 Automated documentation update
  docs/api_docs/python/_redirects.yaml
  docs/catalog/_toc.yaml
  docs/catalog/arc.md
  docs/catalog/cityscapes.md
  docs/catalog/nsynth.md
  docs/catalog/overview.md
  docs/catalog/wikipedia.md
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/nsynth/full/2.2.0/dataset_info.json
  tensorflow_datasets/testing/metadata/nsynth/full/2.2.0/instrument-family.labels.txt
  tensorflow_datasets/testing/metadata/nsynth/full/2.2.0/instrument-label.labels.txt
  tensorflow_datasets/testing/metadata/nsynth/full/2.2.0/instrument-source.labels.txt
  tensorflow_datasets/testing/metadata/nsynth/full/2.2.0/metadata.json
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset.f0_and_loudness/2.2.0/dataset_info.json
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset.f0_and_loudness/2.2.0/instrument-family.labels.txt
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset.f0_and_loudness/2.2.0/instrument-label.labels.txt
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset.f0_and_loudness/2.2.0/instrument-source.labels.txt
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset.f0_and_loudness/2.2.0/metadata.json
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset/2.2.0/dataset_info.json
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset/2.2.0/instrument-family.labels.txt
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset/2.2.0/instrument-label.labels.txt
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset/2.2.0/instrument-source.labels.txt
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset/2.2.0/metadata.json
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#1341 Remove sub-configurations in math data set that don't have training data.
  tensorflow_datasets/testing/test_data/fake_examples/math_dataset/mathematics_dataset-v1.0/interpolate/algebra__linear_1d.txt
  tensorflow_datasets/testing/test_data/fake_examples/math_dataset/mathematics_dataset-v1.0/interpolate/arithmetic__div_big.txt
  tensorflow_datasets/testing/test_data/fake_examples/math_dataset/mathematics_dataset-v1.0/train-easy/algebra__linear_1d.txt
  tensorflow_datasets/testing/test_data/fake_examples/math_dataset/mathematics_dataset-v1.0/train-easy/arithmetic__div_big.txt
  tensorflow_datasets/testing/test_data/fake_examples/math_dataset/mathematics_dataset-v1.0/train-hard/algebra__linear_1d.txt
  tensorflow_datasets/testing/test_data/fake_examples/math_dataset/mathematics_dataset-v1.0/train-hard/arithmetic__div_big.txt
  tensorflow_datasets/testing/test_data/fake_examples/math_dataset/mathematics_dataset-v1.0/train-medium/algebra__linear_1d.txt
  tensorflow_datasets/testing/test_data/fake_examples/math_dataset/mathematics_dataset-v1.0/train-medium/arithmetic__div_big.txt
  tensorflow_datasets/text/math_dataset.py
  tensorflow_datasets/text/math_dataset_test.py
Labels: cla: no

#1324 Update NSynth Dataset
  tensorflow_datasets/audio/nsynth.py
Labels: cla: no

#1347 Update EMNIST homepage
  tensorflow_datasets/image/mnist.py
Labels: cla: no

#1346 Explictly use DatasetV1 objects
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/dataset_utils.py
  tensorflow_datasets/core/file_format_adapter.py
  tensorflow_datasets/core/file_format_adapter_test.py
  tensorflow_datasets/core/tfrecords_reader.py
Labels: cla: no

#1349 Save without outputs
  docs/overview.ipynb
Labels: cla: no

#1348 Automated documentation update
  docs/api_docs/python/tfds/file_adapter.md
  docs/catalog/cityscapes.md
  docs/catalog/math_dataset.md
  docs/catalog/nsynth.md
  tensorflow_datasets/testing/metadata/missing.txt
Labels: cla: no

#1352 TFDS: bigearthnet dataset reading from archive directly.
  tensorflow_datasets/image/bigearthnet.py
  tensorflow_datasets/image/bigearthnet_test.py
  tensorflow_datasets/testing/test_data/fake_examples/bigearthnet/BigEarthNet-v1.0.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/bigearthnet/BigEarthNet-v1.0/S2A_MSIL2A_20170613T101031_12_79/S2A_MSIL2A_20170613T101031_12_79_B01.tif
  tensorflow_datasets/testing/test_data/fake_examples/bigearthnet/BigEarthNet-v1.0/S2A_MSIL2A_20170613T101031_12_79/S2A_MSIL2A_20170613T101031_12_79_B02.tif
  tensorflow_datasets/testing/test_data/fake_examples/bigearthnet/BigEarthNet-v1.0/S2A_MSIL2A_20170613T101031_12_79/S2A_MSIL2A_20170613T101031_12_79_B03.tif
  tensorflow_datasets/testing/test_data/fake_examples/bigearthnet/BigEarthNet-v1.0/S2A_MSIL2A_20170613T101031_12_79/S2A_MSIL2A_20170613T101031_12_79_B04.tif
  tensorflow_datasets/testing/test_data/fake_examples/bigearthnet/BigEarthNet-v1.0/S2A_MSIL2A_20170613T101031_12_79/S2A_MSIL2A_20170613T101031_12_79_B05.tif
  tensorflow_datasets/testing/test_data/fake_examples/bigearthnet/BigEarthNet-v1.0/S2A_MSIL2A_20170613T101031_12_79/S2A_MSIL2A_20170613T101031_12_79_B06.tif
  tensorflow_datasets/testing/test_data/fake_examples/bigearthnet/BigEarthNet-v1.0/S2A_MSIL2A_20170613T101031_12_79/S2A_MSIL2A_20170613T101031_12_79_B07.tif
  tensorflow_datasets/testing/test_data/fake_examples/bigearthnet/BigEarthNet-v1.0/S2A_MSIL2A_20170613T101031_12_79/S2A_MSIL2A_20170613T101031_12_79_B08.tif
  tensorflow_datasets/testing/test_data/fake_examples/bigearthnet/BigEarthNet-v1.0/S2A_MSIL2A_20170613T101031_12_79/S2A_MSIL2A_20170613T101031_12_79_B09.tif
  tensorflow_datasets/testing/test_data/fake_examples/bigearthnet/BigEarthNet-v1.0/S2A_MSIL2A_20170613T101031_12_79/S2A_MSIL2A_20170613T101031_12_79_B11.tif
  tensorflow_datasets/testing/test_data/fake_examples/bigearthnet/BigEarthNet-v1.0/S2A_MSIL2A_20170613T101031_12_79/S2A_MSIL2A_20170613T101031_12_79_B12.tif
  tensorflow_datasets/testing/test_data/fake_examples/bigearthnet/BigEarthNet-v1.0/S2A_MSIL2A_20170613T101031_12_79/S2A_MSIL2A_20170613T101031_12_79_B8A.tif
  tensorflow_datasets/testing/test_data/fake_examples/bigearthnet/BigEarthNet-v1.0/S2A_MSIL2A_20170613T101031_12_79/S2A_MSIL2A_20170613T101031_12_79_labels_metadata.json
Labels: cla: no

#1353 TFDS: wikipedia dataset: remove "kr" language, it has no articles.
  tensorflow_datasets/text/wikipedia.py
Labels: cla: no

#1329 Update blog URLs
  docs/_index.yaml
Labels: cla: no

#1354 TFDS: SplitInfo: use sum(shard_lengths) when possible to compute num_examples.
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/splits.py
Labels: cla: no

#1357 Automated documentation update
  docs/catalog/emnist.md
  docs/catalog/nsynth.md
  docs/catalog/places365_small.md
  docs/catalog/wikipedia.md
  tensorflow_datasets/testing/metadata/bigearthnet/all/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/bigearthnet/all/1.0.0/labels.labels.txt
  tensorflow_datasets/testing/metadata/bigearthnet/rgb/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/bigearthnet/rgb/1.0.0/image.image.json
  tensorflow_datasets/testing/metadata/bigearthnet/rgb/1.0.0/labels.labels.txt
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/nsynth/full/2.3.0/dataset_info.json
  tensorflow_datasets/testing/metadata/nsynth/full/2.3.0/instrument-family.labels.txt
  tensorflow_datasets/testing/metadata/nsynth/full/2.3.0/instrument-label.labels.txt
  tensorflow_datasets/testing/metadata/nsynth/full/2.3.0/instrument-source.labels.txt
  tensorflow_datasets/testing/metadata/nsynth/full/2.3.0/metadata.json
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset.f0_and_loudness/2.3.0/dataset_info.json
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset.f0_and_loudness/2.3.0/instrument-family.labels.txt
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset.f0_and_loudness/2.3.0/instrument-label.labels.txt
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset.f0_and_loudness/2.3.0/instrument-source.labels.txt
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset.f0_and_loudness/2.3.0/metadata.json
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset/2.3.0/dataset_info.json
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset/2.3.0/instrument-family.labels.txt
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset/2.3.0/instrument-label.labels.txt
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset/2.3.0/instrument-source.labels.txt
  tensorflow_datasets/testing/metadata/nsynth/gansynth_subset/2.3.0/metadata.json
  tensorflow_datasets/testing/metadata/places365_small/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/places365_small/2.0.0/image.image.json
  tensorflow_datasets/testing/metadata/places365_small/2.0.0/label.labels.txt
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#1355 Added VGGFace2 to TFDS.
  setup.py
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/vgg_face2.py
  tensorflow_datasets/image/vgg_face2_labels.txt
  tensorflow_datasets/image/vgg_face2_test.py
  tensorflow_datasets/testing/test_data/fake_examples/vgg_face2/vggface2_test.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/vgg_face2/vggface2_train.tar.gz
  tensorflow_datasets/url_checksums/vgg_face2.txt
Labels: cla: no

#1363 Add key description to _generate_examples docstring
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#1367 TFDS: Log incriminated examples before raising error on duplicate keys.
  tensorflow_datasets/core/shuffle.py
  tensorflow_datasets/core/shuffle_test.py
  tensorflow_datasets/core/tfrecords_writer.py
  tensorflow_datasets/core/tfrecords_writer_test.py
Labels: cla: no

#1369 TFDS: fix wikipedia: use id instead of title to key records, make pipeline fast.
  tensorflow_datasets/testing/test_data/fake_examples/wikipedia/enwiki_fake.xml
  tensorflow_datasets/testing/test_data/fake_examples/wikipedia/enwiki_fake.xml.bz2
  tensorflow_datasets/testing/test_data/fake_examples/wikipedia/enwiki_fake2.xml
  tensorflow_datasets/testing/test_data/fake_examples/wikipedia/enwiki_fake2.xml.bz2
  tensorflow_datasets/text/wikipedia.py
  tensorflow_datasets/text/wikipedia_test.py
Labels: cla: no

#1297 beam tfrecord writer: clearer error message in case input pcollection has no examples.
  tensorflow_datasets/core/tfrecords_writer.py
  tensorflow_datasets/core/tfrecords_writer_test.py
Labels: cla: no

#1370 Internal
  oss_scripts/oss_tests.sh
  tensorflow_datasets/core/lazy_imports_lib_test.py
Labels: cla: no

#1358 Adding SCAN dataset to TFDS
  docs/release_notes.md
  tensorflow_datasets/testing/test_data/fake_examples/scan/SCAN-master/simple_split/tasks_test_simple.txt
  tensorflow_datasets/testing/test_data/fake_examples/scan/SCAN-master/simple_split/tasks_train_simple.txt
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/scan.py
  tensorflow_datasets/text/scan_test.py
  tensorflow_datasets/url_checksums/scan.txt
Labels: cla: no

#1383 Add PR Template for Dataset Additions
  .github/PULL_REQUEST_TEMPLATE/add_dataset.md
Labels: cla: yes

#1376 Add movie rationales dataset
  tensorflow_datasets/testing/test_data/fake_examples/movie_rationales/movies/docs/test_1.txt
  tensorflow_datasets/testing/test_data/fake_examples/movie_rationales/movies/docs/train_1.txt
  tensorflow_datasets/testing/test_data/fake_examples/movie_rationales/movies/docs/train_2.txt
  tensorflow_datasets/testing/test_data/fake_examples/movie_rationales/movies/docs/train_3.txt
  tensorflow_datasets/testing/test_data/fake_examples/movie_rationales/movies/docs/val_1.txt
  tensorflow_datasets/testing/test_data/fake_examples/movie_rationales/movies/test.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/movie_rationales/movies/train.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/movie_rationales/movies/val.jsonl
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/movie_rationales.py
  tensorflow_datasets/text/movie_rationales_test.py
  tensorflow_datasets/url_checksums/movie_rationales.txt
Labels: cla: no

#1390 Update the documentation for Beam datasets
  docs/_book.yaml
  docs/beam_datasets.md
  docs/overview.ipynb
  docs/splits.md
  tensorflow_datasets/core/download/download_manager.py
Labels: cla: no

#1387 Add the CoS-E Dataset.
  tensorflow_datasets/testing/test_data/fake_examples/cos_e/cos_e_dev.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/cos_e/cos_e_train.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/cos_e/cqa_dev.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/cos_e/cqa_test.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/cos_e/cqa_train.jsonl
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/cos_e.py
  tensorflow_datasets/text/cos_e_test.py
Labels: cla: no

#1398 Add checksum file for CoS-E Dataset.
  tensorflow_datasets/url_checksums/cos_e.txt
Labels: cla: no

#1400 Fix some broken links
  docs/add_dataset.md
Labels: cla: yes

#1401 Extended description of tfds.as_numpy
  tensorflow_datasets/core/dataset_utils.py
Labels: cla: yes

#1399 Add support for using beam in _split_generators()
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_beam_test.py
Labels: cla: no

#1395 Changes to avoid hanging on DataFlow:
  tensorflow_datasets/testing/test_data/fake_examples/c4/cc_0.warc.wet
  tensorflow_datasets/testing/test_data/fake_examples/c4/cc_0.warc.wet.gz
  tensorflow_datasets/testing/test_data/fake_examples/c4/cc_1.warc.wet
  tensorflow_datasets/testing/test_data/fake_examples/c4/cc_1.warc.wet.gz
  tensorflow_datasets/text/c4.py
  tensorflow_datasets/text/c4_test.py
  tensorflow_datasets/text/c4_utils.py
  tensorflow_datasets/text/c4_utils_test.py
Labels: cla: no

#1412 Remove ipykernel dependency
  docs/overview.ipynb
  oss_scripts/oss_tests.sh
Labels: cla: no

#1406 update CNN/DailyMail to cased version.
  tensorflow_datasets/summarization/cnn_dailymail.py
  tensorflow_datasets/summarization/cnn_dailymail_test.py
Labels: cla: yes

#1428 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/cnn_dailymail.md
  docs/catalog/div2k.md
  docs/catalog/eraser_multi_rc.md
  docs/catalog/natural_questions.md
  docs/catalog/overview.md
  docs/catalog/wmt15_translate.md
  tensorflow_datasets/testing/metadata/div2k/bicubic_x2/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/div2k/bicubic_x2/2.0.0/hr.image.json
  tensorflow_datasets/testing/metadata/div2k/bicubic_x2/2.0.0/lr.image.json
  tensorflow_datasets/testing/metadata/div2k/bicubic_x3/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/div2k/bicubic_x3/2.0.0/hr.image.json
  tensorflow_datasets/testing/metadata/div2k/bicubic_x3/2.0.0/lr.image.json
  tensorflow_datasets/testing/metadata/div2k/bicubic_x4/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/div2k/bicubic_x4/2.0.0/hr.image.json
  tensorflow_datasets/testing/metadata/div2k/bicubic_x4/2.0.0/lr.image.json
  tensorflow_datasets/testing/metadata/div2k/bicubic_x8/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/div2k/bicubic_x8/2.0.0/hr.image.json
  tensorflow_datasets/testing/metadata/div2k/bicubic_x8/2.0.0/lr.image.json
  tensorflow_datasets/testing/metadata/div2k/realistic_difficult_x4/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/div2k/realistic_difficult_x4/2.0.0/hr.image.json
  tensorflow_datasets/testing/metadata/div2k/realistic_difficult_x4/2.0.0/lr.image.json
  tensorflow_datasets/testing/metadata/div2k/realistic_mild_x4/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/div2k/realistic_mild_x4/2.0.0/hr.image.json
  tensorflow_datasets/testing/metadata/div2k/realistic_mild_x4/2.0.0/lr.image.json
  tensorflow_datasets/testing/metadata/div2k/realistic_wild_x4/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/div2k/realistic_wild_x4/2.0.0/hr.image.json
  tensorflow_datasets/testing/metadata/div2k/realistic_wild_x4/2.0.0/lr.image.json
  tensorflow_datasets/testing/metadata/div2k/unknown_x2/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/div2k/unknown_x2/2.0.0/hr.image.json
  tensorflow_datasets/testing/metadata/div2k/unknown_x2/2.0.0/lr.image.json
  tensorflow_datasets/testing/metadata/div2k/unknown_x3/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/div2k/unknown_x3/2.0.0/hr.image.json
  tensorflow_datasets/testing/metadata/div2k/unknown_x3/2.0.0/lr.image.json
  tensorflow_datasets/testing/metadata/div2k/unknown_x4/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/div2k/unknown_x4/2.0.0/hr.image.json
  tensorflow_datasets/testing/metadata/div2k/unknown_x4/2.0.0/lr.image.json
  tensorflow_datasets/testing/metadata/eraser_multi_rc/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/eraser_multi_rc/0.1.0/label.labels.txt
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/natural_questions/0.0.1/annotations-yes_no_answer.labels.txt
  tensorflow_datasets/testing/metadata/natural_questions/0.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/supported.txt
  tensorflow_datasets/testing/metadata/wmt15_translate/cs-en.subwords8k/1.0.0/cs.text.subwords
  tensorflow_datasets/testing/metadata/wmt15_translate/cs-en.subwords8k/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/wmt15_translate/cs-en.subwords8k/1.0.0/en.text.subwords
  tensorflow_datasets/testing/metadata/wmt15_translate/de-en.subwords8k/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/wmt15_translate/de-en.subwords8k/1.0.0/de.text.subwords
  tensorflow_datasets/testing/metadata/wmt15_translate/de-en.subwords8k/1.0.0/en.text.subwords
  tensorflow_datasets/testing/metadata/wmt15_translate/fi-en.subwords8k/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/wmt15_translate/fi-en.subwords8k/1.0.0/en.text.subwords
  tensorflow_datasets/testing/metadata/wmt15_translate/fi-en.subwords8k/1.0.0/fi.text.subwords
  tensorflow_datasets/testing/metadata/wmt15_translate/fr-en.subwords8k/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/wmt15_translate/fr-en.subwords8k/1.0.0/en.text.subwords
  tensorflow_datasets/testing/metadata/wmt15_translate/fr-en.subwords8k/1.0.0/fr.text.subwords
  tensorflow_datasets/testing/metadata/wmt15_translate/ru-en.subwords8k/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/wmt15_translate/ru-en.subwords8k/1.0.0/en.text.subwords
  tensorflow_datasets/testing/metadata/wmt15_translate/ru-en.subwords8k/1.0.0/ru.text.subwords
Labels: cla: no

#1429 Flip True/False label indices in eraser_multi_rc to make False 0 and True 1.
  tensorflow_datasets/text/eraser_multi_rc.py
Labels: cla: no

#1430 Update instructions to generate the protobuf
  tensorflow_datasets/core/proto/README.md
  tensorflow_datasets/core/proto/generate_py_proto.sh
  tensorflow_datasets/core/proto/install_protoc.sh
Labels: cla: no

#1431 Make size_in_bytes reflect final dataset size instead of downloaded size.
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/dataset_info_test.py
  tensorflow_datasets/core/proto/dataset_info.proto
  tensorflow_datasets/core/proto/dataset_info_generated_pb2.py
  tensorflow_datasets/core/tfrecords_writer.py
  tensorflow_datasets/core/tfrecords_writer_test.py
  tensorflow_datasets/testing/test_data/dataset_info/mnist/3.0.0/dataset_info.json
  tensorflow_datasets/testing/test_data/dataset_info/mnist_unlabeled/3.0.0/dataset_info.json
Labels: cla: no

#1425 Add beans dataset to tfds.
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/beans.py
  tensorflow_datasets/image/beans_test.py
  tensorflow_datasets/testing/beans.py
  tensorflow_datasets/testing/test_data/fake_examples/beans/beans_test.zip
  tensorflow_datasets/testing/test_data/fake_examples/beans/beans_train.zip
  tensorflow_datasets/testing/test_data/fake_examples/beans/beans_validation.zip
  tensorflow_datasets/url_checksums/beans.txt
Labels: cla: no

#1377 Add QA4MRE dataset (CLEF 2013 shared task).
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2011.main.DE.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2011.main.EN.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2011.main.ES.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2011.main.IT.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2011.main.RO.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2012.alzheimers.EN.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2012.main.AR.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2012.main.BG.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2012.main.DE.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2012.main.EN.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2012.main.ES.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2012.main.IT.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2012.main.RO.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2013.alzheimers.EN.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2013.entrance_exam.EN.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2013.main.AR.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2013.main.BG.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2013.main.EN.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2013.main.ES.xml
  tensorflow_datasets/testing/test_data/fake_examples/qa4mre/2013.main.RO.xml
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/qa4mre.py
  tensorflow_datasets/text/qa4mre_test.py
  tensorflow_datasets/url_checksums/qa4mre.txt
Labels: cla: no

#1433 Expose the subplits num_examples and instructions to the public API
  tensorflow_datasets/core/__init__.py
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/naming.py
  tensorflow_datasets/core/naming_test.py
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/core/splits_test.py
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/tfrecords_reader_test.py
Labels: cla: no

#1439 Expose API for reading individual TFRecord files.
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/tfrecords_reader_test.py
Labels: cla: no

#1419 use cased raw text string in bigpatent
  tensorflow_datasets/summarization/big_patent.py
  tensorflow_datasets/testing/test_data/fake_examples/big_patent/bigPatentDataNonTokenized/test.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/big_patent/bigPatentDataNonTokenized/train.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/big_patent/bigPatentDataNonTokenized/val.tar.gz
  tensorflow_datasets/url_checksums/big_patent.txt
Labels: cla: no

#1440 Expose file_instructions to SplitInfo
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/core/splits_test.py
Labels: cla: no
