Repository tensorflow/datasets, pull requests merged in 2020-04, with the labels that each got.

#1780 C4: download raw CC files in beam workers.
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/testing/test_data/fake_examples/c4/wet_urls.txt
  tensorflow_datasets/text/c4.py
  tensorflow_datasets/text/c4_test.py
Labels: cla: no

#1775 Remove `in_memory` argument
  docs/release_notes.md
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/registered.py
  tensorflow_datasets/core/registered_test.py
Labels: cla: no

#1714 Add "id" field to Cars196, DSprites, Food-101, SmallNorb and SVHN.
  tensorflow_datasets/image/dsprites.py
  tensorflow_datasets/image_classification/cars196.py
  tensorflow_datasets/image_classification/food101.py
  tensorflow_datasets/image_classification/smallnorb.py
  tensorflow_datasets/image_classification/svhn.py
Labels: cla: no

#1773 Fix some minor typos
  oss_scripts/oss_tests.sh
  tensorflow_datasets/image_classification/plant_leaves.py
  tensorflow_datasets/image_classification/plantae_k.py
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: yes, tfds:ready_to_merge

#1770 Update checksums.py to display correct dir name
  tensorflow_datasets/core/download/checksums.py
Labels: cla: yes, tfds:ready_to_merge

#1784 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/overview.md
  docs/catalog/reddit.md
  docs/catalog/stl10.md
  docs/catalog/voxceleb.md
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/reddit/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/stl10/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/stl10/1.0.0/image.image.json
  tensorflow_datasets/testing/metadata/stl10/1.0.0/label.labels.txt
  tensorflow_datasets/testing/metadata/supported.txt
  tensorflow_datasets/testing/metadata/voxceleb/1.1.0/dataset_info.json
Labels: cla: no

#1786 Remove deprecated urls dataset info field
  tensorflow_datasets/core/dataset_info.py
Labels: cla: no

#1782 Add dementiabank dataset to tfds
  tensorflow_datasets/audio/__init__.py
  tensorflow_datasets/audio/dementiabank.py
  tensorflow_datasets/audio/dementiabank_test.py
  tensorflow_datasets/testing/test_data/fake_examples/dementiabank/dementia/English/Pitt/Control/cookie/002-0.mp3
  tensorflow_datasets/testing/test_data/fake_examples/dementiabank/dementia/English/Pitt/Control/cookie/002-1.mp3
  tensorflow_datasets/testing/test_data/fake_examples/dementiabank/dementia/English/Pitt/Control/cookie/003-1.mp3
  tensorflow_datasets/testing/test_data/fake_examples/dementiabank/dementia/English/Pitt/Dementia/cookie/000-1.mp3
  tensorflow_datasets/testing/test_data/fake_examples/dementiabank/dementia/English/Pitt/Dementia/cookie/001-1.mp3
Labels: cla: no

#1789 Correctly format markdown instructions for dementiabank.
  tensorflow_datasets/audio/dementiabank.py
Labels: cla: no

#1788 Update stanford_dogs.py to correctly use paths in all OS
  tensorflow_datasets/image_classification/stanford_dogs.py
Labels: cla: yes, tfds:ready_to_merge

#1776 Update stl10.py
  tensorflow_datasets/image_classification/stl10.py
Labels: cla: yes, tfds:ready_to_merge

#1737 Update Wikipedia checksums and dataset
  docs/beam_datasets.md
  tensorflow_datasets/testing/test_data/fake_examples/wikipedia/dumpstatus.json
  tensorflow_datasets/text/wikipedia.py
  tensorflow_datasets/text/wikipedia_test.py
  tensorflow_datasets/url_checksums/wikipedia.txt
Labels: cla: yes, tfds:ready_to_merge

#1787 Auto-dedent description, manual instructions,...
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/scripts/templates/dataset.mako.md
Labels: cla: no

#1706 Read CelebA pictures from archive directly.
  tensorflow_datasets/image/celeba.py
  tensorflow_datasets/image/celeba_test.py
  tensorflow_datasets/testing/test_data/fake_examples/celeb_a/img_align_celeba.zip
  tensorflow_datasets/testing/test_data/fake_examples/celeb_a/img_align_celeba/000001.jpg
  tensorflow_datasets/testing/test_data/fake_examples/celeb_a/img_align_celeba/000002.jpg
  tensorflow_datasets/testing/test_data/fake_examples/celeb_a/img_align_celeba/000003.jpg
  tensorflow_datasets/testing/test_data/fake_examples/celeb_a/img_align_celeba/000004.jpg
  tensorflow_datasets/testing/test_data/fake_examples/celeb_a/img_align_celeba/000005.jpg
  tensorflow_datasets/testing/test_data/fake_examples/celeb_a/img_align_celeba/000006.jpg
Labels: cla: yes, tfds:ready_to_merge

#1796 Add WebQuestions dataset.
  tensorflow_datasets/testing/test_data/fake_examples/web_questions/test.json
  tensorflow_datasets/testing/test_data/fake_examples/web_questions/train.json
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/web_questions.py
  tensorflow_datasets/text/web_questions_test.py
  tensorflow_datasets/url_checksums/web_questions.txt
Labels: cla: no

#1807 Remove stray debug prints.
  tensorflow_datasets/text/web_questions.py
Labels: cla: no

#1755 Fixed the error in `add_dataset.md`
  docs/add_dataset.md
Labels: cla: yes, community:please_review

#1808 Fix GCS path for wiki40b
  tensorflow_datasets/text/wiki40b.py
Labels: cla: no

#1809 Minor fake images compression script update
  tensorflow_datasets/scripts/replace_fake_images.py
Labels: cla: no

#1810 Fix some catalog header formatting issues
  tensorflow_datasets/scripts/document_datasets.py
Labels: cla: no

#1815 Remove SKIP_CHECKSUMS from c4
  tensorflow_datasets/text/c4_test.py
Labels: cla: no

#1818 Adding documentation on how to authenticate with GCS for restricted datasets access.
  docs/README.md
  docs/gcs.md
  tensorflow_datasets/object_detection/waymo_open_dataset.py
Labels: cla: no

#1819 Fix label name in voxceleb
  tensorflow_datasets/audio/voxceleb.py
Labels: cla: no

#1583 Add visual question-answer feature in clevr dataset
  tensorflow_datasets/image/clevr.py
  tensorflow_datasets/testing/test_data/fake_examples/clevr/CLEVR_v1.0/questions/CLEVR_test_questions.json
  tensorflow_datasets/testing/test_data/fake_examples/clevr/CLEVR_v1.0/questions/CLEVR_train_questions.json
  tensorflow_datasets/testing/test_data/fake_examples/clevr/CLEVR_v1.0/questions/CLEVR_val_questions.json
Labels: cla: yes, community:is_reviewing

#1828 (minor) Remove quote in c4 description.
  tensorflow_datasets/text/c4.py
Labels: cla: no

#1829 Restore CelebA 2.0.0 read support
  tensorflow_datasets/image/celeba.py
Labels: cla: no

#1822 Better error message for Beam datasets
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_beam_test.py
Labels: cla: no

#1835 Restore reading backward compatibility to Clevr 3.0.0.
  tensorflow_datasets/image/clevr.py
Labels: cla: no

#1838 Fix Clevr dataset for test set
  tensorflow_datasets/image/clevr.py
  tensorflow_datasets/testing/test_data/fake_examples/clevr/CLEVR_v1.0/questions/CLEVR_test_questions.json
Labels: cla: no

#1805 Updates Datasets metadata
  docs/_index.yaml
Labels: cla: no

#1844 Fix kokoro tests
  tensorflow_datasets/core/dataset_builder_test.py
Labels: cla: no

#1843 Minor doc update to explicitly use `tfds.testing` namespace
  tensorflow_datasets/testing/mocking.py
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no

#1840 Automated documentation update
  docs/catalog/c4.md
  docs/catalog/celeb_a.md
  docs/catalog/clevr.md
  docs/catalog/common_voice.md
  docs/catalog/voxceleb.md
  docs/catalog/waymo_open_dataset.md
  docs/catalog/web_questions.md
  tensorflow_datasets/testing/metadata/celeb_a/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/celeb_a/2.0.0/image.image.json
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/supported.txt
  tensorflow_datasets/testing/metadata/voxceleb/1.1.1/dataset_info.json
Labels: cla: no

#1842 Internal
  tensorflow_datasets/testing/mocking.py
Labels: cla: no

#1841 Adding MCD splits to SCAN dataset.
  tensorflow_datasets/text/scan.py
  tensorflow_datasets/url_checksums/scan.txt
Labels: cla: no

#1823 Specify correct dataset dependency for beam workers, which excludes the dataset config.
  docs/beam_datasets.md
Labels: cla: no

#1847 Automated documentation update
  docs/catalog/beans.md
  docs/catalog/big_patent.md
  docs/catalog/c4.md
  docs/catalog/clevr.md
  docs/catalog/scan.md
  docs/catalog/wiki40b.md
  tensorflow_datasets/testing/metadata/clevr/3.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/clevr/3.1.0/image.image.json
  tensorflow_datasets/testing/metadata/clevr/3.1.0/objects-color.labels.txt
  tensorflow_datasets/testing/metadata/clevr/3.1.0/objects-material.labels.txt
  tensorflow_datasets/testing/metadata/clevr/3.1.0/objects-shape.labels.txt
  tensorflow_datasets/testing/metadata/clevr/3.1.0/objects-size.labels.txt
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/scan/addprim_jump/1.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/addprim_turn_left/1.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/filler_num0/1.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/filler_num1/1.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/filler_num2/1.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/filler_num3/1.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/length/1.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/simple/1.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/template_around_right/1.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/template_jump_around_right/1.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/template_opposite_right/1.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/template_right/1.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#1848 Minor markdown formatting issue fix for scientific_papers description
  tensorflow_datasets/summarization/scientific_papers.py
Labels: cla: no

#1856 Explicitly mark `num_shards` as deprecated.
  tensorflow_datasets/core/splits.py
Labels: cla: no

#1858 Automated documentation update
  docs/catalog/scan.md
  docs/catalog/scientific_papers.md
Labels: cla: no

#1857 `list_full_names` should not yield datasets with `None` version value
  tensorflow_datasets/core/registered.py
  tensorflow_datasets/stable_versions.txt
Labels: cla: yes, tfds:ready_to_merge

#1851 Remove legacy non-S3 code
  docs/datasets_versioning.md
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/file_format_adapter_test.py
  tensorflow_datasets/core/splits_test.py
  tensorflow_datasets/core/utils/version.py
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: no

#1801 Remove `%tensorflow_version` and `from __future__`
  docs/_index.ipynb
  docs/overview.ipynb
Labels: cla: no

#1860 Better checksums error message
  tensorflow_datasets/core/download/download_manager.py
Labels: cla: no

#1869 Skip notebook tests for TF 1.15
  oss_scripts/oss_tests.sh
Labels: cla: no

#1871 Automated documentation update
  docs/catalog/scientific_papers.md
  tensorflow_datasets/testing/metadata/missing.txt
Labels: cla: no

#1873 Add a warning to indicates the tfds encoder API is deprecated.
  tensorflow_datasets/core/features/text_feature.py
Labels: cla: no

#1820 internal change
  tensorflow_datasets/image/cityscapes.py
Labels: cla: no

#1879 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/overview.md
  tensorflow_datasets/testing/metadata/missing.txt
Labels: cla: no

#1872 Add `tfds.core.add_data_dir` to register additional `data_dir`
  tensorflow_datasets/core/__init__.py
  tensorflow_datasets/core/constants.py
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/dataset_info.py
Labels: cla: no

#1870 Update TFDS version
  tensorflow_datasets/stable_versions.txt
  tensorflow_datasets/version.py
  tensorflow_datasets/version_stable.py
Labels: cla: no

#1874 Tweak loading of SCAN splits and improve documentation.
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/scan.py
Labels: cla: no

#1878 Fix code snippet display of a couple of text datasets.
  tensorflow_datasets/text/cfq.py
  tensorflow_datasets/text/math_dataset.py
Labels: cla: no

#1886 Remove tf.data.Dataset patch
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/tf_compat.py
Labels: cla: no

#1881 Update tests to not use deprecated file_adapter
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no

#1882 Remove deprecated split code
  tensorflow_datasets/core/__init__.py
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/core/splits_test.py
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/public_api.py
Labels: cla: no

#1880 Remove deprecated file_format_adapter
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/file_format_adapter.py
  tensorflow_datasets/core/file_format_adapter_test.py
  tensorflow_datasets/core/tfrecords_writer.py
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/public_api.py
Labels: cla: no

#1887 Automated documentation update
  docs/catalog/cfq.md
  docs/catalog/math_dataset.md
  docs/catalog/scan.md
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/scan/addprim_jump/1.1.1/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/addprim_turn_left/1.1.1/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/filler_num0/1.1.1/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/filler_num1/1.1.1/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/filler_num2/1.1.1/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/filler_num3/1.1.1/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/length/1.1.1/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/simple/1.1.1/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/template_around_right/1.1.1/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/template_jump_around_right/1.1.1/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/template_opposite_right/1.1.1/dataset_info.json
  tensorflow_datasets/testing/metadata/scan/template_right/1.1.1/dataset_info.json
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#1889 Fix regex error for windows
  tensorflow_datasets/image_classification/horses_or_humans.py
Labels: cla: yes, tfds:ready_to_merge

#1876 Update extractor.py
  tensorflow_datasets/core/download/extractor.py
Labels: cla: yes

#1896 Expose datasets filenames to the public API
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/core/splits_test.py
Labels: cla: no

#1899 Fix documentation formatting issues
  tensorflow_datasets/scripts/templates/dataset.mako.md
Labels: cla: no

#1898 Minor corrections in datasets to able to use in windows
  tensorflow_datasets/image_classification/dtd.py
  tensorflow_datasets/image_classification/eurosat.py
  tensorflow_datasets/video/ucf101.py
Labels: cla: yes, tfds:ready_to_merge

#1877 Fix kaggle downloader silent compression to '.zip' files
  tensorflow_datasets/core/download/kaggle.py
Labels: cla: yes, tfds:ready_to_merge

#1895 [tfds] Rename `tfds.core.NamedSplit` -> `tfds.Split`
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#1891 Remove deprecated `num_shards` argument.
  tensorflow_datasets/core/splits.py
Labels: cla: no

#1883 Minor _item_to_tf_feature code cleanup
  tensorflow_datasets/core/example_serializer.py
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no

#1900 Update create_dataset script
  tensorflow_datasets/scripts/create_new_dataset.py
Labels: cla: no

#1894 Minor improvement for GCS logging message.
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#1893 Disable dataset threading by default
  tensorflow_datasets/core/tfrecords_reader.py
Labels: cla: yes, tfds:ready_to_merge

#1906 Internal
  tensorflow_datasets/audio/nsynth_test.py
  tensorflow_datasets/core/api_utils_test.py
  tensorflow_datasets/core/constants.py
  tensorflow_datasets/core/features/class_label_feature.py
  tensorflow_datasets/core/utils/gcs_utils.py
  tensorflow_datasets/image/abstract_reasoning.py
  tensorflow_datasets/image/abstract_reasoning_test.py
  tensorflow_datasets/image/celebahq.py
  tensorflow_datasets/image/cityscapes.py
  tensorflow_datasets/image/clevr.py
  tensorflow_datasets/image/dsprites_test.py
  tensorflow_datasets/image/shapes3d_test.py
  tensorflow_datasets/image_classification/beans.py
  tensorflow_datasets/image_classification/beans_test.py
  tensorflow_datasets/image_classification/chexpert.py
  tensorflow_datasets/image_classification/oxford_iiit_pet.py
  tensorflow_datasets/image_classification/smallnorb_test.py
  tensorflow_datasets/image_classification/stanford_online_products.py
  tensorflow_datasets/image_classification/stanford_online_products_test.py
  tensorflow_datasets/scripts/build_docs_test.py
  tensorflow_datasets/scripts/document_datasets.py
  tensorflow_datasets/scripts/document_datasets_test.py
  tensorflow_datasets/scripts/download_and_prepare.py
  tensorflow_datasets/scripts/print_num_configs.py
  tensorflow_datasets/summarization/reddit.py
  tensorflow_datasets/summarization/reddit_test.py
  tensorflow_datasets/text/qa4mre.py
  tensorflow_datasets/translate/wmt14.py
  tensorflow_datasets/translate/wmt15.py
  tensorflow_datasets/translate/wmt16.py
  tensorflow_datasets/translate/wmt17.py
  tensorflow_datasets/translate/wmt18.py
  tensorflow_datasets/translate/wmt19.py
  tensorflow_datasets/translate/wmt_t2t.py
  tensorflow_datasets/video/moving_sequence_test.py
Labels: cla: no

#1905 Start adding pytype support to TFDS.
  tensorflow_datasets/core/api_utils.py
Labels: cla: no

#1907 Accept string for Split type
  tensorflow_datasets/core/splits.py
Labels: cla: no

#1904 Add more information about `file_instructions` usage
  tensorflow_datasets/core/splits.py
Labels: cla: no

#1908 Minor doc formatting fixes
  tensorflow_datasets/scripts/download_and_prepare.py
  tensorflow_datasets/text/cfq.py
  tensorflow_datasets/text/math_dataset.py
  tensorflow_datasets/text/scan.py
Labels: cla: no

#1910 Automated documentation update
  docs/catalog/beans.md
  docs/catalog/big_patent.md
  docs/catalog/c4.md
  docs/catalog/cmaterdb.md
  docs/catalog/cnn_dailymail.md
  docs/catalog/div2k.md
  docs/catalog/eurosat.md
  docs/catalog/groove.md
  docs/catalog/imagenet2012_subset.md
  docs/catalog/imagenette.md
  docs/catalog/librispeech.md
  docs/catalog/lost_and_found.md
  docs/catalog/lsun.md
  docs/catalog/robonet.md
  docs/catalog/scientific_papers.md
  docs/catalog/starcraft_video.md
  docs/catalog/wiki40b.md
  docs/catalog/wikipedia.md
  docs/catalog/wmt14_translate.md
  docs/catalog/wmt15_translate.md
  docs/catalog/wmt16_translate.md
  docs/catalog/wmt17_translate.md
  docs/catalog/wmt19_translate.md
  docs/catalog/yelp_polarity_reviews.md
Labels: cla: no

#1919 Automated documentation update
  docs/catalog/cfq.md
  docs/catalog/math_dataset.md
  docs/catalog/scan.md
  docs/catalog/wiki40b.md
Labels: cla: no

#1868 Add TED-LIUM 2 corpus which is about 2 times the size of release 1.
  tensorflow_datasets/audio/tedlium.py
  tensorflow_datasets/audio/tedlium_test.py
  tensorflow_datasets/url_checksums/tedlium.txt
Labels: cla: no

#1922 Remove deprecated symbols
  tensorflow_datasets/core/__init__.py
Labels: cla: no

#1926 Automated documentation update
  docs/catalog/beans.md
  docs/catalog/big_patent.md
  docs/catalog/cfq.md
  docs/catalog/math_dataset.md
  docs/catalog/scan.md
  docs/catalog/tedlium.md
  docs/catalog/wiki40b.md
  tensorflow_datasets/testing/metadata/supported.txt
  tensorflow_datasets/testing/metadata/tedlium/release1/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/tedlium/release1/1.0.1/gender.labels.txt
  tensorflow_datasets/testing/metadata/tedlium/release1/1.0.1/metadata.json
  tensorflow_datasets/testing/metadata/tedlium/release2/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/tedlium/release2/1.0.1/gender.labels.txt
  tensorflow_datasets/testing/metadata/tedlium/release2/1.0.1/metadata.json
Labels: cla: no

#1927 Internal
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: no

#1924 Skip (sym)links (but log a warning) when extracting tarballs in stream mode.
  tensorflow_datasets/core/download/extractor.py
Labels: cla: no

#1925 Add TED-LIUM release 3 speech recognition corpus.
  tensorflow_datasets/audio/tedlium.py
  tensorflow_datasets/url_checksums/tedlium.txt
Labels: cla: no

#1861 Add support for custom decoders in mock_data
  tensorflow_datasets/testing/mocking.py
  tensorflow_datasets/testing/mocking_test.py
Labels: cla: yes, tfds:is_reviewing

#1932 Increase robonet version
  tensorflow_datasets/video/robonet.py
Labels: cla: no

#1890 add SAMSum dataset
  tensorflow_datasets/summarization/__init__.py
  tensorflow_datasets/summarization/samsum.py
  tensorflow_datasets/summarization/samsum_test.py
  tensorflow_datasets/testing/test_data/fake_examples/samsum/test.json
  tensorflow_datasets/testing/test_data/fake_examples/samsum/train.json
  tensorflow_datasets/testing/test_data/fake_examples/samsum/val.json
  tensorflow_datasets/url_checksums/samsum.txt
Labels: cla: no

#1933 Automated documentation update
  docs/catalog/tedlium.md
  docs/catalog/wiki40b.md
  tensorflow_datasets/testing/metadata/supported.txt
  tensorflow_datasets/testing/metadata/tedlium/release3/1.0.1/dataset_info.json
  tensorflow_datasets/testing/metadata/tedlium/release3/1.0.1/gender.labels.txt
  tensorflow_datasets/testing/metadata/tedlium/release3/1.0.1/metadata.json
Labels: cla: no

#1934 Accept CamelCase in tfds.load
  tensorflow_datasets/core/naming_test.py
  tensorflow_datasets/core/registered.py
  tensorflow_datasets/core/registered_test.py
Labels: cla: no

#1936 Add a link to c4 generation instructions
  tensorflow_datasets/text/c4.py
Labels: cla: no

#1939 Minor markdown formating fix
  tensorflow_datasets/image_classification/imagewang.py
Labels: cla: no

#1937 Add a `tfds.builder_cls(name)` to get a builder class.
  tensorflow_datasets/core/registered.py
  tensorflow_datasets/core/registered_test.py
  tensorflow_datasets/public_api.py
Labels: cla: no

#1935 Add per-file cardinality
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/core/tfrecords_reader.py
Labels: cla: no

#1885 Update visualization to return fig
  tensorflow_datasets/core/visualization/image_visualizer.py
  tensorflow_datasets/core/visualization/show_examples.py
Labels: author:please_respond, cla: yes

#1942 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/beans.md
  docs/catalog/big_patent.md
  docs/catalog/c4.md
  docs/catalog/overview.md
  docs/catalog/robonet.md
  docs/catalog/samsum.md
  docs/catalog/wiki40b.md
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/robonet/robonet_128/4.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/robonet/robonet_128/4.0.0/video.image.json
  tensorflow_datasets/testing/metadata/robonet/robonet_64/4.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/robonet/robonet_64/4.0.0/video.image.json
  tensorflow_datasets/testing/metadata/robonet/robonet_sample_128/4.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/robonet/robonet_sample_128/4.0.0/video.image.json
  tensorflow_datasets/testing/metadata/robonet/robonet_sample_64/4.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/robonet/robonet_sample_64/4.0.0/video.image.json
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#1943 Rollback cardinality change.
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/core/tfrecords_reader.py
Labels: cla: no

#1941 Add `list_config_names` to registered
  tensorflow_datasets/core/registered.py
Labels: cla: no

#1952 Update calibration factor for so2sat dataset.
  tensorflow_datasets/image_classification/so2sat.py
Labels: cla: no

#1953 Add per-shards cardinality to file instructions
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/tfrecords_reader_test.py
Labels: cla: no

#1955 Add images for the dataset search referencing.
  tensorflow_datasets/scripts/document_datasets.py
  tensorflow_datasets/scripts/templates/dataset.mako.md
  tensorflow_datasets/scripts/templates/schema_org.mako.md
Labels: cla: no

#1959 Fix document_datasets test.
  tensorflow_datasets/scripts/document_datasets_test.py
Labels: cla: no

#1957 Invert ds, ds_info argument orders for tfds.show_examples
  docs/overview.ipynb
  tensorflow_datasets/core/visualization/image_visualizer.py
  tensorflow_datasets/core/visualization/show_examples.py
  tensorflow_datasets/core/visualization/show_examples_test.py
  tensorflow_datasets/core/visualization/visualizer.py
  tensorflow_datasets/scripts/generate_visualization.py
Labels: cla: no

#1965 h5py dataset update
  tensorflow_datasets/image/dsprites.py
  tensorflow_datasets/image/shapes3d.py
  tensorflow_datasets/image_classification/patch_camelyon.py
  tensorflow_datasets/image_classification/so2sat.py
  tensorflow_datasets/video/robonet.py
Labels: cla: no

#1964 Add ContextManager util
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/testing/test_data/hdf5_example_3dshapes.h5
Labels: cla: no

#1967 Rename `interleave_parallel_reads` -> 'interleave_cycle_length'
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/utils/read_config.py
Labels: cla: no

#1962 Use multi-process to generate figures
  tensorflow_datasets/scripts/generate_visualization.py
Labels: cla: no

#1972 Update version to `3.1.0`
  tensorflow_datasets/stable_versions.txt
  tensorflow_datasets/version.py
  tensorflow_datasets/version_stable.py
Labels: cla: no

#1929 Update tf_flower dataset to iterate over archive
  tensorflow_datasets/image_classification/flowers.py
  tensorflow_datasets/image_classification/flowers_test.py
  tensorflow_datasets/testing/test_data/fake_examples/tf_flowers/flower_photos.tgz
  tensorflow_datasets/testing/test_data/fake_examples/tf_flowers/flower_photos/daisy/000001_daisy.jpg
  tensorflow_datasets/testing/test_data/fake_examples/tf_flowers/flower_photos/dandelion/000001_dandelion.jpg
  tensorflow_datasets/testing/test_data/fake_examples/tf_flowers/flower_photos/dummy.txt
  tensorflow_datasets/testing/test_data/fake_examples/tf_flowers/flower_photos/roses/000001_rose.jpg
  tensorflow_datasets/testing/test_data/fake_examples/tf_flowers/flower_photos/sunflowers/000001_sunflower.jpg
  tensorflow_datasets/testing/test_data/fake_examples/tf_flowers/flower_photos/tulips/000001_tulip.jpg
Labels: cla: yes, kokoro:run

#1973 Fix temporary_assignment if an exception is raised.
  tensorflow_datasets/core/utils/py_utils.py
Labels: cla: no

#1970 Add nightly icon to the Table of Content
  tensorflow_datasets/scripts/document_datasets.py
Labels: cla: yes

#1863 Minor DOC update
  docs/beam_datasets.md
Labels: cla: yes

#1954 Improve GitHub workflow
  .github/ISSUE_TEMPLATE/documentation-issue.md
  .github/pull_request_template.md
  .gitignore
Labels: cla: yes, tfds:is_reviewing

#1930 Fix DIV2K Reference
  tensorflow_datasets/image/div2k.py
Labels: cla: yes, tfds:ready_to_merge

#1733 Update README
  README.md
  tensorflow_datasets/image_classification/mnist.py
Labels: cla: yes, tfds:needs_final_approval

#1912 Don't mock some os functions on windows
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: yes, tfds:ready_to_merge

#1913 Fix tfds/image_classification bugs on windows
  tensorflow_datasets/image_classification/beans.py
  tensorflow_datasets/image_classification/bigearthnet.py
  tensorflow_datasets/image_classification/caltech_birds.py
  tensorflow_datasets/image_classification/imagenet.py
  tensorflow_datasets/image_classification/imagenet2012_subset.py
  tensorflow_datasets/image_classification/imagewang.py
  tensorflow_datasets/image_classification/places365_small.py
  tensorflow_datasets/image_classification/sun.py
  tensorflow_datasets/image_classification/vgg_face2.py
  tensorflow_datasets/image_classification/visual_domain_decathlon.py
Labels: cla: yes, tfds:ready_to_merge

#1976 Fix hash key on windows when a path is used as hashkey
  tensorflow_datasets/core/hashing.py
  tensorflow_datasets/core/hashing_test.py
Labels: cla: no
