Repository tensorflow/datasets, pull requests merged in 2020-07, with the labels that each got.

#2140 Update the source code link on dataset Catalog
  tensorflow_datasets/scripts/documentation/templates/dataset.mako.md
Labels: cla: yes, community:please_review

#2142 CleanUp use tf.nest.map_structure
  tensorflow_datasets/core/decode/base.py
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/features/feature.py
  tensorflow_datasets/core/features/sequence_feature.py
  tensorflow_datasets/testing/dataset_builder_testing.py
  tensorflow_datasets/testing/test_utils.py
Labels: author:kokoro_test_failed, cla: yes

#2134 Add FUSS sound source separation dataset.
  tensorflow_datasets/audio/__init__.py
  tensorflow_datasets/audio/fuss.py
  tensorflow_datasets/audio/fuss_test.py
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/eval/example0000.jams
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/eval/example0000.txt
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/eval/example0000.wav
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/eval/example0000_sources/background0_sound.wav
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/eval_example_list.txt
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/train/example00000.jams
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/train/example00000.txt
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/train/example00000.wav
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/train/example00000_sources/background0_sound.wav
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/train/example00000_sources/foreground0_sound.wav
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/train/example00001.jams
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/train/example00001.txt
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/train/example00001.wav
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/train/example00001_sources/background0_sound.wav
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/train_example_list.txt
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/validation/example0000.jams
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/validation/example0000.txt
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/validation/example0000.wav
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/validation/example0000_sources/background0_sound.wav
  tensorflow_datasets/testing/test_data/fake_examples/fuss/ssdata_reverb/validation_example_list.txt
  tensorflow_datasets/url_checksums/fuss.txt
Labels: cla: no

#2154 Add back support for '-' in split names.
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/tfrecords_reader_test.py
Labels: cla: yes

#2168 Typo
  docs/add_dataset.md
Labels: cla: yes, community:please_review

#2169 Add VCTK speech dataset.
  tensorflow_datasets/audio/__init__.py
  tensorflow_datasets/audio/vctk.py
  tensorflow_datasets/audio/vctk_test.py
  tensorflow_datasets/testing/test_data/fake_examples/vctk/speaker-info.txt
  tensorflow_datasets/testing/test_data/fake_examples/vctk/txt/p229/p229_001.txt
  tensorflow_datasets/testing/test_data/fake_examples/vctk/wav48_silence_trimmed/p229/p229_001_mic1.flac
  tensorflow_datasets/testing/test_data/fake_examples/vctk/wav48_silence_trimmed/p229/p229_001_mic2.flac
  tensorflow_datasets/url_checksums/vctk.txt
Labels: cla: no

#2162 Pin numba version
  setup.py
Labels: cla: no

#2178 Fix typo in c4 comment.
  tensorflow_datasets/text/c4.py
Labels: cla: no

#2179 Update TFDS version to 4.0.0
  tensorflow_datasets/stable_versions.txt
  tensorflow_datasets/version.py
  tensorflow_datasets/version_stable.py
Labels: cla: no

#2148 update ucf101 video dataset weblink
  tensorflow_datasets/video/ucf101.py
Labels: author:kokoro_test_failed, cla: yes

#2180 Minor doc update: clarify TranslateFolder usage.
  tensorflow_datasets/core/custom_dataset/translate_folder.py
Labels: cla: no

#2163 Minor documentation fix
  tensorflow_datasets/scripts/documentation/templates/dataset.mako.md
  tensorflow_datasets/summarization/covid19sum.py
Labels: cla: no

#2104 Update waymo open dataset
  tensorflow_datasets/object_detection/waymo_open_dataset.py
  tensorflow_datasets/object_detection/waymo_open_dataset_test.py
Labels: cla: yes, community:is_reviewing

#2171 Add Imagenet-A to tfds
  tensorflow_datasets/image_classification/__init__.py
  tensorflow_datasets/image_classification/imagenet_a.py
  tensorflow_datasets/image_classification/imagenet_a_test.py
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_a/imagenet-a.tar/imagenet-a/README.txt
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_a/imagenet-a.tar/imagenet-a/n01580077/1.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_a/imagenet-a.tar/imagenet-a/n01580077/2.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_a/imagenet-a.tar/imagenet-a/n01616318/3.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_a/imagenet-a.tar/imagenet-a/n01616318/4.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_a/imagenet-a.tar/imagenet-a/n01616318/5.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_a/imagenet-a.tar/imagenet-a/n07697313/10.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_a/imagenet-a.tar/imagenet-a/n07697313/6.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_a/imagenet-a.tar/imagenet-a/n07697313/7.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_a/imagenet-a.tar/imagenet-a/n07697313/8.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_a/imagenet-a.tar/imagenet-a/n07697313/9.jpeg
  tensorflow_datasets/url_checksums/imagenet_a.txt
Labels: cla: no

#2177 Add ImageNetv2 to tfds
  tensorflow_datasets/image_classification/__init__.py
  tensorflow_datasets/image_classification/imagenet_v2.py
  tensorflow_datasets/image_classification/imagenet_v2_test.py
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/125/3.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/125/4.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/125/5.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency/125/3.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency/125/4.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency/125/5.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency/42/1.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency/42/2.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency/999/10.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency/999/6.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency/999/7.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency/999/8.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-matched-frequency/999/9.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7/125/3.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7/125/4.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7/125/5.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7/42/1.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7/42/2.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7/999/10.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7/999/6.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7/999/7.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7/999/8.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7/999/9.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-topimages/125/3.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-topimages/125/4.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-topimages/125/5.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-topimages/42/1.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-topimages/42/2.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-topimages/999/10.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-topimages/999/6.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-topimages/999/7.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-topimages/999/8.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-topimages/999/9.jpeg
  tensorflow_datasets/url_checksums/imagenet_v2.txt
Labels: cla: no

#2193 tf.io.gfile fails for gcs paths
  tensorflow_datasets/core/utils/gcs_utils.py
Labels: cla: yes, kokoro:run, tfds:ready_to_merge

#2197 Add the CLIC (Workshop and Challenge on Learned Image Compression 2020) dataset to TensorFlow Dataset.
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/clic.py
  tensorflow_datasets/image/clic_test.py
  tensorflow_datasets/testing/test_data/fake_examples/clic/test/1x1_test.png
  tensorflow_datasets/testing/test_data/fake_examples/clic/train/1x1_train.png
  tensorflow_datasets/testing/test_data/fake_examples/clic/valid/1x1_valid.png
  tensorflow_datasets/url_checksums/clic.txt
Labels: cla: no

#2195 Add GoEmotions Dataset to TFDS
  tensorflow_datasets/testing/test_data/fake_examples/goemotions/dev.tsv
  tensorflow_datasets/testing/test_data/fake_examples/goemotions/test.tsv
  tensorflow_datasets/testing/test_data/fake_examples/goemotions/train.tsv
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/goemotions.py
  tensorflow_datasets/text/goemotions_test.py
  tensorflow_datasets/url_checksums/goemotions.txt
Labels: cla: no

#2200 Refactor C4 deduplication to reduce memory usage. Instead of emitting lines to remove, emit lines to keep, which avoids needing to materialize the full list of URLs for a duplicated line in memory.
  tensorflow_datasets/text/c4.py
  tensorflow_datasets/text/c4_utils.py
  tensorflow_datasets/text/c4_utils_test.py
Labels: cla: no

#2203 Update CLIC 2020 URLs.
  tensorflow_datasets/image/clic.py
  tensorflow_datasets/url_checksums/clic.txt
Labels: cla: no

#2206 Fixes https://github.com/magenta/ddsp/issues/54
  tensorflow_datasets/audio/nsynth.py
Labels: cla: no

#2208 Minor ai2 cleanup
  tensorflow_datasets/question_answering/ai2_arc.py
Labels: cla: no

#2202 Modifying docstring of ReadConfig to clarify that `shuffle_seed` and `shuffle_reshuffle_each_iteration` are only used for file shuffling.
  tensorflow_datasets/core/utils/read_config.py
Labels: cla: no

#2209 rename MovieLens dataset handle to "movielens", deprecating "movie_lens".
  tensorflow_datasets/structured/__init__.py
  tensorflow_datasets/structured/movielens.py
  tensorflow_datasets/structured/movielens_parsing_test.py
  tensorflow_datasets/structured/movielens_test.py
  tensorflow_datasets/testing/test_data/fake_examples/movielens/ml-100k/u.data
  tensorflow_datasets/testing/test_data/fake_examples/movielens/ml-100k/u.item
  tensorflow_datasets/testing/test_data/fake_examples/movielens/ml-100k/u.user
  tensorflow_datasets/testing/test_data/fake_examples/movielens/ml-1m/movies.dat
  tensorflow_datasets/testing/test_data/fake_examples/movielens/ml-1m/ratings.dat
  tensorflow_datasets/testing/test_data/fake_examples/movielens/ml-1m/users.dat
  tensorflow_datasets/testing/test_data/fake_examples/movielens/ml-20m/movies.csv
  tensorflow_datasets/testing/test_data/fake_examples/movielens/ml-20m/ratings.csv
  tensorflow_datasets/testing/test_data/fake_examples/movielens/ml-25m/movies.csv
  tensorflow_datasets/testing/test_data/fake_examples/movielens/ml-25m/ratings.csv
  tensorflow_datasets/testing/test_data/fake_examples/movielens/ml-latest-small/movies.csv
  tensorflow_datasets/testing/test_data/fake_examples/movielens/ml-latest-small/ratings.csv
  tensorflow_datasets/url_checksums/movielens.txt
Labels: cla: no

#2205 Add COCO captions dataset using Karpathy and Li (2015) eval set splits.
  tensorflow_datasets/object_detection/__init__.py
  tensorflow_datasets/object_detection/coco_captions.py
  tensorflow_datasets/object_detection/coco_captions_test.py
  tensorflow_datasets/testing/test_data/fake_examples/coco/karpathy_and_li_splits/dataset_coco.json
  tensorflow_datasets/url_checksums/coco_captions.txt
Labels: cla: no

#2213 Minor cleanup of _is_gcs_disabled
  tensorflow_datasets/core/utils/gcs_utils.py
Labels: cla: no

#2207 Remove deprecated `build_dataset` code
  tensorflow_datasets/core/dataset_utils.py
  tensorflow_datasets/core/dataset_utils_test.py
Labels: cla: no

#2224 C4: filter empty pages after deduplication regardless of the min_num_sentences arg.
  tensorflow_datasets/text/c4_utils.py
Labels: cla: no

#2223 Update uc_merced Docstring
  tensorflow_datasets/image_classification/uc_merced.py
Labels: cla: yes, community:please_review

#2222 Set minimal supported Python version in setup.py
  setup.py
Labels: cla: yes, community:please_review

#2183 Update Citrus leaves Dataset
  tensorflow_datasets/image_classification/citrus.py
  tensorflow_datasets/url_checksums/citrus_leaves.txt
Labels: cla: yes, community:please_review, dataset request

#2144 Add overwrite flag in `generate_visualization`
  tensorflow_datasets/scripts/documentation/generate_visualization.py
Labels: author:kokoro_test_failed, cla: yes

#2225 Unpin numba as librosa 8.0 is released, fix kokoro failures
  oss_scripts/oss_tests.sh
  setup.py
Labels: cla: no

#2227 Fix typo in cytrus_leave label class
  tensorflow_datasets/image_classification/cbis_ddsm.py
  tensorflow_datasets/image_classification/cbis_ddsm_patch_labels.txt
Labels: cla: no

#2226 Add show_statistics to public API
  tensorflow_datasets/core/visualization/__init__.py
Labels: cla: no

#2229 Update plant_village download url
  tensorflow_datasets/image_classification/plant_village.py
  tensorflow_datasets/url_checksums/plant_village.txt
Labels: cla: yes, tfds:ready_to_merge

#2164 Add custom_datasets to public API
  tensorflow_datasets/core/folder_dataset/__init__.py
  tensorflow_datasets/core/folder_dataset/image_folder.py
  tensorflow_datasets/core/folder_dataset/image_folder_test.py
  tensorflow_datasets/core/folder_dataset/translate_folder.py
  tensorflow_datasets/core/folder_dataset/translate_folder_test.py
  tensorflow_datasets/public_api.py
Labels: cla: no

#2186 Use f-strings to generate dataset doc
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/scripts/documentation/dataset_markdown_builder.py
  tensorflow_datasets/scripts/documentation/document_datasets.py
  tensorflow_datasets/scripts/documentation/templates/dataset.mako.md
Labels: author:kokoro_test_failed, cla: yes

#2241 Mock sys.exit for CLI test
  tensorflow_datasets/scripts/cli/main_test.py
Labels: cla: no

#2218 Add an option for the ImageNet 2012 Challenge TEST split to TFDS.
  tensorflow_datasets/image_classification/imagenet.py
  tensorflow_datasets/image_classification/imagenet_test.py
  tensorflow_datasets/testing/test_data/fake_examples/imagenet2012/ILSVRC2012_img_test.tar
Labels: cla: no

#2238 Add a repr_html to FeatureConnector
  tensorflow_datasets/core/features/feature.py
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no

#2240 Add a get_base64 util
  tensorflow_datasets/core/utils/py_utils.py
Labels: cla: no

#2242 Add `__all__` to `__init__py2.py`.
  tensorflow_datasets/__init__py2.py
Labels: cla: no

#2236 Add HTML representation for images
  tensorflow_datasets/core/features/image_feature.py
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no

#2237 Add HTML representation for ClassLabel
  tensorflow_datasets/core/features/class_label_feature.py
Labels: cla: no

#2234 Add AG_News dataset
  tensorflow_datasets/testing/test_data/fake_examples/ag_news_subset/ag_news_csv/test.csv
  tensorflow_datasets/testing/test_data/fake_examples/ag_news_subset/ag_news_csv/train.csv
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/ag_news_subset.py
  tensorflow_datasets/text/ag_news_subset_test.py
  tensorflow_datasets/url_checksums/ag_news_subset.txt
Labels: cla: no

#2239 Add HTML representation for Text
  tensorflow_datasets/core/features/text_feature.py
Labels: cla: no

#2235 Add HTML representation for Audio
  tensorflow_datasets/core/features/audio_feature.py
Labels: cla: no

#2247 fix cased raw text string in bigpatent. Previous version 2.0.0 was not cased.
  setup.py
  tensorflow_datasets/summarization/big_patent.py
Labels: cla: no

#1611 More beginner friendly documentation
  CONTRIBUTING.md
Labels: cla: yes, community:please_review, documentation

#1621 Remove python 2 legacy from download_manager.py
  tensorflow_datasets/core/download/download_manager.py
Labels: author:please_resolve_conflict, cla: yes, py3-migration

#2250 Update visualization path for figures
  tensorflow_datasets/scripts/documentation/document_datasets.py
  tensorflow_datasets/scripts/documentation/generate_visualization.py
Labels: cla: no

#2246 Add PAWS_Wiki dataset
  tensorflow_datasets/testing/test_data/fake_examples/paws_wiki/final/dev.tsv
  tensorflow_datasets/testing/test_data/fake_examples/paws_wiki/final/test.tsv
  tensorflow_datasets/testing/test_data/fake_examples/paws_wiki/final/train.tsv
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/paws_wiki.py
  tensorflow_datasets/text/paws_wiki_test.py
  tensorflow_datasets/url_checksums/paws_wiki.txt
Labels: cla: no

#2249 Start adding pytype annotations
  tensorflow_datasets/core/registered.py
  tensorflow_datasets/core/utils/type_utils.py
Labels: cla: no

#2254 Add `tfds new` CLI to the public API
  setup.py
Labels: cla: no

#2248 Add a resource_path util, cleanup importlib_resource
  setup.py
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/scripts/cli/new.py
  tensorflow_datasets/summarization/big_patent.py
Labels: cla: no

#2230 Add genomics_ood dataset to TFDS
  tensorflow_datasets/structured/__init__.py
  tensorflow_datasets/structured/genomics_ood.py
  tensorflow_datasets/structured/genomics_ood_test.py
  tensorflow_datasets/testing/test_data/fake_examples/genomics_ood/genomics_ood.zip
Labels: cla: no
