Repository tensorflow/datasets, pull requests merged in 2020-11, with the labels that each got.

#2671 Minor beam dataset doc cleanup
  docs/beam_datasets.md
Labels: cla: no

#2672 Update `tfds new` to new the `_split_generators` API
  tensorflow_datasets/scripts/cli/new.py
Labels: cla: no

#2674 Pin fastavro version
  setup.py
Labels: cla: no

#2679 Fix False error when using default plain text encoder config.
  tensorflow_datasets/core/features/text_feature.py
Labels: cla: no

#2675 Add manual download instruction to doc
  docs/overview.ipynb
Labels: cla: no

#2677 Update TFDS to v4.1.0
  tensorflow_datasets/stable_versions.txt
  tensorflow_datasets/version.py
  tensorflow_datasets/version_stable.py
Labels: cla: no

#2684 Update GCS doc
  docs/gcs.md
Labels: cla: no

#2685 Update `tfds new` to auto-update the `__init__.py` file
  tensorflow_datasets/scripts/cli/new.py
Labels: cla: no

#2688 Unpin fastavro
  setup.py
Labels: cla: no

#2670 Make DownloadManager uses Path-like objects
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/download_manager_test.py
  tensorflow_datasets/core/download/downloader.py
  tensorflow_datasets/core/download/extractor.py
  tensorflow_datasets/core/download/extractor_test.py
  tensorflow_datasets/core/download/kaggle.py
  tensorflow_datasets/core/download/kaggle_test.py
  tensorflow_datasets/core/download/resource.py
  tensorflow_datasets/core/tf_compat.py
  tensorflow_datasets/core/utils/gpath.py
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/question_answering/cosmos_qa.py
  tensorflow_datasets/question_answering/natural_questions.py
  tensorflow_datasets/testing/dataset_builder_testing.py
  tensorflow_datasets/text/bool_q/bool_q.py
  tensorflow_datasets/translate/wmt.py
  tensorflow_datasets/video/starcraft.py
Labels: cla: no

#2682 Clarify FeatureConnector types in documentation
  docs/features.md
Labels: cla: no

#2691 Add 2016 version of Story cloze dataset.
  tensorflow_datasets/text/story_cloze/dummy_data/cloze_test_test__spring2016.csv
  tensorflow_datasets/text/story_cloze/dummy_data/cloze_test_val__spring2016.csv
  tensorflow_datasets/text/story_cloze/story_cloze.py
  tensorflow_datasets/text/story_cloze/story_cloze_test.py
Labels: cla: no

#2689 Fix non public link in the description.
  tensorflow_datasets/structured/wiki_bio.py
Labels: cla: no

#2690 Update documentation to use pathlib
  docs/add_dataset.md
  docs/beam_datasets.md
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#2687 Remove deprecated BuilderConfig using text encoder
  tensorflow_datasets/audio/__init__.py
  tensorflow_datasets/audio/librispeech.py
  tensorflow_datasets/audio/librispeech_test.py
  tensorflow_datasets/structured/rock_you.py
  tensorflow_datasets/summarization/__init__.py
  tensorflow_datasets/summarization/cnn_dailymail.py
  tensorflow_datasets/testing/mocking_test.py
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/lm1b.py
  tensorflow_datasets/text/multi_nli.py
  tensorflow_datasets/text/multi_nli_mismatch.py
  tensorflow_datasets/text/yelp_polarity.py
  tensorflow_datasets/translate/flores.py
  tensorflow_datasets/translate/para_crawl.py
  tensorflow_datasets/translate/para_crawl_test.py
  tensorflow_datasets/translate/wmt.py
  tensorflow_datasets/translate/wmt15.py
Labels: cla: no

#2693 `Version(v)` works when v is a version
  tensorflow_datasets/core/utils/version.py
  tensorflow_datasets/core/utils/version_test.py
Labels: cla: no

#2667 Optional Builder version
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_test.py
Labels: cla: yes, community:please_review

#2694 Update doc for easier `@dataclasses` based config definition
  docs/add_dataset.md
Labels: cla: no

#2697 Restore `config.description` for read-only-builder
  tensorflow_datasets/core/read_only_builder.py
Labels: cla: no

#2698 Add release notes to documentation
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/scripts/documentation/dataset_markdown_builder.py
Labels: cla: no

#2699 Avoid pickling full SplitBuilder class when running on beam.
  tensorflow_datasets/core/split_builder.py
Labels: cla: no

#2702 Mock gfile in download manager for TF < 2.4
  tensorflow_datasets/text/c4.py
Labels: cla: no

#2703 Fix catalog generation
  tensorflow_datasets/image_classification/cifar10_corrupted.py
  tensorflow_datasets/scripts/documentation/document_datasets.py
Labels: cla: no

#2705 Internal
  tensorflow_datasets/image/cityscapes_test.py
Labels: cla: no

#2704 Cleanup TF logs in generated doc
  docs/cli.ipynb
Labels: cla: no

#2695 Remove deprecated version field
  docs/add_dataset.md
  tensorflow_datasets/core/utils/version.py
  tensorflow_datasets/image_classification/colorectal_histology.py
  tensorflow_datasets/image_classification/mnist.py
  tensorflow_datasets/scripts/cli/new.py
  tensorflow_datasets/text/story_cloze/story_cloze.py
Labels: cla: no

#2598 Add Web NLG dataset
  tensorflow_datasets/structured/__init__.py
  tensorflow_datasets/structured/web_nlg/__init__.py
  tensorflow_datasets/structured/web_nlg/checksums.tsv
  tensorflow_datasets/structured/web_nlg/dummy_data/webnlg-dataset-master/webnlg_challenge_2017/dev/1triples/one_category.xml
  tensorflow_datasets/structured/web_nlg/dummy_data/webnlg-dataset-master/webnlg_challenge_2017/dev/2triples/other_category.xml
  tensorflow_datasets/structured/web_nlg/dummy_data/webnlg-dataset-master/webnlg_challenge_2017/test/testdata_unseen_with_lex.xml
  tensorflow_datasets/structured/web_nlg/dummy_data/webnlg-dataset-master/webnlg_challenge_2017/test/testdata_with_lex.xml
  tensorflow_datasets/structured/web_nlg/dummy_data/webnlg-dataset-master/webnlg_challenge_2017/train/2triples/other_category.xml
  tensorflow_datasets/structured/web_nlg/dummy_data/webnlg-dataset-master/webnlg_challenge_2017/train/2triples/yet_other_category.xml
  tensorflow_datasets/structured/web_nlg/dummy_data/webnlg-dataset-master/webnlg_challenge_2017/train/2triples/yet_other_category.xmltrain/1triples/one_category.xml
  tensorflow_datasets/structured/web_nlg/web_nlg.py
  tensorflow_datasets/structured/web_nlg/web_nlg_test.py
Labels: cla: no

#2707 Better TF 2.3 compatibility for pathlike
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/downloader.py
  tensorflow_datasets/core/download/extractor.py
  tensorflow_datasets/core/download/resource.py
  tensorflow_datasets/text/c4.py
Labels: cla: no

#2681 Adding machine translations provided by XTREME to the XNLI dataset.
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/xtreme_xnli/__init__.py
  tensorflow_datasets/text/xtreme_xnli/checksums.tsv
  tensorflow_datasets/text/xtreme_xnli/dummy_data/en-ar.translated.tsv
  tensorflow_datasets/text/xtreme_xnli/dummy_data/en-bg.translated.tsv
  tensorflow_datasets/text/xtreme_xnli/dummy_data/en-de.translated.tsv
  tensorflow_datasets/text/xtreme_xnli/dummy_data/en-el.translated.tsv
  tensorflow_datasets/text/xtreme_xnli/dummy_data/en-es.translated.tsv
  tensorflow_datasets/text/xtreme_xnli/dummy_data/en-fr.translated.tsv
  tensorflow_datasets/text/xtreme_xnli/dummy_data/en-hi.translated.tsv
  tensorflow_datasets/text/xtreme_xnli/dummy_data/en-ru.translated.tsv
  tensorflow_datasets/text/xtreme_xnli/dummy_data/en-sw.translated.tsv
  tensorflow_datasets/text/xtreme_xnli/dummy_data/en-th.translated.tsv
  tensorflow_datasets/text/xtreme_xnli/dummy_data/en-tr.translated.tsv
  tensorflow_datasets/text/xtreme_xnli/dummy_data/en-ur.translated.tsv
  tensorflow_datasets/text/xtreme_xnli/dummy_data/en-vi.translated.tsv
  tensorflow_datasets/text/xtreme_xnli/dummy_data/en-zh.translated.tsv
  tensorflow_datasets/text/xtreme_xnli/xtreme_xnli.py
  tensorflow_datasets/text/xtreme_xnli/xtreme_xnli_test.py
Labels: cla: no

#2710 Better log message when duplicated examples
  tensorflow_datasets/core/tfrecords_writer.py
  tensorflow_datasets/core/tfrecords_writer_test.py
Labels: cla: no

#2713 Fix colab doc generation by making %%capture be the first instruction
  docs/cli.ipynb
Labels: cla: no

#2709 Better error message if bad _info return type.
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#2712 Better manual instructions for ddsm
  tensorflow_datasets/image_classification/cbis_ddsm.py
Labels: cla: no

#2715 Add arxiv links for fuss papers now that they are public.
  tensorflow_datasets/audio/fuss.py
Labels: cla: no

#2708 Fix the QuAC error
  tensorflow_datasets/text/quac/quac.py
  tensorflow_datasets/text/quac/quac_test.py
Labels: cla: no

#2701 Add WSC273 dataset (first 273 questions from Winograd Schema Challenge) to TFDS.
  setup.py
  tensorflow_datasets/core/lazy_imports_lib.py
  tensorflow_datasets/core/lazy_imports_lib_test.py
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/wsc273/__init__.py
  tensorflow_datasets/text/wsc273/checksums.tsv
  tensorflow_datasets/text/wsc273/dummy_data/wsc273.xml
  tensorflow_datasets/text/wsc273/wsc273.py
  tensorflow_datasets/text/wsc273/wsc273_test.py
Labels: cla: no

#2718 Test builder config declared as dataclasses
  docs/add_dataset.md
  tensorflow_datasets/core/dataset_builder_test.py
Labels: cla: no

#2720 Add `--overwrite` flag to `tfds build`
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/utils/gpath.py
  tensorflow_datasets/core/utils/type_utils.py
  tensorflow_datasets/scripts/cli/build.py
  tensorflow_datasets/scripts/cli/build_test.py
Labels: cla: no

#2719 Add `builder/config:1.0.0` support to tfds build
  tensorflow_datasets/core/load.py
  tensorflow_datasets/scripts/cli/build.py
  tensorflow_datasets/scripts/cli/build_test.py
Labels: cla: no

#2724 Adding XTREME translations of the PAWS dataset.
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/xtreme_pawsx/__init__.py
  tensorflow_datasets/text/xtreme_pawsx/checksums.tsv
  tensorflow_datasets/text/xtreme_pawsx/dummy_data/en-de.translated.tsv
  tensorflow_datasets/text/xtreme_pawsx/dummy_data/en-es.translated.tsv
  tensorflow_datasets/text/xtreme_pawsx/dummy_data/en-fr.translated.tsv
  tensorflow_datasets/text/xtreme_pawsx/dummy_data/en-ja.translated.tsv
  tensorflow_datasets/text/xtreme_pawsx/dummy_data/en-ko.translated.tsv
  tensorflow_datasets/text/xtreme_pawsx/dummy_data/en-zh.translated.tsv
  tensorflow_datasets/text/xtreme_pawsx/xtreme_pawsx.py
  tensorflow_datasets/text/xtreme_pawsx/xtreme_pawsx_test.py
Labels: cla: no

#2683 Add SI-Score synthetic dataset to TFDS.
  tensorflow_datasets/image_classification/__init__.py
  tensorflow_datasets/image_classification/siscore/__init__.py
  tensorflow_datasets/image_classification/siscore/checksums.tsv
  tensorflow_datasets/image_classification/siscore/dummy_data/area/bagel/5.jpg
  tensorflow_datasets/image_classification/siscore/dummy_data/area/bagel/6.jpg
  tensorflow_datasets/image_classification/siscore/dummy_data/location20_area02_min0pc/bagel/1.jpg
  tensorflow_datasets/image_classification/siscore/dummy_data/location20_area02_min0pc/saxophone/2.jpg
  tensorflow_datasets/image_classification/siscore/dummy_data/rotation/toaster/3.jpg
  tensorflow_datasets/image_classification/siscore/dummy_data/rotation/toaster/4.jpg
  tensorflow_datasets/image_classification/siscore/siscore.py
  tensorflow_datasets/image_classification/siscore/siscore_labels.py
  tensorflow_datasets/image_classification/siscore/siscore_test.py
Labels: cla: no

#2722 Update doc to use `tfds build`
  docs/add_dataset.md
  docs/beam_datasets.md
Labels: cla: no

#2725 Fix `--register_checksums` when url already downloaded
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/download_manager_test.py
Labels: cla: no

#2721 `tfds build`: Add support for direct paths
  tensorflow_datasets/core/__init__.py
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/scripts/cli/build.py
  tensorflow_datasets/scripts/cli/build_test.py
Labels: cla: no

#2723 Add `tfds build` doc
  docs/cli.ipynb
  docs/overview.ipynb
Labels: cla: no

#2729 Cleanup debug message
  tensorflow_datasets/image_classification/siscore/siscore.py
Labels: cla: no

#2726 Add `--imports` flag to `tfds build`
  tensorflow_datasets/scripts/cli/build.py
  tensorflow_datasets/scripts/cli/build_test.py
Labels: cla: no

#2727 Change tfds.core.benchmark to return pd.Dataframe for better analysis on the tf.data.Dataset benchmark statistics.
  tensorflow_datasets/core/utils/benchmark.py
Labels: cla: no

#2731 Add demographic data from Kalahari !Kung San, collected by Nancy Howell.
  tensorflow_datasets/structured/__init__.py
  tensorflow_datasets/structured/howell/__init__.py
  tensorflow_datasets/structured/howell/checksums.tsv
  tensorflow_datasets/structured/howell/dummy_data/howell.csv
  tensorflow_datasets/structured/howell/howell.py
  tensorflow_datasets/structured/howell/howell_test.py
Labels: cla: no

#2738 Make BuilderConfig description optional
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#2736 Add backticks to docstring
  tensorflow_datasets/core/load.py
Labels: cla: yes, tfds:ready_to_merge

#2737 Add RACE data into TFDS
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/race/__init__.py
  tensorflow_datasets/text/race/checksums.tsv
  tensorflow_datasets/text/race/dummy_data/RACE/dev/high/145.txt
  tensorflow_datasets/text/race/dummy_data/RACE/dev/middle/156.txt
  tensorflow_datasets/text/race/dummy_data/RACE/test/high/190.txt
  tensorflow_datasets/text/race/dummy_data/RACE/test/middle/901.txt
  tensorflow_datasets/text/race/dummy_data/RACE/train/high/12.txt
  tensorflow_datasets/text/race/dummy_data/RACE/train/middle/123.txt
  tensorflow_datasets/text/race/race.py
  tensorflow_datasets/text/race/race_test.py
Labels: cla: no

#2741 Minor docstring fix for FileReaderBuilder
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#2746 Add tfds.testing.MockPolicy to public API.
  tensorflow_datasets/testing/__init__.py
Labels: cla: no

#2739 Test that config description is different from info description
  tensorflow_datasets/audio/tedlium.py
  tensorflow_datasets/image_classification/cycle_gan.py
  tensorflow_datasets/image_classification/imagenet_resized.py
  tensorflow_datasets/image_classification/imagenet_v2.py
  tensorflow_datasets/object_detection/coco.py
  tensorflow_datasets/object_detection/voc.py
  tensorflow_datasets/testing/dataset_builder_testing.py
  tensorflow_datasets/text/blimp.py
  tensorflow_datasets/text/cfq.py
  tensorflow_datasets/text/gpt3.py
  tensorflow_datasets/text/math_dataset.py
  tensorflow_datasets/text/qa4mre.py
  tensorflow_datasets/text/scan.py
  tensorflow_datasets/text/super_glue.py
  tensorflow_datasets/translate/opus.py
Labels: cla: no

#2747 Update documentation to debug checksums
  docs/overview.ipynb
Labels: cla: no

#2743 Update write_info_files to accept url
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/resource.py
Labels: cla: no

#2750 Adding try_gcs to tfds.builder so that datasets can be loaded from GCS when using the tfds.builder API (not just tfds.load).
  tensorflow_datasets/core/load.py
Labels: cla: no

#2744 Update downloader to return path to destination
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/download_manager_test.py
  tensorflow_datasets/core/download/downloader.py
  tensorflow_datasets/core/download/downloader_test.py
Labels: cla: no

#2749 Update dl_manager.download
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/download_manager_test.py
  tensorflow_datasets/core/utils/type_utils.py
Labels: cla: no

#2740 #EXPERIMENTAL Add support to read/write Riegeli record files.
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/file_adapters.py
  tensorflow_datasets/core/file_adapters_test.py
  tensorflow_datasets/core/load.py
  tensorflow_datasets/core/load_test.py
  tensorflow_datasets/core/split_builder.py
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/tfrecords_reader_test.py
  tensorflow_datasets/core/tfrecords_writer.py
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/core/utils/py_utils_test.py
Labels: cla: no

#2751 Remove Pathlib.Path when writing examples.
  tensorflow_datasets/core/tfrecords_writer.py
Labels: cla: no

#2732 Fix dynamic import for open source tests
  tensorflow_datasets/scripts/cli/build_test.py
  tensorflow_datasets/testing/dummy_dataset/dummy_dataset_test.py
Labels: cla: no

#2728 Update download_and_prepare to use build new
  tensorflow_datasets/scripts/download_and_prepare.py
Labels: cla: no

#2752 Improve doc for manual_dir
  docs/add_dataset.md
Labels: cla: no

#2753 Cleanup beam setup in tests
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: no

#2734 [C4] Automatically download "manual" wet files.
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/testing/dataset_builder_testing.py
  tensorflow_datasets/testing/test_data/fake_examples/c4/c4_wet_files/cc_0.warc.wet
  tensorflow_datasets/testing/test_data/fake_examples/c4/c4_wet_files/cc_0.warc.wet.gz
  tensorflow_datasets/testing/test_data/fake_examples/c4/c4_wet_files/cc_1.warc.wet
  tensorflow_datasets/testing/test_data/fake_examples/c4/c4_wet_files/cc_1.warc.wet.gz
  tensorflow_datasets/text/c4.py
  tensorflow_datasets/text/c4_test.py
  tensorflow_datasets/text/c4_utils_test.py
Labels: cla: no

#2756 Fix non-deterministic pytest import conflict
  tensorflow_datasets/testing/dummy_dataset/dummy_dataset_test.py
Labels: cla: no

#2757 Correctly raise error if no version is defined
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#2755 Add DROP dataset into the TFDS
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/drop/__init__.py
  tensorflow_datasets/text/drop/checksums.tsv
  tensorflow_datasets/text/drop/drop.py
  tensorflow_datasets/text/drop/drop_test.py
  tensorflow_datasets/text/drop/dummy_data/drop_dataset_dev.json
  tensorflow_datasets/text/drop/dummy_data/drop_dataset_train.json
  tensorflow_datasets/text/quac/quac.py
Labels: cla: no

#2766 Add s3:// support to gpath
  tensorflow_datasets/core/utils/gpath.py
  tensorflow_datasets/core/utils/gpath_test.py
Labels: cla: no

#2767 Add tl;dr; command to the dataset guide
  docs/add_dataset.md
Labels: cla: no

#2759 Add historical phenological data for cherry tree flowering at Kyoto City.
  tensorflow_datasets/structured/__init__.py
  tensorflow_datasets/structured/cherry_blossoms/__init__.py
  tensorflow_datasets/structured/cherry_blossoms/checksums.tsv
  tensorflow_datasets/structured/cherry_blossoms/cherry_blossoms.py
  tensorflow_datasets/structured/cherry_blossoms/cherry_blossoms_test.py
  tensorflow_datasets/structured/cherry_blossoms/dummy_data/cherry_blossoms.csv
Labels: cla: no

#2764 Fix the drop dataset path
  tensorflow_datasets/text/drop/drop.py
  tensorflow_datasets/text/drop/dummy_data/drop_dataset/drop_dataset_dev.json
  tensorflow_datasets/text/drop/dummy_data/drop_dataset/drop_dataset_train.json
Labels: cla: no

#2700 Add WIKITABLETEXT dataset
  tensorflow_datasets/structured/__init__.py
  tensorflow_datasets/structured/wiki_table_text/__init__.py
  tensorflow_datasets/structured/wiki_table_text/checksums.tsv
  tensorflow_datasets/structured/wiki_table_text/dummy_data/MSRA_NLC.Table2Text.dev
  tensorflow_datasets/structured/wiki_table_text/dummy_data/MSRA_NLC.Table2Text.test
  tensorflow_datasets/structured/wiki_table_text/dummy_data/MSRA_NLC.Table2Text.train
  tensorflow_datasets/structured/wiki_table_text/wiki_table_text.py
  tensorflow_datasets/structured/wiki_table_text/wiki_table_text_test.py
Labels: cla: no

#2768 Update `as_path` to bu compatible with `s3://` on windows
  tensorflow_datasets/core/utils/generic_path.py
  tensorflow_datasets/core/utils/generic_path_test.py
  tensorflow_datasets/core/utils/gpath.py
Labels: cla: no

#2773 Update CLI for explicit FLAGS --argparse=false compatibility
  tensorflow_datasets/scripts/cli/main.py
  tensorflow_datasets/scripts/cli/main_test.py
Labels: cla: no

#2771 Adjust on the output of the RACE dataset
  tensorflow_datasets/text/race/race.py
  tensorflow_datasets/text/race/race_test.py
Labels: cla: no

#2770 Check if the "validated_answers" exist
  tensorflow_datasets/text/drop/drop.py
Labels: cla: no

#2775 Add a minimal tfds.testing.DummyDataset (single split, no image encoding,...)
  tensorflow_datasets/testing/__init__.py
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no

#2776 Use single-quote in load.py
  tensorflow_datasets/core/load.py
Labels: cla: no

#2777 Add imported_list_builder and imported_builder_cls
  tensorflow_datasets/core/load.py
  tensorflow_datasets/core/read_only_builder_test.py
  tensorflow_datasets/core/registered.py
  tensorflow_datasets/core/registered_test.py
  tensorflow_datasets/scripts/cli/build_test.py
Labels: cla: no

#2778 Update iter_full_name to use list_builder
  tensorflow_datasets/core/load.py
Labels: cla: no

#2785 Fix `is_example_file`
  tensorflow_datasets/core/file_adapters.py
  tensorflow_datasets/core/file_adapters_test.py
  tensorflow_datasets/core/utils/py_utils.py
Labels: cla: no

#2787 Fix catalog generation when config description is missing.
  tensorflow_datasets/scripts/documentation/dataset_markdown_builder.py
  tensorflow_datasets/scripts/documentation/document_datasets_test.py
Labels: cla: no

#2779 Add name parsing support for namespace (e.g. `kaggle:mnist:1.0.0`)
  tensorflow_datasets/core/load.py
  tensorflow_datasets/core/load_test.py
  tensorflow_datasets/core/naming.py
  tensorflow_datasets/core/naming_test.py
  tensorflow_datasets/scripts/cli/build.py
Labels: cla: no

#2781 Add read_only_builder.builder_from_files
  tensorflow_datasets/core/load.py
  tensorflow_datasets/core/load_test.py
  tensorflow_datasets/core/read_only_builder.py
  tensorflow_datasets/core/read_only_builder_test.py
Labels: cla: no

#2782 Add community register class to load externally defined datasets
  tensorflow_datasets/core/community/register_base.py
  tensorflow_datasets/core/community/register_path.py
  tensorflow_datasets/core/community/register_path_test.py
Labels: cla: no

#2783 Internal
  tensorflow_datasets/core/load.py
Labels: cla: no

#2772 Update beam doc to use tfds build CLI
  docs/beam_datasets.md
  docs/cli.ipynb
Labels: cla: no

#2774 Better debug message when encoding fails on one example
  tensorflow_datasets/core/features/feature.py
  tensorflow_datasets/core/split_builder.py
Labels: cla: no

#2788 Fix tfds.as_dataframe decoding issues
  tensorflow_datasets/core/as_dataframe.py
  tensorflow_datasets/core/as_dataframe_test.py
  tensorflow_datasets/core/features/text_feature.py
Labels: cla: no

#2789 Fix the bug
  tensorflow_datasets/text/drop/drop.py
  tensorflow_datasets/text/race/race.py
Labels: cla: no

#2790 Minor debug message improvement
  tensorflow_datasets/core/features/feature.py
Labels: cla: no

#2802 Spelling typo correction
  docs/add_dataset.md
Labels: cla: no

#2803 Better error message for iter_archive
  tensorflow_datasets/core/download/extractor.py
  tensorflow_datasets/text/wikipedia.py
Labels: cla: no
