Repository tensorflow/datasets, pull requests merged in 2020-02, with the labels that each got.

#1445 Fixing moving-mnist that was broken after S3 migration.
  tensorflow_datasets/video/moving_mnist.py
Labels: cla: no

#1448 Remove deprecated documentation
  docs/splits.md
Labels: cla: no

#1447 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/beans.md
  docs/catalog/big_patent.md
  docs/catalog/cfq.md
  docs/catalog/div2k.md
  docs/catalog/eraser_multi_rc.md
  docs/catalog/imagewang.md
  docs/catalog/natural_questions.md
  docs/catalog/overview.md
  docs/catalog/qa4mre.md
  docs/catalog/wmt15_translate.md
  tensorflow_datasets/testing/metadata/beans/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/beans/0.1.0/image.image.json
  tensorflow_datasets/testing/metadata/beans/0.1.0/label.labels.txt
  tensorflow_datasets/testing/metadata/big_patent/a/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/big_patent/all/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/big_patent/b/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/big_patent/c/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/big_patent/d/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/big_patent/e/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/big_patent/f/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/big_patent/g/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/big_patent/h/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/big_patent/y/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/cfq/mcd1/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/cfq/mcd2/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/cfq/mcd3/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/cfq/query_complexity_split/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/cfq/query_pattern_split/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/cfq/question_complexity_split/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/cfq/question_pattern_split/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/cfq/random_split/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/eraser_multi_rc/0.1.1/dataset_info.json
  tensorflow_datasets/testing/metadata/eraser_multi_rc/0.1.1/label.labels.txt
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#1443 Fix wrong Kitti url on windows
  tensorflow_datasets/object_detection/kitti.py
Labels: cla: no

#1450 Add token features to Natural Questions.
  tensorflow_datasets/text/natural_questions.py
Labels: cla: no

#1453 Update Common Crawl data-set to allow disabling of is_language filtering step by passing in no language argument. Enable user to do language-detection on their end.
  tensorflow_datasets/text/c4.py
Labels: cla: no

#1457 Update doc about subsplits
  docs/add_dataset.md
  docs/splits.md
Labels: cla: no

#1454 Automated documentation update
  docs/catalog/beans.md
  docs/catalog/cfq.md
  docs/catalog/imagewang.md
  docs/catalog/moving_mnist.md
  docs/catalog/natural_questions.md
  docs/catalog/qa4mre.md
  tensorflow_datasets/testing/metadata/imagewang/160px/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/imagewang/160px/2.0.0/image.image.json
  tensorflow_datasets/testing/metadata/imagewang/160px/2.0.0/label.labels.txt
  tensorflow_datasets/testing/metadata/imagewang/320px/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/imagewang/320px/2.0.0/image.image.json
  tensorflow_datasets/testing/metadata/imagewang/320px/2.0.0/label.labels.txt
  tensorflow_datasets/testing/metadata/imagewang/full-size/2.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/imagewang/full-size/2.0.0/image.image.json
  tensorflow_datasets/testing/metadata/imagewang/full-size/2.0.0/label.labels.txt
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/moving_mnist/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/moving_mnist/1.0.0/image_sequence.image.json
  tensorflow_datasets/testing/metadata/natural_questions/0.0.2/annotations-yes_no_answer.labels.txt
  tensorflow_datasets/testing/metadata/natural_questions/0.0.2/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2011.main.DE/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2011.main.EN/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2011.main.ES/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2011.main.IT/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2011.main.RO/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2012.alzheimers.EN/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2012.main.AR/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2012.main.BG/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2012.main.DE/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2012.main.EN/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2012.main.ES/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2012.main.IT/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2012.main.RO/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2013.alzheimers.EN/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2013.entrance_exam.EN/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2013.main.AR/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2013.main.BG/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2013.main.EN/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2013.main.ES/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/qa4mre/2013.main.RO/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#1394 Add Tiny Shakespeare dataset
  tensorflow_datasets/testing/test_data/fake_examples/tiny_shakespeare/input.txt
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/tiny_shakespeare.py
  tensorflow_datasets/text/tiny_shakespeare_test.py
  tensorflow_datasets/url_checksums/tiny_shakespeare.txt
Labels: cla: no

#1459 Add parallel decoding during ds.map
  tensorflow_datasets/core/tfrecords_reader.py
Labels: cla: no

#1464 Deprecate `in_memory` feature.
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#1463 Fix description markdown for tiny_shakespeare
  tensorflow_datasets/text/tiny_shakespeare.py
Labels: cla: no

#1451 Add bibtext to documentation for users to cite TFDS.
  README.md
  docs/_index.yaml
  docs/overview.ipynb
Labels: cla: no

#1460 Automated documentation update
  docs/catalog/natural_questions.md
  docs/catalog/trivia_qa.md
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/supported.txt
  tensorflow_datasets/testing/metadata/trivia_qa/rc.nocontext/1.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/trivia_qa/rc/1.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/trivia_qa/unfiltered.nocontext/1.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/trivia_qa/unfiltered/1.1.0/dataset_info.json
Labels: bug, cla: no

#1465 Update dataset info size.
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/dataset_info_test.py
  tensorflow_datasets/core/units.py
  tensorflow_datasets/core/units_test.py
  tensorflow_datasets/scripts/templates/dataset.mako.md
Labels: cla: no

#1466 Add support for Food101 V1.0.0.
  tensorflow_datasets/image/food101.py
Labels: cla: no

#1467 Auto-cache small datasets
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/utils/read_config.py
Labels: cla: no

#1469 Fix wrong Version argument for Lsun, accidentally passed as positional
  tensorflow_datasets/core/utils/version.py
  tensorflow_datasets/image/lsun.py
Labels: cla: no

#1474 Fix bug in error message formatting for missing checksum.
  tensorflow_datasets/core/download/checksums.py
Labels: cla: no

#1470 Update dataset documentation template
  tensorflow_datasets/scripts/document_datasets_test.py
  tensorflow_datasets/scripts/templates/dataset.mako.md
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no

#1480 Fix typo of download size not saved correctly
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#1478 Expose auto-cache default value to the documentation
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/scripts/document_datasets_test.py
  tensorflow_datasets/scripts/templates/dataset.mako.md
Labels: cla: no

#1471 Add performance tips section to the doc
  docs/_book.yaml
  docs/performances.md
Labels: cla: no

#1475 Expose tf.data.Dataset cardinality in TFDS
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/tfrecords_reader_test.py
Labels: cla: no

#1481 Increment c4 version
  tensorflow_datasets/text/c4.py
Labels: cla: no

#1485 Fix '\' warning when importing tfds
  tensorflow_datasets/text/qa4mre.py
Labels: cla: no

#1487 Update dead API doc links
  README.md
  docs/add_dataset.md
Labels: cla: no

#1252 Adding the Opinosis dataset
  docs/release_notes.md
  tensorflow_datasets/summarization/__init__.py
  tensorflow_datasets/summarization/opinosis.py
  tensorflow_datasets/summarization/opinosis_test.py
  tensorflow_datasets/testing/test_data/fake_examples/opinosis/summaries-gold/topic1/topic1.1.gold
  tensorflow_datasets/testing/test_data/fake_examples/opinosis/summaries-gold/topic1/topic1.2.gold
  tensorflow_datasets/testing/test_data/fake_examples/opinosis/summaries-gold/topic2/topic2.1.gold
  tensorflow_datasets/testing/test_data/fake_examples/opinosis/summaries-gold/topic2/topic2.2.gold
  tensorflow_datasets/testing/test_data/fake_examples/opinosis/summaries-gold/topic2/topic2.3.gold
  tensorflow_datasets/testing/test_data/fake_examples/opinosis/topics/topic1.txt.data
  tensorflow_datasets/testing/test_data/fake_examples/opinosis/topics/topic2.txt.data
  tensorflow_datasets/url_checksums/opinosis.txt
Labels: almost_ready_to_merge, cla: yes, dataset request, tfds:ready_to_merge

#1486 Fix wrong auto-cache documentation value when splits info are missing
  tensorflow_datasets/scripts/templates/dataset.mako.md
Labels: cla: no

#1491 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/beans.md
  docs/catalog/c4.md
  docs/catalog/opinosis.md
  docs/catalog/overview.md
  docs/catalog/qa4mre.md
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/opinosis/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#1488 Create working librispeech tfds config, parallelizing example creation using beam.
  tensorflow_datasets/audio/librispeech.py
  tensorflow_datasets/audio/librispeech_test.py
  tensorflow_datasets/url_checksums/librispeech.txt
Labels: cla: no

#1492 Add librispeech_lm text corpus, a companion to the speech+text librispeech corpus.
  tensorflow_datasets/testing/test_data/fake_examples/librispeech_lm/librispeech-lm-norm.txt.gz
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/librispeech_lm.py
  tensorflow_datasets/text/librispeech_lm_test.py
  tensorflow_datasets/url_checksums/librispeech_lm.txt
Labels: cla: no

#1493 Expose sample_rate (in Hertz) metadata to audio datasets.
  tensorflow_datasets/audio/librispeech.py
  tensorflow_datasets/audio/nsynth.py
  tensorflow_datasets/core/dataset_info.py
Labels: cla: no

#1495 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/beans.md
  docs/catalog/c4.md
  docs/catalog/cityscapes.md
  docs/catalog/cnn_dailymail.md
  docs/catalog/image_label_folder.md
  docs/catalog/librispeech.md
  docs/catalog/librispeech_lm.md
  docs/catalog/opinosis.md
  docs/catalog/overview.md
  docs/catalog/qa4mre.md
  docs/catalog/so2sat.md
  docs/catalog/wmt18_translate.md
  tensorflow_datasets/testing/metadata/missing.txt
Labels: cla: no

#1500 Expose corpus-wide speaker and chapter metadata in dataset metadata.
  tensorflow_datasets/audio/librispeech.py
Labels: cla: no

#1501 Add Speech Commands to TFDS
  tensorflow_datasets/audio/__init__.py
  tensorflow_datasets/audio/speech_commands.py
  tensorflow_datasets/audio/speech_commands_test.py
  tensorflow_datasets/testing/test_data/fake_examples/speech_commands/test.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/speech_commands/train.tar.gz
  tensorflow_datasets/url_checksums/speech_commands.txt
Labels: cla: no

#1505 Better Tensor singleton repr
  tensorflow_datasets/core/features/feature.py
  tensorflow_datasets/core/features/features_dict.py
  tensorflow_datasets/core/features/features_test.py
  tensorflow_datasets/core/features/sequence_feature.py
Labels: cla: no

#1498 Add libritts audio corpus, a variant of librispeech targeted at text-to-speech synthesis applications, to tfds.
  tensorflow_datasets/audio/__init__.py
  tensorflow_datasets/audio/libritts.py
  tensorflow_datasets/audio/libritts_test.py
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-clean/LibriTTS/dev-clean/11/01/11_01.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-clean/LibriTTS/dev-clean/11/01/11_01_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-clean/LibriTTS/dev-clean/12/02/12_02.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-clean/LibriTTS/dev-clean/12/02/12_02_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-clean/LibriTTS/speakers.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-other/LibriTTS/dev-other/13/03/13_03.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-other/LibriTTS/dev-other/13/03/13_03_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-other/LibriTTS/dev-other/14/04/14_04.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-other/LibriTTS/dev-other/14/04/14_04_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/dev-other/LibriTTS/speakers.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-clean/LibriTTS/speakers.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-clean/LibriTTS/test-clean/15/05/15_05.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-clean/LibriTTS/test-clean/15/05/15_05_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-clean/LibriTTS/test-clean/16/06/16_06.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-clean/LibriTTS/test-clean/16/06/16_06_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-other/LibriTTS/speakers.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-other/LibriTTS/test-clean/17/07/17_07.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-other/LibriTTS/test-clean/17/07/17_07_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-other/LibriTTS/test-clean/18/08/18_08.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/test-other/LibriTTS/test-clean/18/08/18_08_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-100/LibriTTS/speakers.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-100/LibriTTS/train-clean-100/19/09/19_09.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-100/LibriTTS/train-clean-100/19/09/19_09_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-100/LibriTTS/train-clean-100/20/10/20_10.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-100/LibriTTS/train-clean-100/20/10/20_10_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-360/LibriTTS/speakers.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-360/LibriTTS/train-clean-360/21/11/21_11.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-360/LibriTTS/train-clean-360/21/11/21_11_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-360/LibriTTS/train-clean-360/22/12/22_12.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-clean-360/LibriTTS/train-clean-360/22/12/22_12_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-other-500/LibriTTS/speakers.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-other-500/LibriTTS/train-other-500/23/13/23_13.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-other-500/LibriTTS/train-other-500/23/13/23_13_0000_000.wav
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-other-500/LibriTTS/train-other-500/24/14/24_14.trans.tsv
  tensorflow_datasets/testing/test_data/fake_examples/libritts/train-other-500/LibriTTS/train-other-500/24/14/24_14_0000_000.wav
  tensorflow_datasets/url_checksums/libritts.txt
Labels: cla: no

#1509 Update TFDS to 2.1.0
  tensorflow_datasets/version.py
Labels: cla: no

#1510 Automated documentation update
  docs/catalog/_toc.yaml
  docs/catalog/abstract_reasoning.md
  docs/catalog/amazon_us_reviews.md
  docs/catalog/arc.md
  docs/catalog/beans.md
  docs/catalog/bigearthnet.md
  docs/catalog/c4.md
  docs/catalog/celeb_a.md
  docs/catalog/civil_comments.md
  docs/catalog/clevr.md
  docs/catalog/coco.md
  docs/catalog/dsprites.md
  docs/catalog/duke_ultrasound.md
  docs/catalog/flic.md
  docs/catalog/gap.md
  docs/catalog/glue.md
  docs/catalog/groove.md
  docs/catalog/higgs.md
  docs/catalog/kitti.md
  docs/catalog/librispeech.md
  docs/catalog/librispeech_lm.md
  docs/catalog/natural_questions.md
  docs/catalog/newsroom.md
  docs/catalog/nsynth.md
  docs/catalog/omniglot.md
  docs/catalog/open_images_v4.md
  docs/catalog/overview.md
  docs/catalog/pet_finder.md
  docs/catalog/reddit_tifu.md
  docs/catalog/scicite.md
  docs/catalog/shapes3d.md
  docs/catalog/so2sat.md
  docs/catalog/speech_commands.md
  docs/catalog/squad.md
  docs/catalog/super_glue.md
  docs/catalog/titanic.md
  docs/catalog/trivia_qa.md
  docs/catalog/voc.md
  docs/catalog/wider_face.md
  tensorflow_datasets/testing/metadata/c4/en.noclean/2.2.1/dataset_info.json
  tensorflow_datasets/testing/metadata/c4/en.realnewslike/2.2.1/dataset_info.json
  tensorflow_datasets/testing/metadata/c4/en.webtextlike/2.2.1/dataset_info.json
  tensorflow_datasets/testing/metadata/c4/en/2.2.1/dataset_info.json
  tensorflow_datasets/testing/metadata/librispeech_lm/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#1502 Fixed a very small typo in Update abstract_reasoning.md
  tensorflow_datasets/scripts/templates/dataset.mako.md
Labels: cla: yes, tfds:please_review

#1515 Update version docs to clarify that changes to metadata should update the PATCH version.
  docs/datasets_versioning.md
Labels: cla: no

#1507 Update kitti dataset checksum files
  tensorflow_datasets/object_detection/kitti.py
  tensorflow_datasets/url_checksums/kitti.txt
Labels: cla: yes, community:please_review

#1514 Update tests to TF 2.1 and TF nightly, drop Py2 and TF1 support
  README.md
  oss_scripts/oss_pip_install.sh
  oss_scripts/oss_release.sh
  oss_scripts/oss_tests.sh
  oss_scripts/utils.sh
Labels: cla: no

#1494 adding checksum for flores and also empty file check.
  tensorflow_datasets/translate/flores.py
  tensorflow_datasets/url_checksums/flores.txt
Labels: cla: yes, tfds:is_reviewing

#1531 Automated documentation update
  docs/catalog/amazon_us_reviews.md
  docs/catalog/big_patent.md
  docs/catalog/bigearthnet.md
  docs/catalog/c4.md
  docs/catalog/celeb_a_hq.md
  docs/catalog/cifar10_1.md
  docs/catalog/cityscapes.md
  docs/catalog/cmaterdb.md
  docs/catalog/curated_breast_imaging_ddsm.md
  docs/catalog/cycle_gan.md
  docs/catalog/div2k.md
  docs/catalog/downsampled_imagenet.md
  docs/catalog/emnist.md
  docs/catalog/eurosat.md
  docs/catalog/flic.md
  docs/catalog/flores.md
  docs/catalog/imagenet_resized.md
  docs/catalog/imagenette.md
  docs/catalog/imagewang.md
  docs/catalog/imdb_reviews.md
  docs/catalog/kitti.md
  docs/catalog/lm1b.md
  docs/catalog/lost_and_found.md
  docs/catalog/lsun.md
  docs/catalog/para_crawl.md
  docs/catalog/qa4mre.md
  docs/catalog/so2sat.md
  docs/catalog/starcraft_video.md
  docs/catalog/ted_hrlr_translate.md
  docs/catalog/ucf101.md
  docs/catalog/visual_domain_decathlon.md
  docs/catalog/voc.md
  docs/catalog/wikihow.md
  docs/catalog/wikipedia.md
  docs/catalog/wmt14_translate.md
  docs/catalog/wmt15_translate.md
  docs/catalog/wmt16_translate.md
  docs/catalog/wmt17_translate.md
  docs/catalog/wmt18_translate.md
  docs/catalog/wmt19_translate.md
  docs/catalog/yelp_polarity_reviews.md
  tensorflow_datasets/testing/metadata/kitti/3.2.0/dataset_info.json
  tensorflow_datasets/testing/metadata/kitti/3.2.0/image.image.json
  tensorflow_datasets/testing/metadata/kitti/3.2.0/objects-type.labels.txt
  tensorflow_datasets/testing/metadata/missing.txt
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no
