Repository tensorflow/datasets, pull requests merged in 2020-08, with the labels that each got.

#2260 Deploy new version of Imagenet2012
  tensorflow_datasets/image_classification/imagenet.py
Labels: cla: no

#2244 Remove encoder from the datasets
  tensorflow_datasets/audio/__init__.py
  tensorflow_datasets/audio/librispeech.py
  tensorflow_datasets/audio/librispeech_test.py
  tensorflow_datasets/structured/rock_you.py
  tensorflow_datasets/summarization/__init__.py
  tensorflow_datasets/summarization/cnn_dailymail.py
  tensorflow_datasets/testing/mocking_test.py
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/imdb.py
  tensorflow_datasets/text/lm1b.py
  tensorflow_datasets/text/multi_nli.py
  tensorflow_datasets/text/multi_nli_mismatch.py
  tensorflow_datasets/text/yelp_polarity.py
  tensorflow_datasets/translate/flores.py
  tensorflow_datasets/translate/para_crawl.py
  tensorflow_datasets/translate/wmt.py
  tensorflow_datasets/translate/wmt15.py
Labels: cla: no

#2263 Fix genomics_ood URL
  tensorflow_datasets/structured/genomics_ood.py
Labels: cla: no

#2265 Rollback of text builder configs
  tensorflow_datasets/audio/__init__.py
  tensorflow_datasets/audio/librispeech.py
  tensorflow_datasets/audio/librispeech_test.py
  tensorflow_datasets/structured/rock_you.py
  tensorflow_datasets/summarization/__init__.py
  tensorflow_datasets/summarization/cnn_dailymail.py
  tensorflow_datasets/testing/mocking_test.py
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/imdb.py
  tensorflow_datasets/text/lm1b.py
  tensorflow_datasets/text/multi_nli.py
  tensorflow_datasets/text/multi_nli_mismatch.py
  tensorflow_datasets/text/yelp_polarity.py
  tensorflow_datasets/translate/flores.py
  tensorflow_datasets/translate/para_crawl.py
  tensorflow_datasets/translate/wmt.py
  tensorflow_datasets/translate/wmt15.py
Labels: cla: no

#2268 Minor big_patent update
  tensorflow_datasets/summarization/big_patent.py
Labels: cla: no

#2258 Better Version.__repr__
  tensorflow_datasets/core/utils/version.py
  tensorflow_datasets/core/utils/version_test.py
Labels: cla: no

#2273 * Allow `as_numpy()` iterable to be iterated on multiple times
  tensorflow_datasets/core/dataset_utils.py
  tensorflow_datasets/core/dataset_utils_test.py
  tensorflow_datasets/core/utils/gcs_utils_test.py
  tensorflow_datasets/core/utils/type_utils.py
Labels: cla: no

#2271 Add new alias for the text API: `tfds.features.text` -> `tfds.deprecated.text`
  tensorflow_datasets/audio/librispeech.py
  tensorflow_datasets/core/features/text/subword_text_encoder.py
  tensorflow_datasets/core/features/text_feature.py
  tensorflow_datasets/core/features/translation_feature.py
  tensorflow_datasets/public_api.py
  tensorflow_datasets/scripts/documentation/build_api_docs.py
  tensorflow_datasets/structured/rock_you.py
  tensorflow_datasets/summarization/cnn_dailymail.py
  tensorflow_datasets/text/imdb.py
  tensorflow_datasets/text/lm1b.py
  tensorflow_datasets/text/multi_nli.py
  tensorflow_datasets/text/multi_nli_mismatch.py
  tensorflow_datasets/text/yelp_polarity.py
  tensorflow_datasets/translate/flores.py
  tensorflow_datasets/translate/para_crawl.py
  tensorflow_datasets/translate/wmt.py
  tensorflow_datasets/translate/wmt15.py
Labels: cla: no

#2282 Add XQuAD with translate-train and translate-dev sets from XTREME.
  tensorflow_datasets/question_answering/__init__.py
  tensorflow_datasets/question_answering/xquad.py
  tensorflow_datasets/question_answering/xquad_test.py
  tensorflow_datasets/testing/test_data/fake_examples/xquad/test.json
  tensorflow_datasets/testing/test_data/fake_examples/xquad/translate-dev.json
  tensorflow_datasets/testing/test_data/fake_examples/xquad/translate-test.json
  tensorflow_datasets/testing/test_data/fake_examples/xquad/translate-train.json
  tensorflow_datasets/url_checksums/xquad.txt
Labels: cla: no, dataset request

#2287 Add TyDiQA GoldP task. Create `qa_utils` to reduce code duplication in `tfds.question_answering`.
  tensorflow_datasets/question_answering/__init__.py
  tensorflow_datasets/question_answering/natural_questions.py
  tensorflow_datasets/question_answering/qa_utils.py
  tensorflow_datasets/question_answering/squad.py
  tensorflow_datasets/question_answering/tydi_qa.py
  tensorflow_datasets/question_answering/tydi_qa_test.py
  tensorflow_datasets/question_answering/xquad.py
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/dev-v1.1.json
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/train-v1.1.json
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/tydiqa-goldp-v1.1-dev/tydiqa-goldp-dev-arabic.json
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/tydiqa-goldp-v1.1-dev/tydiqa-goldp-dev-bengali.json
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/tydiqa-goldp-v1.1-dev/tydiqa-goldp-dev-english.json
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/tydiqa-goldp-v1.1-dev/tydiqa-goldp-dev-finnish.json
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/tydiqa-goldp-v1.1-dev/tydiqa-goldp-dev-indonesian.json
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/tydiqa-goldp-v1.1-dev/tydiqa-goldp-dev-korean.json
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/tydiqa-goldp-v1.1-dev/tydiqa-goldp-dev-russian.json
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/tydiqa-goldp-v1.1-dev/tydiqa-goldp-dev-swahili.json
  tensorflow_datasets/testing/test_data/fake_examples/tydi_qa/tydiqa-goldp-v1.1-dev/tydiqa-goldp-dev-telugu.json
  tensorflow_datasets/url_checksums/triviaqa.txt
  tensorflow_datasets/url_checksums/tydi_qa.txt
Labels: cla: no

#2281 Add YesNo dataset
  tensorflow_datasets/audio/__init__.py
  tensorflow_datasets/audio/yesno/__init__.py
  tensorflow_datasets/audio/yesno/checksums.tsv
  tensorflow_datasets/audio/yesno/dummy_data/waves_yesno/0_0_0_0_0_1_0_1.wav
  tensorflow_datasets/audio/yesno/dummy_data_generation.py
  tensorflow_datasets/audio/yesno/yesno.py
  tensorflow_datasets/audio/yesno/yesno_test.py
Labels: cla: no, dataset request

#2276 Add PAWSX Wiki dataset
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/paws_x_wiki/__init__.py
  tensorflow_datasets/text/paws_x_wiki/checksums.tsv
  tensorflow_datasets/text/paws_x_wiki/dummy_data/x-final/es/dev_2k.tsv
  tensorflow_datasets/text/paws_x_wiki/dummy_data/x-final/es/test_2k.tsv
  tensorflow_datasets/text/paws_x_wiki/dummy_data/x-final/es/translated_train.tsv
  tensorflow_datasets/text/paws_x_wiki/dummy_data/x-final/ja/dev_2k.tsv
  tensorflow_datasets/text/paws_x_wiki/dummy_data/x-final/ja/test_2k.tsv
  tensorflow_datasets/text/paws_x_wiki/dummy_data/x-final/ja/translated_train.tsv
  tensorflow_datasets/text/paws_x_wiki/paws_x_wiki.py
  tensorflow_datasets/text/paws_x_wiki/paws_x_wiki_test.py
Labels: cla: no

#2256 Add BCCD dataset
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/bccd/__init__.py
  tensorflow_datasets/image/bccd/bccd.py
  tensorflow_datasets/image/bccd/bccd_test.py
  tensorflow_datasets/image/bccd/checksums.tsv
  tensorflow_datasets/image/bccd/dummy_data/BCCD_Dataset-1.0/BCCD/Annotations/BloodImage_00000.xml
  tensorflow_datasets/image/bccd/dummy_data/BCCD_Dataset-1.0/BCCD/Annotations/BloodImage_00001.xml
  tensorflow_datasets/image/bccd/dummy_data/BCCD_Dataset-1.0/BCCD/Annotations/BloodImage_00002.xml
  tensorflow_datasets/image/bccd/dummy_data/BCCD_Dataset-1.0/BCCD/Annotations/BloodImage_00003.xml
  tensorflow_datasets/image/bccd/dummy_data/BCCD_Dataset-1.0/BCCD/Annotations/BloodImage_00004.xml
  tensorflow_datasets/image/bccd/dummy_data/BCCD_Dataset-1.0/BCCD/ImageSets/Main/test.txt
  tensorflow_datasets/image/bccd/dummy_data/BCCD_Dataset-1.0/BCCD/ImageSets/Main/train.txt
  tensorflow_datasets/image/bccd/dummy_data/BCCD_Dataset-1.0/BCCD/ImageSets/Main/val.txt
  tensorflow_datasets/image/bccd/dummy_data/BCCD_Dataset-1.0/BCCD/JPEGImages/BloodImage_00000.jpg
  tensorflow_datasets/image/bccd/dummy_data/BCCD_Dataset-1.0/BCCD/JPEGImages/BloodImage_00001.jpg
  tensorflow_datasets/image/bccd/dummy_data/BCCD_Dataset-1.0/BCCD/JPEGImages/BloodImage_00002.jpg
  tensorflow_datasets/image/bccd/dummy_data/BCCD_Dataset-1.0/BCCD/JPEGImages/BloodImage_00003.jpg
  tensorflow_datasets/image/bccd/dummy_data/BCCD_Dataset-1.0/BCCD/JPEGImages/BloodImage_00004.jpg
  tensorflow_datasets/image/bccd/dummy_data_generation.py
Labels: cla: no, dataset request

#2297 Minor docstring formatting cleanup
  tensorflow_datasets/text/paws_x_wiki/paws_x_wiki.py
Labels: cla: no

#2292 Add Spoken Digit Dataset
  tensorflow_datasets/audio/__init__.py
  tensorflow_datasets/audio/spoken_digit/__init__.py
  tensorflow_datasets/audio/spoken_digit/checksums.tsv
  tensorflow_datasets/audio/spoken_digit/dummy_data/free-spoken-digit-dataset-1.0.9/recordings/4_queen_10.wav
  tensorflow_datasets/audio/spoken_digit/dummy_data_generation.py
  tensorflow_datasets/audio/spoken_digit/spoken_digit.py
  tensorflow_datasets/audio/spoken_digit/spoken_digit_test.py
Labels: cla: no

#2274 Update Caltech Birds dataset download urls
  tensorflow_datasets/image_classification/caltech_birds.py
  tensorflow_datasets/url_checksums/caltech_birds2010.txt
  tensorflow_datasets/url_checksums/caltech_birds2011.txt
Labels: cla: yes, community:please_review

#2289 [TFDS] Add Ai2 ARC with additional context from IR. Sentences and IR are the same as those used in UnifiedQA.
  tensorflow_datasets/question_answering/__init__.py
  tensorflow_datasets/question_answering/ai2_arc_with_ir.py
  tensorflow_datasets/question_answering/ai2_arc_with_ir_test.py
  tensorflow_datasets/testing/test_data/fake_examples/ai2_arc_with_ir/ARC-IR10V8/dev.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/ai2_arc_with_ir/ARC-IR10V8/test.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/ai2_arc_with_ir/ARC-IR10V8/train.jsonl
  tensorflow_datasets/url_checksums/ai2_arc_with_ir.txt
Labels: cla: no

#2277 Move text encoder to deprecated/ folder
  tensorflow_datasets/core/deprecated/__init__.py
  tensorflow_datasets/core/deprecated/text/__init__.py
  tensorflow_datasets/core/deprecated/text/subword_text_encoder.py
  tensorflow_datasets/core/deprecated/text/subword_text_encoder_test.py
  tensorflow_datasets/core/deprecated/text/text_encoder.py
  tensorflow_datasets/core/deprecated/text/text_encoder_test.py
  tensorflow_datasets/core/features/__init__.py
  tensorflow_datasets/core/features/text_feature.py
  tensorflow_datasets/core/features/text_feature_test.py
  tensorflow_datasets/core/features/translation_feature_test.py
  tensorflow_datasets/public_api.py
Labels: cla: no

#2280 Fix typo in dataset markdown builder
  docs/catalog/imagenet2012.md
  tensorflow_datasets/scripts/documentation/dataset_markdown_builder.py
Labels: cla: yes, tfds:ready_to_merge

#2298 Add Bool Q Dataset
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/bool_q/__init__.py
  tensorflow_datasets/text/bool_q/bool_q.py
  tensorflow_datasets/text/bool_q/bool_q_test.py
  tensorflow_datasets/text/bool_q/checksums.tsv
  tensorflow_datasets/text/bool_q/dummy_data/dev.jsonl
  tensorflow_datasets/text/bool_q/dummy_data/train.jsonl
Labels: cla: no

#2288 change yelp dataset link
  tensorflow_datasets/text/yelp_polarity.py
Labels: cla: yes, tfds:ready_to_merge

#2304 Updated description of manually downloading the test split for ImageNet 2012 to describe how to handle the 2019 patch.
  tensorflow_datasets/image_classification/imagenet.py
Labels: cla: no

#2303 Split registered.py in load.py and registered.py
  tensorflow_datasets/core/as_dataframe_test.py
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/load.py
  tensorflow_datasets/core/registered.py
  tensorflow_datasets/core/registered_test.py
  tensorflow_datasets/core/visualization/show_examples_test.py
  tensorflow_datasets/public_api.py
  tensorflow_datasets/scripts/deployment/copy_dataset_info_files.py
  tensorflow_datasets/scripts/documentation/document_datasets.py
  tensorflow_datasets/scripts/documentation/document_datasets_test.py
  tensorflow_datasets/scripts/documentation/generate_visualization.py
  tensorflow_datasets/scripts/freeze_dataset_versions.py
  tensorflow_datasets/scripts/metadata_cleanup.py
  tensorflow_datasets/testing/dataset_builder_testing.py
  tensorflow_datasets/testing/mocking_test.py
Labels: cla: no

#2307 Update DMLAB link, because the old one is down.
  tensorflow_datasets/image_classification/dmlab.py
  tensorflow_datasets/url_checksums/dmlab.txt
Labels: cla: no

#2221 Load and dump FeatureConnectors
  tensorflow_datasets/core/features/audio_feature.py
  tensorflow_datasets/core/features/audio_feature_test.py
  tensorflow_datasets/core/features/bounding_boxes.py
  tensorflow_datasets/core/features/class_label_feature.py
  tensorflow_datasets/core/features/class_label_feature_test.py
  tensorflow_datasets/core/features/feature.py
  tensorflow_datasets/core/features/features_dict.py
  tensorflow_datasets/core/features/image_feature.py
  tensorflow_datasets/core/features/image_feature_test.py
  tensorflow_datasets/core/features/sequence_feature.py
  tensorflow_datasets/core/features/sequence_feature_test.py
  tensorflow_datasets/core/features/text_feature.py
  tensorflow_datasets/core/features/text_feature_test.py
  tensorflow_datasets/core/features/translation_feature.py
  tensorflow_datasets/core/features/translation_feature_test.py
  tensorflow_datasets/core/features/video_feature.py
  tensorflow_datasets/core/features/video_feature_test.py
  tensorflow_datasets/core/utils/type_utils.py
  tensorflow_datasets/testing/test_utils.py
Labels: author:please_resolve_conflict, cla: yes, enhancement

#2305 Add a function to dynamically load DatasetBuilder from a Python module
  tensorflow_datasets/core/community/__init__.py
  tensorflow_datasets/core/community/load.py
  tensorflow_datasets/core/community/load_test.py
  tensorflow_datasets/core/registered.py
  tensorflow_datasets/core/registered_test.py
Labels: cla: no

#2291 Add GZTAN Dataset
  tensorflow_datasets/audio/__init__.py
  tensorflow_datasets/audio/gtzan/__init__.py
  tensorflow_datasets/audio/gtzan/checksums.tsv
  tensorflow_datasets/audio/gtzan/dummy_data/genres/country/country.00077.wav
  tensorflow_datasets/audio/gtzan/dummy_data_generation.py
  tensorflow_datasets/audio/gtzan/gtzan.py
  tensorflow_datasets/audio/gtzan/gtzan_test.py
Labels: cla: no

#2315 Fix bug where xquad and tydi qa kept the same context for all questions.
  tensorflow_datasets/question_answering/qa_utils.py
  tensorflow_datasets/question_answering/qa_utils_test.py
  tensorflow_datasets/question_answering/tydi_qa.py
  tensorflow_datasets/question_answering/xquad.py
  tensorflow_datasets/question_answering/xquad_test.py
  tensorflow_datasets/testing/test_data/fake_examples/xquad/translate-test.json
Labels: cla: no

#2311 Minor `tfds.core.benchmark` update:
  docs/performances.md
  tensorflow_datasets/core/utils/benchmark.py
Labels: cla: no

#2312 Add <my_dataset>/checksums.tsv to setup.py
  setup.py
Labels: cla: no

#2314 Add `tfds.as_dataframe` to the documentation
  docs/overview.ipynb
Labels: cla: no

#2310 Add Wine Quality Dataset
  tensorflow_datasets/structured/__init__.py
  tensorflow_datasets/structured/wine_quality/__init__.py
  tensorflow_datasets/structured/wine_quality/checksums.tsv
  tensorflow_datasets/structured/wine_quality/dummy_data/winequality-red.csv
  tensorflow_datasets/structured/wine_quality/dummy_data/winequality-white.csv
  tensorflow_datasets/structured/wine_quality/wine_quality.py
  tensorflow_datasets/structured/wine_quality/wine_quality_test.py
Labels: cla: no

#2327 Adds note about parallelism and absolute ranges to ReadInstruction class pydoc.
  docs/splits.md
  tensorflow_datasets/core/tfrecords_reader.py
Labels: cla: no

#2330 Display less as_dataframe examples in the documentation
  docs/overview.ipynb
Labels: cla: no

#2284 Show Supported Python versions
  README.md
  setup.py
Labels: cla: yes, tfds:ready_to_merge

#2319 add mocking for bools
  tensorflow_datasets/testing/mocking.py
  tensorflow_datasets/testing/mocking_test.py
Labels: cla: yes, tfds:ready_to_merge

#2313 Remove BuilderConfig from the text datasets
  tensorflow_datasets/text/definite_pronoun_resolution.py
  tensorflow_datasets/text/esnli.py
  tensorflow_datasets/text/snli.py
  tensorflow_datasets/text/xnli.py
  tensorflow_datasets/translate/ted_multi.py
Labels: cla: no

#2332 Update ReadConfig to be eq=False
  tensorflow_datasets/core/utils/read_config.py
Labels: cla: no

#2306 Add GTZAN Music Speech Classification Dataset
  tensorflow_datasets/audio/__init__.py
  tensorflow_datasets/audio/gtzan_music_speech/__init__.py
  tensorflow_datasets/audio/gtzan_music_speech/checksums.tsv
  tensorflow_datasets/audio/gtzan_music_speech/dummy_data/music_speech/speech_wav/test.wav
  tensorflow_datasets/audio/gtzan_music_speech/dummy_data_generation.py
  tensorflow_datasets/audio/gtzan_music_speech/gtzan_music_speech.py
  tensorflow_datasets/audio/gtzan_music_speech/gtzan_music_speech_test.py
Labels: cla: no

#2333 Add TREC Dataset
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/trec/__init__.py
  tensorflow_datasets/text/trec/checksums.tsv
  tensorflow_datasets/text/trec/dummy_data/TREC_10.label
  tensorflow_datasets/text/trec/dummy_data/train_5500.label
  tensorflow_datasets/text/trec/trec.py
  tensorflow_datasets/text/trec/trec_test.py
Labels: cla: no

#2331 Add Sentiment140 Dataset
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/sentiment140/__init__.py
  tensorflow_datasets/text/sentiment140/checksums.tsv
  tensorflow_datasets/text/sentiment140/dummy_data/testdata.manual.2009.06.14.csv
  tensorflow_datasets/text/sentiment140/dummy_data/training.1600000.processed.noemoticon.csv
  tensorflow_datasets/text/sentiment140/sentiment140.py
  tensorflow_datasets/text/sentiment140/sentiment140_test.py
Labels: cla: no

#2335 Add CoQA Dataset
  tensorflow_datasets/question_answering/__init__.py
  tensorflow_datasets/question_answering/coqa/__init__.py
  tensorflow_datasets/question_answering/coqa/checksums.tsv
  tensorflow_datasets/question_answering/coqa/coqa.py
  tensorflow_datasets/question_answering/coqa/coqa_test.py
  tensorflow_datasets/question_answering/coqa/dummy_data/coqa-dev-v1.0.json
  tensorflow_datasets/question_answering/coqa/dummy_data/coqa-train-v1.0.json
Labels: cla: no

#2334 fix return type of tfds.load in doc
  tensorflow_datasets/core/load.py
Labels: cla: yes, tfds:ready_to_merge

#2336 Move metadata_cleanup script to cleanup/
  tensorflow_datasets/scripts/cleanup/metadata_cleanup.py
Labels: cla: no

#2337 Add QASC Dataset
  tensorflow_datasets/question_answering/__init__.py
  tensorflow_datasets/question_answering/qasc/__init__.py
  tensorflow_datasets/question_answering/qasc/checksums.tsv
  tensorflow_datasets/question_answering/qasc/dummy_data/QASC_Dataset/dev.jsonl
  tensorflow_datasets/question_answering/qasc/dummy_data/QASC_Dataset/test.jsonl
  tensorflow_datasets/question_answering/qasc/dummy_data/QASC_Dataset/train.jsonl
  tensorflow_datasets/question_answering/qasc/qasc.py
  tensorflow_datasets/question_answering/qasc/qasc_test.py
Labels: cla: no

#2325 Convert Hugging Face datasets
  tensorflow_datasets/scripts/cleanup/convert_nlp.py
  tensorflow_datasets/scripts/cli/new.py
Labels: cla: no

#2338 Wrap GCS paths inside `tfds.core.gcs_path`
  tensorflow_datasets/core/utils/gcs_utils.py
  tensorflow_datasets/object_detection/waymo_open_dataset.py
  tensorflow_datasets/text/pg19.py
Labels: cla: no

#2345 Add salient span wikipedia dataset from REALM.
  tensorflow_datasets/testing/test_data/fake_examples/salient_span_wikipedia/test_examples.tfrecord.gz
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/salient_span_wikipedia.py
  tensorflow_datasets/text/salient_span_wikipedia_test.py
Labels: cla: no

#2328 Surround calls to tf.io.gfile.Exists with a try catch to avoid unexpected behaviour with TFDS if this call fails.
  tensorflow_datasets/core/utils/gcs_utils.py
Labels: cla: no

#2343 `as_supervised=True` support for `tfds.show_examples`, Fix #1575, Fix #2342
  tensorflow_datasets/core/visualization/show_examples.py
  tensorflow_datasets/core/visualization/show_examples_test.py
Labels: cla: no

#2341 Cleanup README.md
  README.md
Labels: cla: no

#2349 Remove deprecated method
  tensorflow_datasets/text/salient_span_wikipedia.py
Labels: cla: no

#2339 Adding filenames as features which enables filtering by specific robots.
  tensorflow_datasets/video/robonet.py
Labels: cla: no

#2360 internal
  tensorflow_datasets/scripts/download_and_prepare.py
Labels: cla: no

#2363 Add synthetic tasks from GPT-3 paper.
  tensorflow_datasets/testing/test_data/fake_examples/gpt3/gpt-3-master/data/cycle_letters_in_word.jsonl.gz
  tensorflow_datasets/testing/test_data/fake_examples/gpt3/gpt-3-master/data/sum_of_digits.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/gpt3/gpt-3-master/data/two_digit_addition.jsonl
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/gpt3.py
  tensorflow_datasets/text/gpt3_test.py
  tensorflow_datasets/url_checksums/gpt3.txt
Labels: cla: no
