Repository tensorflow/datasets, pull requests merged in 2020-06, with the labels that each got.

#2064 Fix generate_visualization bug when splits not found.
  tensorflow_datasets/scripts/documentation/generate_visualization.py
Labels: cla: no

#2063 Expose `tfds.show_statistics` alias to the public API
  tensorflow_datasets/public_api.py
Labels: cla: no

#2066 Added PG-19 dataset
  tensorflow_datasets/testing/test_data/fake_examples/pg19/metadata.csv
  tensorflow_datasets/testing/test_data/fake_examples/pg19/test/121122.txt
  tensorflow_datasets/testing/test_data/fake_examples/pg19/train/121322.txt
  tensorflow_datasets/testing/test_data/fake_examples/pg19/train/121422.txt
  tensorflow_datasets/testing/test_data/fake_examples/pg19/train/121522.txt
  tensorflow_datasets/testing/test_data/fake_examples/pg19/validation/121222.txt
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/pg19.py
  tensorflow_datasets/text/pg19_test.py
  tensorflow_datasets/url_checksums/pg19.txt
Labels: cla: yes, tfds:is_reviewing

#2056 Add IRC Disentanglement dataset https://github.com/jkkummerfeld/irc-disentanglement
  tensorflow_datasets/testing/test_data/fake_examples/irc_disentanglement/jkkummerfeld-irc-disentanglement-fd379e9/data/dev/2004-11-20_10.annotation.txt
  tensorflow_datasets/testing/test_data/fake_examples/irc_disentanglement/jkkummerfeld-irc-disentanglement-fd379e9/data/dev/2004-11-20_10.raw.txt
  tensorflow_datasets/testing/test_data/fake_examples/irc_disentanglement/jkkummerfeld-irc-disentanglement-fd379e9/data/test/2004-11-15_03.annotation.txt
  tensorflow_datasets/testing/test_data/fake_examples/irc_disentanglement/jkkummerfeld-irc-disentanglement-fd379e9/data/test/2004-11-15_03.raw.txt
  tensorflow_datasets/testing/test_data/fake_examples/irc_disentanglement/jkkummerfeld-irc-disentanglement-fd379e9/data/train/2005-02-08.train-a.annotation.txt
  tensorflow_datasets/testing/test_data/fake_examples/irc_disentanglement/jkkummerfeld-irc-disentanglement-fd379e9/data/train/2005-02-08.train-a.raw.txt
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/irc_disentanglement.py
  tensorflow_datasets/text/irc_disentanglement_test.py
  tensorflow_datasets/url_checksums/irc_disentanglement.txt
Labels: cla: no

#2062 Add a list_info_files util
  tensorflow_datasets/core/utils/py_utils.py
Labels: cla: no

#1902 covid19sum
  tensorflow_datasets/summarization/__init__.py
  tensorflow_datasets/summarization/covid19sum.py
  tensorflow_datasets/summarization/covid19sum_test.py
  tensorflow_datasets/testing/test_data/fake_examples/covid19sum/CORD-19-research-challenge.zip
Labels: cla: no

#2061 Add script to copy metadata
  tensorflow_datasets/scripts/deployment/__init__.py
  tensorflow_datasets/scripts/deployment/copy_dataset_info_files.py
Labels: cla: no

#2071 Update TFDV version executed
  setup.py
Labels: cla: no

#2072 Corrected Catalog Overview
  tensorflow_datasets/scripts/documentation/templates/catalog_overview.mako.md
Labels: cla: yes, community:please_review

#2074 Fix _list_directory function
  tensorflow_datasets/testing/test_utils.py
  tensorflow_datasets/testing/test_utils_test.py
Labels: bug, cla: yes, tfds:ready_to_merge

#2080 move qa datasets to dedicated folder
  tensorflow_datasets/__init__.py
  tensorflow_datasets/question_answering/__init__.py
  tensorflow_datasets/question_answering/cosmos_qa.py
  tensorflow_datasets/question_answering/cosmos_qa_test.py
  tensorflow_datasets/question_answering/mctaco.py
  tensorflow_datasets/question_answering/mctaco_test.py
  tensorflow_datasets/question_answering/natural_questions.py
  tensorflow_datasets/question_answering/natural_questions_test.py
  tensorflow_datasets/question_answering/squad.py
  tensorflow_datasets/question_answering/squad_test.py
  tensorflow_datasets/question_answering/trivia_qa.py
  tensorflow_datasets/question_answering/trivia_qa_test.py
  tensorflow_datasets/question_answering/web_questions.py
  tensorflow_datasets/question_answering/web_questions_test.py
  tensorflow_datasets/scripts/create_new_dataset.py
  tensorflow_datasets/text/__init__.py
Labels: cla: no

#2102 Fix missing NoReturn with Python 3.6
  tensorflow_datasets/core/custom_dataset/image_folder.py
Labels: cla: no

#2110 Add ImageNet validation split with new "Re-assessed Labels" (ReaL).
  tensorflow_datasets/image_classification/__init__.py
  tensorflow_datasets/image_classification/imagenet2012_real.py
  tensorflow_datasets/image_classification/imagenet2012_real_test.py
  tensorflow_datasets/testing/fake_data_generation/imagenet.py
  tensorflow_datasets/testing/fake_data_utils.py
  tensorflow_datasets/testing/test_data/fake_examples/imagenet2012_real/ILSVRC2012_img_val.tar
  tensorflow_datasets/testing/test_data/fake_examples/imagenet2012_real/real.json
  tensorflow_datasets/url_checksums/imagenet2012_real.txt
Labels: cla: no

#2108 Wikipedia Toxicity Subtypes dataset to TFDS.
  tensorflow_datasets/testing/test_data/fake_examples/wikipedia_toxicity_subtypes/wikidata_test.csv
  tensorflow_datasets/testing/test_data/fake_examples/wikipedia_toxicity_subtypes/wikidata_train.csv
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/wikipedia_toxicity_subtypes.py
  tensorflow_datasets/text/wikipedia_toxicity_subtypes_test.py
  tensorflow_datasets/url_checksums/wikipedia_toxicity_subtypes.txt
Labels: cla: no

#2120 Remove redundant shape and string checks to improve performance
  tensorflow_datasets/core/example_serializer.py
  tensorflow_datasets/core/example_serializer_test.py
Labels: cla: yes

#2119 Made correction for an example in docstring
  tensorflow_datasets/core/example_serializer.py
Labels: author:kokoro_test_failed, cla: yes

#2117 Minor changes to GitHub workflow
  .gitignore
  CONTRIBUTING.md
Labels: author:kokoro_test_failed, cla: yes

#2094 Add Custom Translate Datasets template
  tensorflow_datasets/core/custom_dataset/__init__.py
  tensorflow_datasets/core/custom_dataset/translate_folder.py
  tensorflow_datasets/core/custom_dataset/translate_folder_test.py
  tensorflow_datasets/public_api.py
  tensorflow_datasets/testing/test_data/fake_examples/translate_folder/az.test.txt
  tensorflow_datasets/testing/test_data/fake_examples/translate_folder/az.train.txt
  tensorflow_datasets/testing/test_data/fake_examples/translate_folder/az.val.txt
  tensorflow_datasets/testing/test_data/fake_examples/translate_folder/en.test.txt
  tensorflow_datasets/testing/test_data/fake_examples/translate_folder/en.train.txt
  tensorflow_datasets/testing/test_data/fake_examples/translate_folder/en.val.txt
Labels: cla: yes, tfds:is_reviewing

#2124 Make Wikipedia Toxicity Subtypes features consistent with CivilComments.
  tensorflow_datasets/text/wikipedia_toxicity_subtypes.py
Labels: cla: no

#2127 Prefer list comprehension in TopLevelFeature.decode_example
  tensorflow_datasets/core/features/top_level_feature.py
Labels: cla: yes, community:please_review

#2111 Use TFDS_DATA_DIR environment variable if available.
  tensorflow_datasets/core/constants.py
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/registered.py
Labels: cla: yes

#2125 Simplify access counter in FeatureDict._flatten
  tensorflow_datasets/core/features/features_dict.py
Labels: author:kokoro_test_failed, cla: yes

#2017 Update cifar10_1 datasets checksums
  tensorflow_datasets/image_classification/cifar10_1.py
  tensorflow_datasets/url_checksums/cifar10_1.txt
Labels: cla: yes, tfds:ready_to_merge

#2122 Optimizing run_with_reraise
  tensorflow_datasets/core/example_serializer.py
  tensorflow_datasets/core/example_serializer_test.py
Labels: author:kokoro_test_failed, cla: yes

#2123 Remove py_utils.abstractclassmethod
  tensorflow_datasets/core/features/text/text_encoder.py
  tensorflow_datasets/core/utils/py_utils.py
Labels: cla: yes, community:please_review

#2126 Rename __is_top_level to support autograph
  tensorflow_datasets/core/features/top_level_feature.py
Labels: author:kokoro_test_failed, cla: yes

#2128 Set __slots__ for frequently used classes
  tensorflow_datasets/core/features/feature.py
  tensorflow_datasets/core/utils/tf_utils.py
Labels: author:kokoro_test_failed, cla: yes

#2136 Update catalog nightly note
  docs/catalog/overview.md
Labels: author:kokoro_test_failed, cla: yes

#2114 Updated kaggle utils
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/downloader.py
  tensorflow_datasets/core/download/downloader_test.py
  tensorflow_datasets/core/download/kaggle.py
  tensorflow_datasets/core/download/kaggle_test.py
  tensorflow_datasets/testing/test_utils.py
Labels: bug, cla: yes, contributions welcome, tfds:is_reviewing
