Repository tensorflow/datasets, pull requests merged in 2020-12, with the labels that each got.

#2794 Disable community datasets for scripts and tests
  tensorflow_datasets/conftest.py
  tensorflow_datasets/core/load.py
  tensorflow_datasets/scripts/cleanup/refactor_dataset_as_folder.py
  tensorflow_datasets/scripts/cleanup/url_filename_recorder.py
  tensorflow_datasets/scripts/cleanup/url_status_checker.py
  tensorflow_datasets/scripts/cli/build.py
  tensorflow_datasets/scripts/documentation/document_datasets.py
  tensorflow_datasets/testing/setup_teardown.py
  tensorflow_datasets/testing/test_case.py
Labels: cla: no

#2797 Update catalog builder
  tensorflow_datasets/core/__init__.py
  tensorflow_datasets/scripts/documentation/build_catalog.py
  tensorflow_datasets/scripts/documentation/build_catalog_test.py
  tensorflow_datasets/scripts/documentation/doc_utils.py
  tensorflow_datasets/scripts/documentation/doc_utils_test.py
  tensorflow_datasets/scripts/documentation/document_datasets.py
  tensorflow_datasets/scripts/documentation/document_datasets_test.py
  tensorflow_datasets/scripts/documentation/templates/catalog_overview.mako.md
  tensorflow_datasets/scripts/documentation/templates/catalog_overview.md
Labels: cla: no

#2806 Do not use mako for schema.org
  setup.py
  tensorflow_datasets/scripts/documentation/dataset_markdown_builder.py
  tensorflow_datasets/scripts/documentation/document_datasets.py
  tensorflow_datasets/scripts/documentation/templates/schema_org.mako.md
Labels: cla: no

#2807 Allow to customize the doc util paths
  tensorflow_datasets/scripts/documentation/build_catalog.py
  tensorflow_datasets/scripts/documentation/build_catalog_test.py
  tensorflow_datasets/scripts/documentation/dataset_markdown_builder.py
  tensorflow_datasets/scripts/documentation/doc_utils.py
  tensorflow_datasets/scripts/documentation/doc_utils_test.py
  tensorflow_datasets/scripts/documentation/document_datasets.py
  tensorflow_datasets/scripts/documentation/document_datasets_test.py
Labels: cla: no

#2792 Make SplitInfo a dataclass
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/dataset_info_test.py
  tensorflow_datasets/core/folder_dataset/image_folder.py
  tensorflow_datasets/core/folder_dataset/translate_folder.py
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/core/splits_test.py
  tensorflow_datasets/core/tfrecords_reader_test.py
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/testing/test_data/dataset_info/mnist/3.0.1/dataset_info.json
Labels: cla: no

#2808 Remove testing filter
  tensorflow_datasets/scripts/documentation/document_datasets.py
Labels: cla: no

#2804 Fix GCS support for `tfds build --data_dir=gs://` (Fix #2799)
  tensorflow_datasets/scripts/cli/build.py
Labels: cla: no

#2793 Make SplitDict immuntable
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/folder_dataset/image_folder.py
  tensorflow_datasets/core/folder_dataset/translate_folder.py
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/core/splits_test.py
Labels: cla: no

#2795 Use tfds.testing rather than absltest
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/download/download_manager_test.py
  tensorflow_datasets/core/download/downloader_test.py
  tensorflow_datasets/core/download/extractor_test.py
  tensorflow_datasets/core/tfrecords_reader_test.py
  tensorflow_datasets/core/tfrecords_writer_test.py
  tensorflow_datasets/testing/dataset_builder_testing.py
  tensorflow_datasets/testing/test_case.py
Labels: cla: no

#2805 Add S3O4D to tensorflow_datasets
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/s3o4d/__init__.py
  tensorflow_datasets/image/s3o4d/checksums.tsv
  tensorflow_datasets/image/s3o4d/dummy_data/bunny/test_images.zip
  tensorflow_datasets/image/s3o4d/dummy_data/bunny/test_latents.npz
  tensorflow_datasets/image/s3o4d/dummy_data/bunny/train_images.zip
  tensorflow_datasets/image/s3o4d/dummy_data/bunny/train_latents.npz
  tensorflow_datasets/image/s3o4d/dummy_data/dragon/test_images.zip
  tensorflow_datasets/image/s3o4d/dummy_data/dragon/test_latents.npz
  tensorflow_datasets/image/s3o4d/dummy_data/dragon/train_images.zip
  tensorflow_datasets/image/s3o4d/dummy_data/dragon/train_latents.npz
  tensorflow_datasets/image/s3o4d/s3o4d.py
  tensorflow_datasets/image/s3o4d/s3o4d_test.py
Labels: cla: no

#2811 Save/restore default config info when loading from files
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/read_only_builder.py
  tensorflow_datasets/core/read_only_builder_test.py
Labels: cla: no

#2809 Remove duplicate testing code
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: yes, tfds:ready_to_merge

#2816 Add description of TensorFlow Datasets to GitHub README, and change dataset name to avoid snake case dataset name.
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/s3o4d/__init__.py
  tensorflow_datasets/image/s3o4d/s3o4d.py
  tensorflow_datasets/image/s3o4d/s3o4d_test.py
Labels: cla: no

#2819 Upgrade protobuf to fix kokoro
  oss_scripts/oss_pip_install.sh
  setup.py
Labels: cla: no

#2821 Fix deprecationwarning error (fromstring -> frombuffer)
  tensorflow_datasets/core/shuffle_test.py
  tensorflow_datasets/image_classification/caltech_birds.py
  tensorflow_datasets/image_classification/cbis_ddsm.py
  tensorflow_datasets/image_classification/corruptions.py
  tensorflow_datasets/image_classification/diabetic_retinopathy_detection.py
  tensorflow_datasets/image_classification/sun.py
  tensorflow_datasets/object_detection/kitti.py
  tensorflow_datasets/object_detection/open_images.py
  tensorflow_datasets/object_detection/open_images_challenge2019_beam.py
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: no

#2814 Update scripts/documentation for community dataset
  tensorflow_datasets/core/__init__.py
  tensorflow_datasets/core/read_only_builder.py
  tensorflow_datasets/core/read_only_builder_test.py
  tensorflow_datasets/scripts/documentation/build_catalog.py
  tensorflow_datasets/scripts/documentation/dataset_markdown_builder.py
  tensorflow_datasets/scripts/documentation/doc_utils.py
  tensorflow_datasets/scripts/documentation/document_datasets.py
Labels: cla: no

#2823 Remove deprecated `back_prop=False` parameter
  docs/decode.md
  tensorflow_datasets/core/decode/base.py
  tensorflow_datasets/core/features/feature.py
  tensorflow_datasets/video/moving_sequence.py
Labels: cla: no

#2619 Add DART dataset
  tensorflow_datasets/structured/__init__.py
  tensorflow_datasets/structured/dart/__init__.py
  tensorflow_datasets/structured/dart/checksums.tsv
  tensorflow_datasets/structured/dart/dart.py
  tensorflow_datasets/structured/dart/dart_test.py
  tensorflow_datasets/structured/dart/dummy_data/dart-master/data/v1.1.1/dart-v1.1.1-full-dev.json
  tensorflow_datasets/structured/dart/dummy_data/dart-master/data/v1.1.1/dart-v1.1.1-full-test.json
  tensorflow_datasets/structured/dart/dummy_data/dart-master/data/v1.1.1/dart-v1.1.1-full-train.json
Labels: cla: no, dataset request

#2826 Minor documentation clarification
  docs/overview.ipynb
Labels: cla: no

#2824 Make tfds.core.gcs_path returns Path-like object
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/utils/gcs_utils.py
  tensorflow_datasets/object_detection/waymo_open_dataset.py
  tensorflow_datasets/scripts/deployment/copy_dataset_info_files.py
  tensorflow_datasets/scripts/documentation/generate_dataframe.py
  tensorflow_datasets/scripts/documentation/generate_visualization.py
  tensorflow_datasets/scripts/documentation/script_utils.py
  tensorflow_datasets/text/pg19.py
Labels: cla: no

#2829 Restrict keys to str, int
  tensorflow_datasets/core/hashing.py
Labels: cla: no

#2832 [*.py] Rename "Arguments:" to "Args:"
  tensorflow_datasets/scripts/cleanup/delete_old_versions.py
Labels: cla: yes, tfds:ready_to_merge

#2835 Fix GCS crash when unavailable (Fix #2833)
  tensorflow_datasets/core/utils/gcs_utils.py
Labels: cla: no

#2837 Support 0-len sequence of dynamic shape images (Fix #2616)
  tensorflow_datasets/core/features/feature.py
  tensorflow_datasets/core/features/sequence_feature_test.py
Labels: cla: no

#2836 Add LVIS dataset.
  tensorflow_datasets/object_detection/__init__.py
  tensorflow_datasets/object_detection/lvis/__init__.py
  tensorflow_datasets/object_detection/lvis/checksums.tsv
  tensorflow_datasets/object_detection/lvis/dummy_data/lvis_v1_image_info_test_dev.json
  tensorflow_datasets/object_detection/lvis/dummy_data/lvis_v1_train.json
  tensorflow_datasets/object_detection/lvis/dummy_data/lvis_v1_val.json
  tensorflow_datasets/object_detection/lvis/dummy_data/test2017/005.jpg
  tensorflow_datasets/object_detection/lvis/dummy_data/train2017/001.jpg
  tensorflow_datasets/object_detection/lvis/dummy_data/train2017/002.jpg
  tensorflow_datasets/object_detection/lvis/dummy_data/val2017/003.jpg
  tensorflow_datasets/object_detection/lvis/lvis.py
  tensorflow_datasets/object_detection/lvis/lvis_test.py
Labels: cla: no

#2840 [tensorflow_datasets/core/utils/gpath.py] Fix Windows support - `ModuleNotFoundError: No module named 'pwd'`
  tensorflow_datasets/core/utils/gpath.py
Labels: cla: yes, tfds:ready_to_merge

#2842 Add `tfds.typing` to the public API
  tensorflow_datasets/public_api.py
Labels: cla: no

#2838 Add support for decoders in ImageFolder
  tensorflow_datasets/core/folder_dataset/image_folder.py
  tensorflow_datasets/core/folder_dataset/image_folder_test.py
Labels: cla: yes, tfds:ready_to_merge

#2843 Update ReadOnlyBuilder to restore the original __module__
  tensorflow_datasets/core/read_only_builder.py
  tensorflow_datasets/core/read_only_builder_test.py
Labels: cla: no

#2844 Allows num_parallel_calls to be configurable in TFDS.
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/utils/read_config.py
Labels: cla: no

#2848 Add a `tfds.ReadConfig(add_tfds_id=True)`
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_read_test.py
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/tfrecords_reader_test.py
  tensorflow_datasets/core/utils/read_config.py
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no

#2849 Minor attr -> dataclasses cleanup
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/utils/shard_utils.py
Labels: cla: no

#2853 * Add support for --max_examples_per_splits=0: This can be useful when updating the checksums but without regenerating the full dataset `--register_checksums`.
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/load.py
  tensorflow_datasets/scripts/cli/build.py
  tensorflow_datasets/scripts/cli/build_test.py
Labels: cla: no

#2856 Remove tfds.units from the public API.
  tensorflow_datasets/core/units.py
  tensorflow_datasets/public_api.py
  tensorflow_datasets/scripts/documentation/dataset_markdown_builder.py
Labels: cla: no

#2841 Update TF MNIST Example
  docs/keras_example.ipynb
Labels: cla: yes

#2855 Better logging when using `tfds` CLI
  tensorflow_datasets/scripts/cli/main.py
Labels: cla: no

#2859 Update `DatasetInfo.__repr__`
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/dataset_info_test.py
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/scripts/cli/build.py
Labels: cla: no

#2851 Add log message when dynamically importing dataset
  tensorflow_datasets/scripts/cli/build.py
Labels: cla: no

#2858 Fix TQDM artifacts for logging
  tensorflow_datasets/core/utils/tqdm_utils.py
  tensorflow_datasets/scripts/cli/main.py
Labels: cla: no

#2857 Cleanup logging and fix additional TQDM artifacts
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/split_builder.py
  tensorflow_datasets/core/tfrecords_writer.py
Labels: cla: no

#2850 Update wikipedia dumps
  tensorflow_datasets/testing/test_data/fake_examples/wikipedia/dumpstatus.json
  tensorflow_datasets/text/wikipedia.py
  tensorflow_datasets/text/wikipedia_test.py
  tensorflow_datasets/url_checksums/wikipedia.txt
Labels: cla: no

#2825 Add WIKITABLEQUESTIONS dataset
  tensorflow_datasets/structured/__init__.py
  tensorflow_datasets/structured/wiki_table_questions/__init__.py
  tensorflow_datasets/structured/wiki_table_questions/checksums.tsv
  tensorflow_datasets/structured/wiki_table_questions/dummy_data/WikiTableQuestions-master/csv/203-csv/733.csv
  tensorflow_datasets/structured/wiki_table_questions/dummy_data/WikiTableQuestions-master/csv/204-csv/149.csv
  tensorflow_datasets/structured/wiki_table_questions/dummy_data/WikiTableQuestions-master/csv/204-csv/590.csv
  tensorflow_datasets/structured/wiki_table_questions/dummy_data/WikiTableQuestions-master/csv/204-csv/622.csv
  tensorflow_datasets/structured/wiki_table_questions/dummy_data/WikiTableQuestions-master/csv/204-csv/772.csv
  tensorflow_datasets/structured/wiki_table_questions/dummy_data/WikiTableQuestions-master/data/pristine-unseen-tables.tsv
  tensorflow_datasets/structured/wiki_table_questions/dummy_data/WikiTableQuestions-master/data/random-split-1-dev.tsv
  tensorflow_datasets/structured/wiki_table_questions/dummy_data/WikiTableQuestions-master/data/random-split-1-train.tsv
  tensorflow_datasets/structured/wiki_table_questions/dummy_data/WikiTableQuestions-master/data/random-split-2-dev.tsv
  tensorflow_datasets/structured/wiki_table_questions/dummy_data/WikiTableQuestions-master/data/random-split-2-train.tsv
  tensorflow_datasets/structured/wiki_table_questions/dummy_data/WikiTableQuestions-master/data/random-split-3-dev.tsv
  tensorflow_datasets/structured/wiki_table_questions/dummy_data/WikiTableQuestions-master/data/random-split-3-train.tsv
  tensorflow_datasets/structured/wiki_table_questions/dummy_data/WikiTableQuestions-master/data/training.tsv
  tensorflow_datasets/structured/wiki_table_questions/wiki_table_questions.py
  tensorflow_datasets/structured/wiki_table_questions/wiki_table_questions_test.py
Labels: cla: no

#2865 Better error message when accessing `info.splits['train']` in a non generated dataset
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/core/splits_test.py
Labels: cla: no

#2862 Remove deprecated dataset from doc
  docs/catalog/image_label_folder.md
Labels: cla: no

#2863 [tfds] Update links to TFDS documentation
  README.md
Labels: cla: no

#2866 Fix file reading error.
  tensorflow_datasets/structured/web_nlg/web_nlg.py
  tensorflow_datasets/structured/web_nlg/web_nlg_test.py
Labels: cla: no

#2871 Fix `path.touch()` when file already exists
  tensorflow_datasets/core/utils/gpath_test.py
  tensorflow_datasets/core/utils/type_utils.py
Labels: cla: no

#2873 Clarify message when TF not installed
  tensorflow_datasets/core/tf_compat.py
Labels: cla: no

#2868 Fix read from code when config does not exists
  tensorflow_datasets/core/load.py
  tensorflow_datasets/core/read_only_builder_test.py
  tensorflow_datasets/core/registered_test.py
Labels: cla: no

#2877 Add `GPath.unlink` to remove a file
  tensorflow_datasets/core/utils/gpath.py
  tensorflow_datasets/core/utils/gpath_test.py
  tensorflow_datasets/core/utils/type_utils.py
Labels: cla: no

#2878 Fix concurrent access when writing global config
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/core/utils/py_utils_test.py
Labels: cla: no

#2880 Add `__len__` to `tfds.as_numpy` datasets
  tensorflow_datasets/core/dataset_utils.py
  tensorflow_datasets/core/dataset_utils_test.py
Labels: cla: no

#2881 Add a note about common pitfall when computing imagenet2012_real accuracy.
  tensorflow_datasets/image_classification/imagenet2012_real.py
Labels: cla: no

#2874 Add a DatasetName utils
  tensorflow_datasets/core/community/register_base.py
  tensorflow_datasets/core/community/register_path.py
  tensorflow_datasets/core/community/register_path_test.py
  tensorflow_datasets/core/load.py
  tensorflow_datasets/core/naming.py
  tensorflow_datasets/core/naming_test.py
  tensorflow_datasets/core/read_only_builder.py
  tensorflow_datasets/core/utils/__init__.py
  tensorflow_datasets/scripts/cli/build.py
  tensorflow_datasets/scripts/documentation/dataset_markdown_builder.py
  tensorflow_datasets/scripts/documentation/doc_utils.py
Labels: cla: no

#2876 Experimental nested dataset Feature.
  tensorflow_datasets/core/features/__init__.py
  tensorflow_datasets/core/features/class_label_feature.py
  tensorflow_datasets/core/features/dataset_feature.py
  tensorflow_datasets/core/features/dataset_feature_test.py
  tensorflow_datasets/core/features/feature.py
  tensorflow_datasets/core/features/sequence_feature.py
  tensorflow_datasets/core/features/top_level_feature.py
  tensorflow_datasets/testing/feature_test_case.py
Labels: cla: no

#2883 Add a `Size` utils.
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/dataset_info_test.py
  tensorflow_datasets/core/download/checksums.py
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/downloader.py
  tensorflow_datasets/core/units.py
  tensorflow_datasets/core/units_test.py
  tensorflow_datasets/core/utils/__init__.py
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/scripts/documentation/dataset_markdown_builder.py
Labels: cla: no

#2882 Display expected checksum info when non matching checksum is raised
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/units.py
  tensorflow_datasets/core/units_test.py
Labels: cla: no

#2895 Remove bottleneck in C4 pipeline.
  tensorflow_datasets/text/c4.py
Labels: cla: no

#2897 Further increase parallelism of c4 download stage.
  tensorflow_datasets/text/c4.py
Labels: cla: no
