Repository tensorflow/datasets, pull requests merged in 2020-05, with the labels that each got.

#1981 Disable progression bar for documentation
  tensorflow_datasets/core/utils/tqdm_utils.py
Labels: cla: no

#1982 Cleanup proto imports
  tensorflow_datasets/core/proto/__init__.py
  tensorflow_datasets/proto/__init__.py
Labels: cla: no

#1984 Update wiki40b builder config names
  tensorflow_datasets/text/wiki40b.py
  tensorflow_datasets/text/wiki40b_test.py
Labels: cla: no

#1983 Disable TFDV statistics computation for dataset tests
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: no

#1990 Export CFQConfig. Useful to load custom splits.
  tensorflow_datasets/text/__init__.py
Labels: cla: no

#1985 Fix or ignore type errors generated by the next release of pytype.
  tensorflow_datasets/core/api_utils.py
Labels: cla: no

#1992 Merge of PR #1979
  tensorflow_datasets/image_classification/oxford_iiit_pet.py
  tensorflow_datasets/image_classification/visual_domain_decathlon.py
  tensorflow_datasets/url_checksums/oxford_iiit_pet.txt
  tensorflow_datasets/url_checksums/visual_domain_decathlon.txt
Labels: cla: no

#1993 Remove `num_parallel_call=1` from `TFRecordDataset`
  tensorflow_datasets/core/tfrecords_reader.py
Labels: cla: no

#1991 Start adding pytype support
  tensorflow_datasets/audio/savee.py
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/download/extractor.py
  tensorflow_datasets/core/download/resource.py
  tensorflow_datasets/core/features/sequence_feature.py
  tensorflow_datasets/core/features/text/text_encoder.py
  tensorflow_datasets/core/features/text_feature.py
  tensorflow_datasets/core/features/translation_feature.py
  tensorflow_datasets/core/proto/__init__.py
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/image_classification/caltech_birds.py
  tensorflow_datasets/image_classification/geirhos_conflict_stimuli.py
  tensorflow_datasets/object_detection/waymo_open_dataset.py
  tensorflow_datasets/testing/dataset_builder_testing.py
  tensorflow_datasets/testing/fake_data_generation/dsprites.py
  tensorflow_datasets/testing/fake_data_generation/e2e_binary.py
  tensorflow_datasets/testing/fake_data_generation/imagenet.py
  tensorflow_datasets/testing/fake_data_generation/kitti.py
  tensorflow_datasets/testing/fake_data_generation/lsun.py
  tensorflow_datasets/testing/fake_data_generation/sun397.py
  tensorflow_datasets/testing/fake_data_generation/voc2007.py
  tensorflow_datasets/text/c4_utils.py
  tensorflow_datasets/text/super_glue.py
  tensorflow_datasets/text/wikipedia.py
  tensorflow_datasets/translate/wmt.py
  tensorflow_datasets/video/bair_robot_pushing.py
Labels: cla: no

#1995 Update oxford_iii_pet and visual_domain_decathlon checksums (Fix #1978)
  tensorflow_datasets/image_classification/oxford_iiit_pet.py
  tensorflow_datasets/image_classification/visual_domain_decathlon.py
  tensorflow_datasets/url_checksums/oxford_iiit_pet.txt
  tensorflow_datasets/url_checksums/visual_domain_decathlon.txt
Labels: cla: no

#1988 Update "introduction" documentation
  docs/_index.ipynb
  docs/_index.yaml
  docs/overview.ipynb
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/registered.py
Labels: cla: no

#1997 Add read_config option to shard before interleave (Fix #1426)
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/tfrecords_reader_test.py
  tensorflow_datasets/core/utils/read_config.py
Labels: cla: no

#1989 Add VoxForge dataset to tfds
  tensorflow_datasets/audio/__init__.py
  tensorflow_datasets/audio/voxforge.py
  tensorflow_datasets/audio/voxforge_test.py
  tensorflow_datasets/testing/test_data/fake_examples/voxforge/urls_list.txt
  tensorflow_datasets/testing/test_data/fake_examples/voxforge/www.repository.voxforge1.org/downloads/es/Trunk/Audio/Main/16kHz_16bit/speaker1-10-1.tgz
  tensorflow_datasets/testing/test_data/fake_examples/voxforge/www.repository.voxforge1.org/downloads/es/Trunk/Audio/Main/16kHz_16bit/speaker2-20-1.tgz
  tensorflow_datasets/testing/test_data/fake_examples/voxforge/www.repository.voxforge1.org/downloads/ru/Trunk/Audio/Main/16kHz_16bit/speaker3-30-1.tgz
  tensorflow_datasets/testing/test_data/fake_examples/voxforge/www.repository.voxforge1.org/downloads/ru/Trunk/Audio/Main/16kHz_16bit/speaker4-40-1.tgz
Labels: cla: no

#2001 Allow --module_imports as comma separated values.
  tensorflow_datasets/scripts/download_and_prepare.py
Labels: cla: no

#2003 Fix checksums for Vox dataset.
  tensorflow_datasets/url_checksums/voxforge.txt
Labels: cla: no

#2008 Internal
  tensorflow_datasets/testing/test_case.py
Labels: cla: no

#1999 Fix typo in example usage of tfds.core.ReadInstruction.
  tensorflow_datasets/core/tfrecords_reader.py
Labels: cla: no

#2009 Drop Py2 support for download_and_prepare
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_beam_test.py
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/dataset_info_test.py
  tensorflow_datasets/core/splits_test.py
Labels: cla: no

#2007 Add validation set for CFQ.
  tensorflow_datasets/testing/test_data/fake_examples/cfq/cfq/splits/mcd1.json
  tensorflow_datasets/text/cfq.py
  tensorflow_datasets/text/cfq_test.py
Labels: cla: no

#1996 Make checksums validation optional
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/download_manager_test.py
  tensorflow_datasets/core/download/downloader.py
  tensorflow_datasets/scripts/download_and_prepare.py
Labels: cla: no

#2005 Add pytype to checksums and use `UrlInfo` instead of `tuple`
  tensorflow_datasets/core/download/checksums.py
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/download_manager_test.py
  tensorflow_datasets/core/download/downloader.py
  tensorflow_datasets/core/download/downloader_test.py
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: yes

#2013 Cleanup download_manager_test
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/download_manager_test.py
  tensorflow_datasets/testing/__init__.py
  tensorflow_datasets/testing/test_utils.py
  tensorflow_datasets/testing/test_utils_test.py
Labels: cla: no

#2014 Always cache download, even without checksums
  tensorflow_datasets/core/download/checksums.py
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/download_manager_test.py
  tensorflow_datasets/core/download/resource.py
Labels: cla: no

#2018 Move threads utils to py_utils
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/downloader.py
  tensorflow_datasets/core/download/resource.py
  tensorflow_datasets/core/download/util.py
  tensorflow_datasets/core/utils/py_utils.py
Labels: cla: no

#2025 Fix UrlInfo issue with dl_manager
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/download_manager_test.py
Labels: cla: no

#2023 Make it easy to load CFQ compound divergence splits.
  tensorflow_datasets/text/cfq.py
Labels: cla: no

#2027 Add the Adversarial NLI (ANLI) Text Dataset to TFDS.
  tensorflow_datasets/testing/test_data/fake_examples/anli/anli_v0.1/R3/dev.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/anli/anli_v0.1/R3/test.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/anli/anli_v0.1/R3/train.jsonl
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/anli.py
  tensorflow_datasets/text/anli_test.py
  tensorflow_datasets/url_checksums/anli.txt
Labels: cla: no

#2020 Cleanup downloader code
  tensorflow_datasets/core/download/downloader.py
  tensorflow_datasets/core/download/downloader_test.py
Labels: cla: no

#2028 Update tfds_dir documentation
  tensorflow_datasets/core/utils/py_utils.py
Labels: cla: no

#2029 Add generate catalog script
  tensorflow_datasets/scripts/document_datasets.py
  tensorflow_datasets/scripts/documentation/build_catalog.py
Labels: cla: no

#2031 Add mctaco to tfds
  tensorflow_datasets/testing/test_data/fake_examples/mctaco/dev_3783.tsv
  tensorflow_datasets/testing/test_data/fake_examples/mctaco/test_9942.tsv
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/mctaco.py
  tensorflow_datasets/text/mctaco_test.py
  tensorflow_datasets/url_checksums/mctaco.txt
Labels: cla: no

#2030 Add Winogrande dataset to tfds
  tensorflow_datasets/testing/test_data/fake_examples/winogrande/winogrande_1.1/dev.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/winogrande/winogrande_1.1/test.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/winogrande/winogrande_1.1/train_l.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/winogrande/winogrande_1.1/train_m.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/winogrande/winogrande_1.1/train_s.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/winogrande/winogrande_1.1/train_xl.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/winogrande/winogrande_1.1/train_xs.jsonl
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/winogrande.py
  tensorflow_datasets/text/winogrande_test.py
  tensorflow_datasets/url_checksums/winogrande.txt
Labels: cla: no

#2032 Add cosmos_qa to tfds
  tensorflow_datasets/testing/test_data/fake_examples/cosmos_qa/test.jsonl
  tensorflow_datasets/testing/test_data/fake_examples/cosmos_qa/train.csv
  tensorflow_datasets/testing/test_data/fake_examples/cosmos_qa/valid.csv
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/cosmos_qa.py
  tensorflow_datasets/text/cosmos_qa_test.py
  tensorflow_datasets/url_checksums/cosmos_qa.txt
Labels: cla: no

#2034 Internal
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no

#2037 Add `gcs_path` util function
  tensorflow_datasets/core/__init__.py
  tensorflow_datasets/core/constants.py
  tensorflow_datasets/core/registered.py
  tensorflow_datasets/core/utils/__init__.py
  tensorflow_datasets/core/utils/gcs_utils.py
  tensorflow_datasets/scripts/document_datasets.py
  tensorflow_datasets/scripts/generate_visualization.py
  tensorflow_datasets/text/wiki40b.py
Labels: cla: no

#2038 Display pip packages to help debugging.
  oss_scripts/oss_pip_install.sh
  oss_scripts/oss_tests.sh
Labels: cla: no

#2043 Fix documentation formatting issue.
  tensorflow_datasets/image_classification/bigearthnet.py
Labels: cla: no

#2047 Fix key error on ReadConfig (Fix #2046)
  tensorflow_datasets/core/utils/read_config.py
Labels: cla: no

#2044 Use dataclass rather than dict for file instructions
  tensorflow_datasets/core/_sharded_files_test.py
  tensorflow_datasets/core/hashing.py
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/core/splits_test.py
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/tfrecords_reader_test.py
  tensorflow_datasets/core/tfrecords_writer.py
  tensorflow_datasets/core/tfrecords_writer_test.py
  tensorflow_datasets/core/utils/shard_utils.py
  tensorflow_datasets/core/utils/shard_utils_test.py
Labels: cla: no

#2050 Fiter gcs_utils test on 1.15
  oss_scripts/oss_tests.sh
Labels: cla: no

#2055 Fix typo in mock_data error message.
  tensorflow_datasets/testing/mocking.py
Labels: cla: no

#2012 add opinion abstracts
  tensorflow_datasets/summarization/__init__.py
  tensorflow_datasets/summarization/opinion_abstracts.py
  tensorflow_datasets/summarization/opinion_abstracts_test.py
  tensorflow_datasets/testing/test_data/fake_examples/opinion_abstracts/opinion_abstracts/idebate.json
  tensorflow_datasets/testing/test_data/fake_examples/opinion_abstracts/opinion_abstracts/rottentomatoes.json
  tensorflow_datasets/url_checksums/opinion_abstracts.txt
Labels: cla: no

#2049 Move docs scripts to scripts/documentation/
  oss_scripts/oss_tests.sh
  setup.py
  tensorflow_datasets/scripts/documentation/__init__.py
  tensorflow_datasets/scripts/documentation/build_api_docs.py
  tensorflow_datasets/scripts/documentation/build_api_docs_test.py
  tensorflow_datasets/scripts/documentation/build_catalog.py
  tensorflow_datasets/scripts/documentation/document_datasets.py
  tensorflow_datasets/scripts/documentation/document_datasets_test.py
  tensorflow_datasets/scripts/documentation/templates/catalog_overview.mako.md
  tensorflow_datasets/scripts/documentation/templates/dataset.mako.md
  tensorflow_datasets/scripts/documentation/templates/schema_org.mako.md
Labels: cla: no

#1384 Add NYU Depth V2 dataset
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/nyu_depth_v2.py
  tensorflow_datasets/image/nyu_depth_v2_test.py
  tensorflow_datasets/testing/fake_data_generation/nyu_depth_v2.py
  tensorflow_datasets/testing/test_data/fake_examples/nyu_depth_v2/nyudepthv2/train/scene_0001/00001.h5
  tensorflow_datasets/testing/test_data/fake_examples/nyu_depth_v2/nyudepthv2/train/scene_0001/00002.h5
  tensorflow_datasets/testing/test_data/fake_examples/nyu_depth_v2/nyudepthv2/val/official/00001.h5
  tensorflow_datasets/url_checksums/nyu_depth_v2.txt
Labels: author:kokoro_test_failed, cla: yes, dataset request

#2057 Move generate_visualization -> scripts/documentation/
  tensorflow_datasets/scripts/documentation/generate_visualization.py
Labels: cla: no

#2058 Change image encoding for random dataset generator from PNG to JPEG for imagenet image classification datasets.
  tensorflow_datasets/image/downsampled_imagenet.py
  tensorflow_datasets/image_classification/imagenet.py
  tensorflow_datasets/image_classification/imagenette.py
  tensorflow_datasets/testing/metadata/downsampled_imagenet/32x32/2.0.0/image.image.json
  tensorflow_datasets/testing/metadata/downsampled_imagenet/64x64/2.0.0/image.image.json
  tensorflow_datasets/testing/metadata/imagenet2012/5.0.0/image.image.json
  tensorflow_datasets/testing/metadata/imagenette/160px-v2/0.1.0/image.image.json
  tensorflow_datasets/testing/metadata/imagenette/160px/0.1.0/image.image.json
  tensorflow_datasets/testing/metadata/imagenette/320px-v2/0.1.0/image.image.json
  tensorflow_datasets/testing/metadata/imagenette/320px/0.1.0/image.image.json
  tensorflow_datasets/testing/metadata/imagenette/full-size-v2/0.1.0/image.image.json
  tensorflow_datasets/testing/metadata/imagenette/full-size/0.1.0/image.image.json
Labels: cla: no
