Repository tensorflow/datasets, pull requests merged in 2021-02, with the labels that each got.

#3005 Fix ag_news_subset checksum
  tensorflow_datasets/url_checksums/ag_news_subset.txt
Labels: cla: yes, tfds:please_review

#3001 Avoid extra copy with `tfds.as_numpy()`
  tensorflow_datasets/core/dataset_utils.py
Labels: cla: no

#3002 Read correctly index PNG in Davis.
  tensorflow_datasets/video/davis/davis.py
  tensorflow_datasets/video/davis/davis_test.py
  tensorflow_datasets/video/davis/dummy_data/DAVIS/Annotations/480p/bear/00000.png
  tensorflow_datasets/video/davis/dummy_data/DAVIS/Annotations/480p/bear/00001.png
  tensorflow_datasets/video/davis/dummy_data/DAVIS/Annotations/480p/bear/00002.png
  tensorflow_datasets/video/davis/dummy_data/DAVIS/Annotations/480p/bear/00003.png
  tensorflow_datasets/video/davis/dummy_data/DAVIS/Annotations/480p/bike-packing/00000.png
  tensorflow_datasets/video/davis/dummy_data/DAVIS/Annotations/480p/bike-packing/00001.png
  tensorflow_datasets/video/davis/dummy_data/DAVIS/Annotations/480p/bike-packing/00002.png
  tensorflow_datasets/video/davis/dummy_data/DAVIS/Annotations/480p/bike-packing/00003.png
  tensorflow_datasets/video/davis/dummy_data/DAVIS/Annotations/Full-Resolution/bear/00000.png
  tensorflow_datasets/video/davis/dummy_data/DAVIS/Annotations/Full-Resolution/bear/00001.png
  tensorflow_datasets/video/davis/dummy_data/DAVIS/Annotations/Full-Resolution/bear/00002.png
  tensorflow_datasets/video/davis/dummy_data/DAVIS/Annotations/Full-Resolution/bear/00003.png
  tensorflow_datasets/video/davis/dummy_data/DAVIS/Annotations/Full-Resolution/bike-packing/00000.png
  tensorflow_datasets/video/davis/dummy_data/DAVIS/Annotations/Full-Resolution/bike-packing/00001.png
  tensorflow_datasets/video/davis/dummy_data/DAVIS/Annotations/Full-Resolution/bike-packing/00002.png
  tensorflow_datasets/video/davis/dummy_data/DAVIS/Annotations/Full-Resolution/bike-packing/00003.png
Labels: cla: no

#3009 `tfds.benchmark` improvements:
  docs/performances.md
  tensorflow_datasets/core/__init__.py
  tensorflow_datasets/core/utils/benchmark.py
  tensorflow_datasets/core/utils/benchmark_test.py
  tensorflow_datasets/public_api.py
Labels: cla: no

#3011 Fix error when using config with beam
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: no

#3014 Fix waymo open dataset proto import.
  tensorflow_datasets/proto/__init__.py
Labels: cla: no

#3007 Added LSUN objects datasets to TFDS.
  tensorflow_datasets/image/lsun.py
  tensorflow_datasets/url_checksums/lsun.txt
Labels: cla: no

#3019 Better error message for non-matching checksums
  tensorflow_datasets/core/download/download_manager.py
Labels: cla: no

#3012 Add the *-CFQ dataset suite to TFDS.
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/star_cfq/__init__.py
  tensorflow_datasets/text/star_cfq/checksums.tsv
  tensorflow_datasets/text/star_cfq/dummy_data/b-cfq-1.0-compact/dataset_000.json
  tensorflow_datasets/text/star_cfq/dummy_data/divergence_splits/divergence_split_s0.1_d0.3_r4.25_0.json
  tensorflow_datasets/text/star_cfq/dummy_data/random_splits/train_10x_b_cfq__test_1x_b_cfq.json
  tensorflow_datasets/text/star_cfq/dummy_data/random_splits/train_1x_b_cfq_1x_x_cfq__test_1x_b_cfq.json
  tensorflow_datasets/text/star_cfq/dummy_data/u-cfq-for-divergence-splits-1.0-compact-combined/dataset.json
  tensorflow_datasets/text/star_cfq/dummy_data/x-cfq-1.0-compact/dataset_000.json
  tensorflow_datasets/text/star_cfq/star_cfq.py
  tensorflow_datasets/text/star_cfq/star_cfq_test.py
Labels: cla: no

#3021 Add missing checksum for datasets/cfq-1.0-compact.tar.gz in *-CFQ.
  tensorflow_datasets/text/star_cfq/checksums.tsv
Labels: cla: no

#3027 Fix race condition during extraction
  tensorflow_datasets/core/download/extractor.py
Labels: cla: no

#3023 Add warning to oxford_flowers102 dataset
  tensorflow_datasets/image_classification/oxford_flowers102.py
Labels: cla: yes, community:please_review

#3029 Add tfds.benchmark to __all__
  tensorflow_datasets/public_api.py
Labels: cla: no

#3028 Clip TAO bounding boxes to be within image boundary. Rename TAO "baby" category to "human."
  tensorflow_datasets/video/tao/labels.txt
  tensorflow_datasets/video/tao/tao.py
Labels: cla: no

#3010 Add doc for tfds.benchmark
  docs/cli.ipynb
  docs/keras_example.ipynb
  docs/overview.ipynb
Labels: cla: no

#3024 Add youtube-vis dataset to TFDS.
  setup.py
  tensorflow_datasets/core/lazy_imports_lib.py
  tensorflow_datasets/core/lazy_imports_lib_test.py
  tensorflow_datasets/video/__init__.py
  tensorflow_datasets/video/youtube_vis/__init__.py
  tensorflow_datasets/video/youtube_vis/dummy_data/test.json
  tensorflow_datasets/video/youtube_vis/dummy_data/test_all_frames.zip
  tensorflow_datasets/video/youtube_vis/dummy_data/train.json
  tensorflow_datasets/video/youtube_vis/dummy_data/train_all_frames.zip
  tensorflow_datasets/video/youtube_vis/dummy_data/valid.json
  tensorflow_datasets/video/youtube_vis/dummy_data/valid_all_frames.zip
  tensorflow_datasets/video/youtube_vis/labels.txt
  tensorflow_datasets/video/youtube_vis/youtube_vis.py
  tensorflow_datasets/video/youtube_vis/youtube_vis_test.py
Labels: cla: no

#3032 Add `num_shards` to subsplit info
  tensorflow_datasets/core/splits.py
  tensorflow_datasets/core/splits_test.py
Labels: cla: no

#3038 Fix as_dataframe for Sequence(Video)
  tensorflow_datasets/core/features/feature.py
Labels: cla: no

#3041 Add a HuggingFace compatibility wrapper
  tensorflow_datasets/core/community/__init__.py
  tensorflow_datasets/core/community/huggingface_wrapper.py
  tensorflow_datasets/core/community/huggingface_wrapper_test.py
  tensorflow_datasets/core/community/load.py
  tensorflow_datasets/testing/huggingface/dummy_dataset.py
Labels: cla: no

#3042 Make DatasetName comparable (to allow sort ds per ns:name)
  tensorflow_datasets/core/naming.py
  tensorflow_datasets/core/naming_test.py
Labels: cla: no

#3044 Attempt to fix dummy_dataset_test conflict with api_docs
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: no

#3039 Make DatasetPackage public (as it is used in the package index export script)
  tensorflow_datasets/core/community/register_package.py
  tensorflow_datasets/core/community/register_package_test.py
Labels: cla: no

#3040 Add script to update the community package index
  tensorflow_datasets/community-datasets.toml
  tensorflow_datasets/scripts/deployment/export_community_datasets.py
  tensorflow_datasets/scripts/deployment/export_community_datasets_test.py
Labels: cla: no

#3043 Update testing metadata of lm1b.
  tensorflow_datasets/testing/metadata/lm1b/1.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/lm1b/bytes/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/lm1b/bytes/1.0.0/text.text.bytes
  tensorflow_datasets/testing/metadata/lm1b/plain_text/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/lm1b/subwords32k/1.0.0/text.text.subwords
  tensorflow_datasets/testing/metadata/lm1b/subwords8k/1.0.0/dataset_info.json
  tensorflow_datasets/testing/metadata/lm1b/subwords8k/1.0.0/text.text.subwords
Labels: cla: no

#3045 parallelize list_builder over namespaces
  tensorflow_datasets/core/community/register_path.py
Labels: cla: yes, community:please_review

#3048 Add `add_tfds_id` support to `mock_data`
  tensorflow_datasets/testing/mocking.py
  tensorflow_datasets/testing/mocking_test.py
Labels: cla: no

#3049 Fix typo (Feature*s*Dict)
  docs/add_dataset.md
Labels: cla: yes

#3050 Remove smaller compound divergence sizes from the star_cfq dataset suite.
  tensorflow_datasets/text/star_cfq/dummy_data/divergence_splits/divergence_split_s0.333333_d0.3_r4.25_0.json
  tensorflow_datasets/text/star_cfq/star_cfq.py
  tensorflow_datasets/text/star_cfq/star_cfq_test.py
Labels: cla: no

#3051 fixed a few typos in the documentation where instead of `tfds.features.X` it said `tfds.feature.X`.
  docs/features.md
  tensorflow_datasets/core/example_serializer.py
  tensorflow_datasets/core/features/bounding_boxes.py
  tensorflow_datasets/core/features/dataset_feature.py
Labels: cla: no

#2991 Add Open Graph Benchmark dataset 'ogbg-molpcba' to Tensorflow Datasets.
  setup.py
  tensorflow_datasets/__init__.py
  tensorflow_datasets/graphs/__init__.py
  tensorflow_datasets/graphs/ogbg_molpcba/__init__.py
  tensorflow_datasets/graphs/ogbg_molpcba/checksums.tsv
  tensorflow_datasets/graphs/ogbg_molpcba/dummy_data/pcba/raw/edge-feat.csv.gz
  tensorflow_datasets/graphs/ogbg_molpcba/dummy_data/pcba/raw/edge.csv.gz
  tensorflow_datasets/graphs/ogbg_molpcba/dummy_data/pcba/raw/graph-label.csv.gz
  tensorflow_datasets/graphs/ogbg_molpcba/dummy_data/pcba/raw/node-feat.csv.gz
  tensorflow_datasets/graphs/ogbg_molpcba/dummy_data/pcba/raw/num-edge-list.csv.gz
  tensorflow_datasets/graphs/ogbg_molpcba/dummy_data/pcba/raw/num-node-list.csv.gz
  tensorflow_datasets/graphs/ogbg_molpcba/dummy_data/pcba/split/scaffold/test.csv.gz
  tensorflow_datasets/graphs/ogbg_molpcba/dummy_data/pcba/split/scaffold/train.csv.gz
  tensorflow_datasets/graphs/ogbg_molpcba/dummy_data/pcba/split/scaffold/valid.csv.gz
  tensorflow_datasets/graphs/ogbg_molpcba/dummy_data_generation.py
  tensorflow_datasets/graphs/ogbg_molpcba/ogbg_molpcba.py
  tensorflow_datasets/graphs/ogbg_molpcba/ogbg_molpcba_test.py
Labels: cla: no

#3058 Update imagenette checksums
  tensorflow_datasets/image_classification/imagenette.py
  tensorflow_datasets/url_checksums/imagenette.txt
Labels: cla: yes, community:please_review

#3055 Fix download manager when manual_dir is None
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/download_manager_test.py
Labels: cla: no

#3063 Fix UnicodeEncodeError error.
  tensorflow_datasets/question_answering/tydi_qa.py
Labels: cla: no

#3066 Updating version number for tydi_qa to reflect the addition of new translate-train-* splits.
  tensorflow_datasets/question_answering/tydi_qa.py
Labels: cla: no
