Repository tensorflow/datasets, pull requests merged in 2021-04, with the labels that each got.

#3138 Show Examples blocks only for the first 100 configs to optimize page loading times for datasets with many builder configs.
  tensorflow_datasets/scripts/documentation/dataset_markdown_builder.py
Labels: cla: no

#3145 Fixed a spelling mistake in the contribution guidelines document
  docs/contribute.md
Labels: cla: yes, tfds:please_review

#3140 [tfds]: Significant fix for TyDiQA (and to a smaller extent XQuAD).
  tensorflow_datasets/question_answering/qa_utils.py
  tensorflow_datasets/question_answering/qa_utils_test.py
  tensorflow_datasets/question_answering/squad/squad.py
  tensorflow_datasets/question_answering/tydi_qa.py
  tensorflow_datasets/question_answering/xquad.py
  tensorflow_datasets/testing/test_data/fake_examples/xquad/translate-test.json
Labels: cla: no

#3146 Add CivilCommentsCovert config for CivilComments
  tensorflow_datasets/testing/test_data/fake_examples/civil_comments/test_private_expanded.csv
  tensorflow_datasets/testing/test_data/fake_examples/civil_comments/train.csv
  tensorflow_datasets/text/civil_comments.py
  tensorflow_datasets/text/civil_comments_test.py
  tensorflow_datasets/url_checksums/civil_comments.txt
Labels: cla: no

#3135 Add ability to derive the validation and testing splits from the training data for youtube_vis.
  tensorflow_datasets/video/youtube_vis/youtube_vis.py
  tensorflow_datasets/video/youtube_vis/youtube_vis_test.py
Labels: cla: no

#3141 Add `neg_category_ids` and `not_exhaustive_category_ids` to LVIS dataset.
  tensorflow_datasets/object_detection/lvis/lvis.py
Labels: cla: no

#3149 Add necessary gtzan extras
  setup.py
Labels: cla: yes

#3142 Update documentation with a new url util
  tensorflow_datasets/scripts/documentation/dataset_markdown_builder.py
  tensorflow_datasets/scripts/documentation/doc_utils.py
  tensorflow_datasets/scripts/documentation/doc_utils_test.py
  tensorflow_datasets/scripts/documentation/document_datasets.py
Labels: cla: no

#3153 TFDS: DatasetBuilder.as_dataset: add pytype annotations.
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#3147 add a logging hook, to be specified through a Logger class.
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_read_test.py
  tensorflow_datasets/core/logging/__init__.py
  tensorflow_datasets/core/logging/base_logger.py
  tensorflow_datasets/core/logging/logging_logger.py
Labels: cla: no

#3156 Minor error message clarification when dataset isn't found
  tensorflow_datasets/core/read_only_builder.py
Labels: cla: no

#3161 Fix future typing error
  tensorflow_datasets/core/features/feature.py
Labels: cla: no

#3157 Load metadata from metadata.json if there is any
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/dataset_info_test.py
Labels: cla: yes

#3165 Add new patch correcting checksum for CivilComments with Covert data
  tensorflow_datasets/text/civil_comments.py
  tensorflow_datasets/url_checksums/civil_comments.txt
Labels: cla: no

#3167 Enable custom decoding in the nested dataset feature.
  tensorflow_datasets/core/features/dataset_feature_test.py
  tensorflow_datasets/core/features/top_level_feature.py
Labels: cla: no

#3166 No-op.
  tensorflow_datasets/core/lazy_imports_lib.py
Labels: cla: no

#3169 Add class names for LVIS.
  tensorflow_datasets/object_detection/lvis/lvis.py
  tensorflow_datasets/object_detection/lvis/lvis_classes.txt
Labels: cla: no

#3168 Adds D4RL HalfCheetah to TFDS
  tensorflow_datasets/__init__.py
  tensorflow_datasets/d4rl/__init__.py
  tensorflow_datasets/d4rl/d4rl_mujoco_halfcheetah/__init__.py
  tensorflow_datasets/d4rl/d4rl_mujoco_halfcheetah/checksums.tsv
  tensorflow_datasets/d4rl/d4rl_mujoco_halfcheetah/d4rl_mujoco_halfcheetah.py
  tensorflow_datasets/d4rl/d4rl_mujoco_halfcheetah/d4rl_mujoco_halfcheetah_test.py
  tensorflow_datasets/d4rl/d4rl_mujoco_halfcheetah/dummy_data/halfcheetah_medium.hdf5
  tensorflow_datasets/d4rl/dataset_utils.py
Labels: cla: no

#3174 Allow to express nested datasets as dicts of lists.
  tensorflow_datasets/core/features/dataset_feature.py
  tensorflow_datasets/core/features/dataset_feature_test.py
  tensorflow_datasets/core/features/sequence_feature.py
Labels: cla: no

#3178 Make lookup tables initializable in graph mode with tfds.as_numpy.
  tensorflow_datasets/core/dataset_utils.py
Labels: cla: no

#3179 TFDS: fix imagenet_r, file_name feature: absolute path (setup dependant) => relative path of images.
  tensorflow_datasets/image_classification/imagenet_r.py
  tensorflow_datasets/image_classification/imagenet_r_test.py
Labels: cla: no

#3184 TFDS: fix imagenet_v2, file_name feature: absolute path (setup dependant) => relative path of images.
  tensorflow_datasets/image_classification/imagenet_v2.py
Labels: cla: no

#3187 Instead of using experimental_stats to check that `tf.data.Options` are properly set, use experimental_slack. The tf.data.experimental.StatsAggregator has been deprecated.
  tensorflow_datasets/core/dataset_builder_test.py
Labels: cla: no

#3188 Fix kokoro import error
  tensorflow_datasets/structured/dart/dart_test.py
  tensorflow_datasets/structured/web_nlg/web_nlg_test.py
  tensorflow_datasets/structured/wiki_table_questions/wiki_table_questions_test.py
  tensorflow_datasets/structured/wiki_table_text/wiki_table_text_test.py
Labels: cla: no

#3181 Add citation for CivilCommentsCovert separate from main CivilComments citation
  tensorflow_datasets/text/civil_comments.py
Labels: cla: no

#3176 Exceptions check
  tensorflow_datasets/scripts/documentation/document_datasets.py
Labels: cla: no

#3180 Small refactor of the dataset utils
  tensorflow_datasets/d4rl/dataset_utils.py
Labels: cla: no

#3192 Fix python formatting
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_test.py
  tensorflow_datasets/core/shuffle.py
  tensorflow_datasets/core/split_builder.py
  tensorflow_datasets/core/tfrecords_writer.py
  tensorflow_datasets/core/tfrecords_writer_test.py
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no
