Repository tensorflow/datasets, pull requests merged in 2021-01, with the labels that each got.

#2884 Fix `read_checksum_digest` -> `compute_url_info` to return UrlInfo
  tensorflow_datasets/core/download/checksums.py
  tensorflow_datasets/core/download/checksums_test.py
  tensorflow_datasets/core/download/download_manager.py
  tensorflow_datasets/core/download/downloader.py
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/core/utils/py_utils_test.py
Labels: cla: no

#2908 Minor manual_dir usage clarification
  docs/add_dataset.md
Labels: cla: no

#2898 Add pyyaml dependency
  setup.py
Labels: cla: yes, tfds:please_review

#2907 Update progression bar when download through copy (Fix #2899)
  tensorflow_datasets/core/download/downloader.py
Labels: cla: no

#2906 Recording checksums according to dataset structure
  tensorflow_datasets/core/dataset_builder.py
Labels: author:kokoro_test_failed, cla: yes

#2910 Update wikipedia checksums
  tensorflow_datasets/url_checksums/wikipedia.txt
Labels: cla: no

#2904 Update URL and version for citrus leaves dataset
  tensorflow_datasets/image_classification/citrus.py
  tensorflow_datasets/url_checksums/citrus_leaves.txt
Labels: cla: yes, tfds:ready_to_merge

#2913 Clarification about --manual_dir in add_dataset
  docs/add_dataset.md
Labels: cla: no

#2896 Update imagenet_v2 dataset
  tensorflow_datasets/image_classification/imagenet_v2.py
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7-format-val/125/3.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7-format-val/125/4.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7-format-val/125/5.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7-format-val/42/1.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7-format-val/42/2.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7-format-val/999/10.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7-format-val/999/6.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7-format-val/999/7.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7-format-val/999/8.jpeg
  tensorflow_datasets/testing/test_data/fake_examples/imagenet_v2/imagenetv2-threshold0.7-format-val/999/9.jpeg
  tensorflow_datasets/url_checksums/imagenet_v2.txt
Labels: cla: yes, tfds:please_review

#2914 Fix `list_full_names` for datasets with shared VERSION across `BUILDER_CONFIG`
  tensorflow_datasets/core/load.py
Labels: cla: no

#2915 Document builder configs even when default config not defined.
  tensorflow_datasets/core/community/register_path.py
  tensorflow_datasets/scripts/documentation/document_datasets.py
Labels: cla: no

#2919 Downloading from GCS is a info message, rather than warning
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#2920 Fix _checksums_path for zipapp
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#2912 Update TFDS to 4.2.0
  tensorflow_datasets/stable_versions.txt
  tensorflow_datasets/version.py
  tensorflow_datasets/version_stable.py
Labels: cla: no

#2921 Fix doc for pip install command for zsh
  docs/contribute.md
Labels: cla: yes, tfds:ready_to_merge

#2928 Add google referring expression dataset.
  tensorflow_datasets/__init__py3.py
  tensorflow_datasets/vision_language/__init__.py
  tensorflow_datasets/vision_language/gref/__init__.py
  tensorflow_datasets/vision_language/gref/dummy_data/coco_train2014/COCO_train2014_000000181828.jpg
  tensorflow_datasets/vision_language/gref/dummy_data/coco_train2014/COCO_train2014_000000208256.jpg
  tensorflow_datasets/vision_language/gref/dummy_data/coco_train2014/COCO_train2014_000000307082.jpg
  tensorflow_datasets/vision_language/gref/dummy_data/coco_train2014/COCO_train2014_000000380440.jpg
  tensorflow_datasets/vision_language/gref/dummy_data/coco_train2014/COCO_train2014_000000519404.jpg
  tensorflow_datasets/vision_language/gref/dummy_data/coco_train2014/COCO_train2014_000000546154.jpg
  tensorflow_datasets/vision_language/gref/dummy_data/google_refexp_train_201511_coco_aligned_catg.json
  tensorflow_datasets/vision_language/gref/dummy_data/google_refexp_val_201511_coco_aligned_catg.json
  tensorflow_datasets/vision_language/gref/gref.py
  tensorflow_datasets/vision_language/gref/gref_test.py
Labels: cla: no

#2937 Update the link of colab in TFDS.
  tensorflow_datasets/image/celeba.py
  tensorflow_datasets/image/celebahq.py
Labels: cla: no

#2936 Fixed comment in TFDS feature.py.
  tensorflow_datasets/core/features/feature.py
Labels: cla: no

#2931 Fix downloader bug
  tensorflow_datasets/core/download/downloader.py
  tensorflow_datasets/core/download/downloader_test.py
Labels: cla: yes, tfds:ready_to_merge

#2932 Fix broken data urls for glue datasets
  tensorflow_datasets/text/glue.py
  tensorflow_datasets/url_checksums/glue.txt
Labels: cla: yes, tfds:ready_to_merge

#2933 Better Sun error when invalid image.
  tensorflow_datasets/image_classification/sun.py
Labels: cla: no

#2938 Remove py2 legacy `__init__`
  tensorflow_datasets/__init__.py
  tensorflow_datasets/__init__py2.py
  tensorflow_datasets/__init__py3.py
Labels: cla: no

#2939 Fix extraction error when archive contains bad symlink
  tensorflow_datasets/core/download/extractor.py
Labels: cla: no

#2941 Temporary rollback of glue version
  tensorflow_datasets/text/glue.py
Labels: cla: no

#2942 Fix name extraction when encoded `/` is present
  tensorflow_datasets/core/utils/py_utils.py
  tensorflow_datasets/core/utils/py_utils_test.py
  tensorflow_datasets/url_checksums/glue.txt
Labels: cla: no

#2934 Internal
  tensorflow_datasets/core/utils/gpath.py
Labels: cla: no

#2947 Add GPath.copy
  tensorflow_datasets/core/utils/gpath.py
  tensorflow_datasets/core/utils/gpath_test.py
  tensorflow_datasets/core/utils/type_utils.py
Labels: cla: no

#2943 Minor manual download clarification
  docs/overview.ipynb
Labels: cla: no

#2948 Add contextmanager to change visibility
  tensorflow_datasets/core/visibility.py
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: no

#2955 Add Efron-Morris baseball dataset.
  tensorflow_datasets/structured/__init__.py
  tensorflow_datasets/structured/efron_morris_75/__init__.py
  tensorflow_datasets/structured/efron_morris_75/checksums.tsv
  tensorflow_datasets/structured/efron_morris_75/dummy_data/efron-morris-75-data.tsv
  tensorflow_datasets/structured/efron_morris_75/efron_morris_75.py
  tensorflow_datasets/structured/efron_morris_75/efron_morris_75_test.py
Labels: cla: no, dataset request

#2945 Add a community register
  oss_scripts/oss_tests.sh
  tensorflow_datasets/core/community/__init__.py
  tensorflow_datasets/core/community/cache.py
  tensorflow_datasets/core/community/dataset_sources.py
  tensorflow_datasets/core/community/load.py
  tensorflow_datasets/core/community/register_package.py
  tensorflow_datasets/core/community/register_package_test.py
  tensorflow_datasets/core/naming.py
  tensorflow_datasets/core/utils/gcs_utils.py
Labels: cla: no

#2949 Update tfds.load to support community datasets
  tensorflow_datasets/core/community/register_path.py
  tensorflow_datasets/core/load.py
  tensorflow_datasets/core/load_test.py
Labels: cla: no

#2956 updated dataset download link
  tensorflow_datasets/image_classification/bigearthnet.py
  tensorflow_datasets/url_checksums/bigearthnet.txt
Labels: cla: yes, tfds:ready_to_merge

#2965 Support as_dataframe visualization for Sequence(Image())
  tensorflow_datasets/core/features/image_feature.py
  tensorflow_datasets/core/features/video_feature.py
  tensorflow_datasets/core/utils/image_utils.py
Labels: cla: no

#2961 Obtimize import times (Fix #2959)
  tensorflow_datasets/core/as_dataframe.py
  tensorflow_datasets/core/utils/py_utils.py
Labels: cla: no

#2952 Internal
  tensorflow_datasets/scripts/documentation/document_datasets.py
Labels: cla: no

#2950 Add a `dummy_data` class property to DatasetBuilderTest
  tensorflow_datasets/object_detection/waymo_open_dataset_test.py
  tensorflow_datasets/testing/dataset_builder_testing.py
  tensorflow_datasets/translate/wmt_test.py
Labels: cla: no

#2968 Internal
  tensorflow_datasets/scripts/documentation/build_catalog.py
Labels: cla: no

#2963 Remap DAVIS dataset so masks are 1, 2, 3, .. etc instead of arbitrary colors.
  tensorflow_datasets/video/davis/davis.py
Labels: cla: no

#2977 Use gfile to copy DAVIS files to local temp directory.
  tensorflow_datasets/video/davis/davis.py
Labels: cla: no

#2980 Fix html tag visualization for Ragged Tensor
  tensorflow_datasets/core/features/feature.py
Labels: cla: yes, tfds:ready_to_merge

#2887 [ENC] Better `tfds.as_dataframe` visualization [2/2]
  tensorflow_datasets/core/features/feature.py
Labels: cla: yes, tfds:ready_to_merge

#2976 Update documentation generation
  tensorflow_datasets/core/read_only_builder.py
  tensorflow_datasets/core/registered.py
  tensorflow_datasets/core/visibility.py
  tensorflow_datasets/scripts/documentation/document_datasets.py
Labels: cla: no

#2985 Enables builder tests for datasets with nested datasets.
  tensorflow_datasets/core/dataset_utils.py
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: no

#2982 Added public API to enable tqdm corresponding to the one for closing it
  tensorflow_datasets/core/utils/tqdm_utils.py
  tensorflow_datasets/public_api.py
Labels: cla: yes, tfds:ready_to_merge

#2984 Better setup teardown registration
  tensorflow_datasets/conftest.py
  tensorflow_datasets/testing/setup_teardown.py
  tensorflow_datasets/testing/test_case.py
Labels: cla: no

#2990 added wmt13 for downloading wmt13 data, benchmark for Spanish
  tensorflow_datasets/translate/__init__.py
  tensorflow_datasets/translate/wmt.py
  tensorflow_datasets/translate/wmt13.py
Labels: cla: no

#2986 Add a pathlib-like util for Github
  tensorflow_datasets/core/github_api/__init__.py
  tensorflow_datasets/core/github_api/github_path.py
  tensorflow_datasets/core/github_api/github_path_test.py
  tensorflow_datasets/testing/setup_teardown.py
Labels: cla: no

#2988 Add GithubPath.as_raw_url()
  tensorflow_datasets/core/github_api/github_path.py
  tensorflow_datasets/core/github_api/github_path_test.py
Labels: cla: no

#2987 Add a GithubPath.read_bytes()
  tensorflow_datasets/core/github_api/github_path.py
  tensorflow_datasets/core/github_api/github_path_test.py
Labels: cla: no

#2993 Add copy method to GithubPath
  tensorflow_datasets/core/github_api/github_path.py
  tensorflow_datasets/core/github_api/github_path_test.py
Labels: cla: no

#2983 Support custom BuilderConfig in testing
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: yes, tfds:ready_to_merge

#2994 Add uri-registering mechanism to as_path
  tensorflow_datasets/core/github_api/github_path.py
  tensorflow_datasets/core/github_api/github_path_test.py
  tensorflow_datasets/core/utils/__init__.py
  tensorflow_datasets/core/utils/generic_path.py
  tensorflow_datasets/core/utils/generic_path_test.py
Labels: cla: no

#2995 Supports github packages and allow packages to contain multiple files.
  tensorflow_datasets/core/community/dataset_sources.py
  tensorflow_datasets/core/community/dataset_sources_test.py
  tensorflow_datasets/core/community/register_package.py
  tensorflow_datasets/core/community/register_package_test.py
  tensorflow_datasets/core/dataset_builder.py
Labels: cla: no

#2997 Fix typo in Video repr_html
  tensorflow_datasets/core/features/video_feature.py
  tensorflow_datasets/testing/feature_test_case.py
Labels: cla: no

#2998 Adding wmt13_translate.txt checksums
  tensorflow_datasets/url_checksums/wmt13_translate.txt
Labels: cla: no

#2999 Better benchmark (compatible with any iterator, better colab repr)
  tensorflow_datasets/core/__init__.py
  tensorflow_datasets/core/utils/benchmark.py
  tensorflow_datasets/core/utils/benchmark_test.py
Labels: cla: no
