Repository tensorflow/datasets, pull requests merged in 2021-06, with the labels that each got.

#3267 Add load-from-file support for custom feature connectors
  oss_scripts/oss_tests.sh
  tensorflow_datasets/core/features/feature.py
  tensorflow_datasets/core/features/features_test.py
  tensorflow_datasets/core/features/test_feature.py
Labels: cla: no

#3031 Update glue/qqp data source
  tensorflow_datasets/text/glue.py
  tensorflow_datasets/url_checksums/glue.txt
Labels: cla: yes, tfds:please_review

#3272 Add 1.0.x GLUE versions as supported.
  tensorflow_datasets/text/glue.py
Labels: cla: no

#3273 Fix typo in splits docs.
  docs/splits.md
Labels: cla: yes

#3270 Save/restore the file format in dataset_info.json
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_info.py
  tensorflow_datasets/core/dataset_info_test.py
  tensorflow_datasets/core/proto/dataset_info.proto
  tensorflow_datasets/core/proto/dataset_info_generated_pb2.py
Labels: cla: no

#3238 Add the ProteinNet dataset.
  tensorflow_datasets/bio/proteinnet/__init__.py
  tensorflow_datasets/bio/proteinnet/checksums.tsv
  tensorflow_datasets/bio/proteinnet/dummy_data/casp7/testing
  tensorflow_datasets/bio/proteinnet/dummy_data/casp7/training_100
  tensorflow_datasets/bio/proteinnet/dummy_data/casp7/validation
  tensorflow_datasets/bio/proteinnet/proteinnet.py
  tensorflow_datasets/bio/proteinnet/proteinnet_test.py
Labels: cla: no

#3274 Minor refactoring of FileAdapter
  tensorflow_datasets/core/file_adapters.py
  tensorflow_datasets/core/file_adapters_test.py
  tensorflow_datasets/core/shuffle.py
  tensorflow_datasets/core/shuffle_test.py
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/tfrecords_reader_test.py
  tensorflow_datasets/core/tfrecords_writer.py
  tensorflow_datasets/core/utils/type_utils.py
  tensorflow_datasets/testing/__init__.py
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no

#3277 Add FilenameInfo util to help conversions from/to filename
  tensorflow_datasets/core/naming.py
  tensorflow_datasets/core/naming_test.py
Labels: cla: no

#3282 Rollback of SSTable file adapter
  tensorflow_datasets/core/file_adapters.py
  tensorflow_datasets/core/file_adapters_test.py
  tensorflow_datasets/core/shuffle.py
  tensorflow_datasets/core/shuffle_test.py
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/tfrecords_reader_test.py
  tensorflow_datasets/core/tfrecords_writer.py
  tensorflow_datasets/core/utils/type_utils.py
  tensorflow_datasets/testing/__init__.py
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no

#3288 Minor refactoring of FileAdapter
  tensorflow_datasets/core/file_adapters.py
  tensorflow_datasets/core/file_adapters_test.py
  tensorflow_datasets/core/shuffle.py
  tensorflow_datasets/core/shuffle_test.py
  tensorflow_datasets/core/tfrecords_reader.py
  tensorflow_datasets/core/tfrecords_reader_test.py
  tensorflow_datasets/core/tfrecords_writer.py
  tensorflow_datasets/core/utils/type_utils.py
  tensorflow_datasets/testing/__init__.py
  tensorflow_datasets/testing/test_utils.py
Labels: cla: no

#3279 Add documentation for common mistakes
  docs/_book.yaml
  docs/add_dataset.md
  docs/common_gotchas.md
Labels: cla: no

#3278 Adds Symmetric Solids dataset ('symmetric_solids') to Tensorflow Datasets.
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image/symmetric_solids/__init__.py
  tensorflow_datasets/image/symmetric_solids/checksums.tsv
  tensorflow_datasets/image/symmetric_solids/dummy_data/test/images/cube_00000.png
  tensorflow_datasets/image/symmetric_solids/dummy_data/test/images/sphereX_00000.png
  tensorflow_datasets/image/symmetric_solids/dummy_data/test/images/tet_00000.png
  tensorflow_datasets/image/symmetric_solids/dummy_data/test/rotations.npz
  tensorflow_datasets/image/symmetric_solids/dummy_data/train/images/cube_00000.png
  tensorflow_datasets/image/symmetric_solids/dummy_data/train/images/cube_00001.png
  tensorflow_datasets/image/symmetric_solids/dummy_data/train/images/cube_00002.png
  tensorflow_datasets/image/symmetric_solids/dummy_data/train/images/sphereX_00000.png
  tensorflow_datasets/image/symmetric_solids/dummy_data/train/images/tet_00000.png
  tensorflow_datasets/image/symmetric_solids/dummy_data/train/images/tet_00001.png
  tensorflow_datasets/image/symmetric_solids/dummy_data/train/rotations.npz
  tensorflow_datasets/image/symmetric_solids/symmetric_solids.py
  tensorflow_datasets/image/symmetric_solids/symmetric_solids_test.py
Labels: cla: no

#3284 Update the link to the eval server.
  tensorflow_datasets/image_classification/imagenet.py
Labels: cla: no

#3283 internal
  tensorflow_datasets/core/logging/__init__.py
Labels: cla: no

#3289 Add script to compute split info metadata on a tfrecord files
  tensorflow_datasets/scripts/tools/compute_split_info.py
  tensorflow_datasets/scripts/tools/compute_split_info_test.py
Labels: cla: no

#3292 Move compute_splits utils to core/ to allow usage in user scripts
  tensorflow_datasets/core/folder_dataset/__init__.py
  tensorflow_datasets/core/folder_dataset/compute_split_utils.py
  tensorflow_datasets/core/folder_dataset/compute_split_utils_test.py
  tensorflow_datasets/core/lazy_imports_lib.py
  tensorflow_datasets/scripts/tools/compute_split_info.py
Labels: cla: no

#3293 Add util to add TFDS metadata into external tf-record files
  tensorflow_datasets/core/file_adapters.py
  tensorflow_datasets/core/folder_dataset/__init__.py
  tensorflow_datasets/core/folder_dataset/compute_split_utils.py
  tensorflow_datasets/core/folder_dataset/write_metadata_utils.py
  tensorflow_datasets/core/folder_dataset/write_metadata_utils_test.py
Labels: cla: no

#3297 Add common gotchas on dataset structure
  docs/common_gotchas.md
Labels: cla: no

#3294 Add documentation to load external TF records
  docs/_book.yaml
  docs/external_tfrecord.md
Labels: cla: no

#3295 Add tfrecord check in tfds.folder_dataset.write_metadata
  tensorflow_datasets/core/folder_dataset/write_metadata_utils.py
  tensorflow_datasets/core/read_only_builder.py
Labels: cla: no

#3303 Also fixes a Python 3.7 type error exposed by this change.
  tensorflow_datasets/core/naming.py
Labels: cla: no

#3298 Add global fixtures for dummy datasets
  tensorflow_datasets/conftest.py
Labels: cla: no

#3299 Add utils.shapes_are_compatible to validate shape matches
  tensorflow_datasets/core/utils/tf_utils.py
  tensorflow_datasets/core/utils/tf_utils_test.py
Labels: cla: no

#3300 Add partial decoding support
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/decode/__init__.py
  tensorflow_datasets/core/decode/base.py
  tensorflow_datasets/core/decode/partial_decode.py
  tensorflow_datasets/core/decode/partial_decode_test.py
  tensorflow_datasets/core/features/sequence_feature.py
Labels: cla: no

#3301 Add documentation for partial decoding support
  docs/decode.md
Labels: cla: no

#3287 Add ProteinNet imports.
  tensorflow_datasets/structured/__init__.py
  tensorflow_datasets/structured/proteinnet/__init__.py
  tensorflow_datasets/structured/proteinnet/checksums.tsv
  tensorflow_datasets/structured/proteinnet/dummy_data/casp7/testing
  tensorflow_datasets/structured/proteinnet/dummy_data/casp7/training_100
  tensorflow_datasets/structured/proteinnet/dummy_data/casp7/validation
  tensorflow_datasets/structured/proteinnet/proteinnet.py
  tensorflow_datasets/structured/proteinnet/proteinnet_test.py
Labels: cla: no

#3309 Add clarification to custom feature connectors
  docs/external_tfrecord.md
  docs/features.md
Labels: cla: no

#3197 Fix cars196 dataset URL
  tensorflow_datasets/image_classification/cars196.py
  tensorflow_datasets/url_checksums/cars196.txt
Labels: cla: yes

#3314 Allow test to pass when there are unrelated logging.warning() calls
  tensorflow_datasets/core/tfrecords_reader_test.py
Labels: cla: no

#3318 Update version doc (remove deprecated content and clarify current state)
  docs/datasets_versioning.md
Labels: cla: no

#3315 Add float support for `tfds.features.Image`
  tensorflow_datasets/core/features/image_feature.py
  tensorflow_datasets/core/features/image_feature_test.py
  tensorflow_datasets/testing/feature_test_case.py
Labels: cla: no

#3316 Update TFDS feature tests to support float comparison
  tensorflow_datasets/testing/feature_test_case.py
Labels: cla: no

#3317 Parent
  tensorflow_datasets/core/features/image_feature.py
  tensorflow_datasets/core/utils/tf_utils.py
Labels: cla: no

#3319 Propagate the file_format in write_metadata and use the file_format in builder_from_directory.
  tensorflow_datasets/core/folder_dataset/write_metadata_utils.py
Labels: cla: no

#3296 Added SummScreen to TFDS.
  tensorflow_datasets/summarization/__init__.py
  tensorflow_datasets/summarization/summscreen/__init__.py
  tensorflow_datasets/summarization/summscreen/checksums.tsv
  tensorflow_datasets/summarization/summscreen/dummy_data/tokenized/SummScreen/ForeverDreaming/fd_dev.json
  tensorflow_datasets/summarization/summscreen/dummy_data/tokenized/SummScreen/ForeverDreaming/fd_test.json
  tensorflow_datasets/summarization/summscreen/dummy_data/tokenized/SummScreen/ForeverDreaming/fd_train.json
  tensorflow_datasets/summarization/summscreen/dummy_data/tokenized/SummScreen/TVMegaSite/tms_dev.json
  tensorflow_datasets/summarization/summscreen/dummy_data/tokenized/SummScreen/TVMegaSite/tms_test.json
  tensorflow_datasets/summarization/summscreen/dummy_data/tokenized/SummScreen/TVMegaSite/tms_train.json
  tensorflow_datasets/summarization/summscreen/dummy_data/untokenized/SummScreen_raw/fd/dev_example.json
  tensorflow_datasets/summarization/summscreen/dummy_data/untokenized/SummScreen_raw/fd/test_example.json
  tensorflow_datasets/summarization/summscreen/dummy_data/untokenized/SummScreen_raw/fd/train_example.json
  tensorflow_datasets/summarization/summscreen/dummy_data/untokenized/SummScreen_raw/tms/dev_example.json
  tensorflow_datasets/summarization/summscreen/dummy_data/untokenized/SummScreen_raw/tms/test_example.json
  tensorflow_datasets/summarization/summscreen/dummy_data/untokenized/SummScreen_raw/tms/train_example.json
  tensorflow_datasets/summarization/summscreen/summscreen.py
  tensorflow_datasets/summarization/summscreen/summscreen_test.py
Labels: cla: no

#3261 Add metadata for version 0.1.1 of ogbg-molpcba.
  tensorflow_datasets/testing/metadata/ogbg_molpcba/0.1.1/dataset_info.json
  tensorflow_datasets/testing/metadata/ogbg_molpcba/0.1.1/features.json
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#3263 Add GraphVisualizer class to visualize graph prediction datasets, with tests for 'ogbg_molpcba.'
  setup.py
  tensorflow_datasets/core/lazy_imports_lib.py
  tensorflow_datasets/core/visualization/__init__.py
  tensorflow_datasets/core/visualization/graph_visualizer.py
  tensorflow_datasets/core/visualization/show_examples.py
  tensorflow_datasets/core/visualization/show_examples_test.py
  tensorflow_datasets/graphs/ogbg_molpcba/ogbg_molpcba.py
Labels: cla: no

#3324 Move Tensor feature to separate file
  tensorflow_datasets/core/features/__init__.py
  tensorflow_datasets/core/features/audio_feature.py
  tensorflow_datasets/core/features/bounding_boxes.py
  tensorflow_datasets/core/features/class_label_feature.py
  tensorflow_datasets/core/features/feature.py
  tensorflow_datasets/core/features/features_dict.py
  tensorflow_datasets/core/features/features_test.py
  tensorflow_datasets/core/features/sequence_feature.py
  tensorflow_datasets/core/features/tensor_feature.py
  tensorflow_datasets/core/features/tensor_feature_test.py
  tensorflow_datasets/core/features/text_feature.py
Labels: cla: no

#3325 Dynamic shape and compression for `tfds.features.Tensor`
  tensorflow_datasets/core/example_parser.py
  tensorflow_datasets/core/features/__init__.py
  tensorflow_datasets/core/features/tensor_feature.py
  tensorflow_datasets/core/features/tensor_feature_test.py
  tensorflow_datasets/core/utils/tf_utils.py
Labels: cla: no

#3200 Add Covid-19 dataset.
  tensorflow_datasets/structured/__init__.py
  tensorflow_datasets/structured/covid19/__init__.py
  tensorflow_datasets/structured/covid19/checksums.tsv
  tensorflow_datasets/structured/covid19/covid19.py
  tensorflow_datasets/structured/covid19/covid19_test.py
  tensorflow_datasets/structured/covid19/dummy_data/covid19.csv
  tensorflow_datasets/structured/covid19/dummy_data/covid19.csv.gz
Labels: cla: no

#3326 Add `Tensor(..., encoding='zlib')`
  tensorflow_datasets/core/features/tensor_feature.py
  tensorflow_datasets/core/features/tensor_feature_test.py
Labels: cla: no

#3328 remove vgg_face2 dataset, no longer supported by their authors, and cannot be downloaded.
  setup.py
  tensorflow_datasets/image/__init__.py
  tensorflow_datasets/image_classification/__init__.py
  tensorflow_datasets/image_classification/vgg_face2.py
  tensorflow_datasets/image_classification/vgg_face2_labels.txt
  tensorflow_datasets/image_classification/vgg_face2_test.py
  tensorflow_datasets/stable_versions.txt
  tensorflow_datasets/testing/metadata/supported.txt
  tensorflow_datasets/testing/test_data/fake_examples/vgg_face2/vggface2_test.tar.gz
  tensorflow_datasets/testing/test_data/fake_examples/vgg_face2/vggface2_train.tar.gz
  tensorflow_datasets/url_checksums/vgg_face2.txt
Labels: cla: no

#3327 Fix summscreen/tms field parsing
  tensorflow_datasets/summarization/summscreen/dummy_data/untokenized/SummScreen_raw/tms/dev_example.json
  tensorflow_datasets/summarization/summscreen/dummy_data/untokenized/SummScreen_raw/tms/test_example.json
  tensorflow_datasets/summarization/summscreen/dummy_data/untokenized/SummScreen_raw/tms/train_example.json
  tensorflow_datasets/summarization/summscreen/summscreen.py
Labels: cla: no

#3329 Move check inside Tensor.encode_example for backward compatibility
  tensorflow_datasets/core/features/tensor_feature.py
  tensorflow_datasets/core/features/tensor_feature_test.py
Labels: cla: no

#3331 Fix or ignore some pytype errors.
  tensorflow_datasets/core/lazy_imports_lib.py
Labels: cla: no

#3333 Internal
  tensorflow_datasets/core/lazy_imports_lib.py
Labels: cla: no

#3332 Refactor the DMLab dataset builder.
  tensorflow_datasets/rl_unplugged/dmlab_dataset.py
  tensorflow_datasets/rl_unplugged/rlu_common.py
Labels: cla: no

#3335 Internal
  tensorflow_datasets/scripts/documentation/dataset_markdown_builder.py
Labels: cla: no

#3235 Fix format /testing
  tensorflow_datasets/testing/dataset_builder_testing.py
  tensorflow_datasets/testing/dataset_builder_testing_test.py
  tensorflow_datasets/testing/dummy_dataset/dummy_dataset.py
  tensorflow_datasets/testing/fake_data_generation/binarized_mnist.py
  tensorflow_datasets/testing/fake_data_generation/cityscapes.py
  tensorflow_datasets/testing/fake_data_generation/clevr.py
  tensorflow_datasets/testing/fake_data_generation/colorectal_histology.py
  tensorflow_datasets/testing/fake_data_generation/curated_breast_imaging_ddsm.py
  tensorflow_datasets/testing/fake_data_generation/imagenet.py
  tensorflow_datasets/testing/fake_data_generation/mnist.py
  tensorflow_datasets/testing/fake_data_generation/open_images.py
  tensorflow_datasets/testing/fake_data_generation/oxford_iiit_pet.py
  tensorflow_datasets/testing/fake_data_generation/patch_camelyon.py
  tensorflow_datasets/testing/fake_data_generation/smallnorb.py
  tensorflow_datasets/testing/fake_data_generation/smallnorb_test.py
  tensorflow_datasets/testing/fake_data_generation/stl10.py
  tensorflow_datasets/testing/fake_data_generation/sun397.py
  tensorflow_datasets/testing/fake_data_utils.py
  tensorflow_datasets/testing/huggingface/dummy_dataset.py
  tensorflow_datasets/testing/mocking.py
  tensorflow_datasets/testing/mocking_test.py
  tensorflow_datasets/testing/test_case.py
  tensorflow_datasets/testing/test_utils_test.py
Labels: cla: no
