Repository tensorflow/datasets, pull requests merged in 2021-03, with the labels that each got.

#3071 Fix ascii error when printing
  tensorflow_datasets/scripts/cli/build.py
Labels: cla: no

#3073 add dtype parameter to features.Video to support uint16 videos
  tensorflow_datasets/core/features/video_feature.py
Labels: cla: no

#3074 [tfds] Remove trailing / in constants.add_data_dir
  tensorflow_datasets/core/constants.py
Labels: cla: no

#3075 Fix link in GEM/MLSum loader that led to wrong examples being filtered and bump
  tensorflow_datasets/text/gem/checksums.tsv
  tensorflow_datasets/text/gem/gem.py
Labels: cla: no

#3076 Cleared a typo in contribute.md for the word "community"
  docs/contribute.md
Labels: cla: yes, community:please_review

#3079 Changes to description to render correctly on the web documentation.
  tensorflow_datasets/graphs/ogbg_molpcba/ogbg_molpcba.py
Labels: cla: no

#3081 fix a broken link in the tfds home page
  docs/_index.yaml
Labels: cla: yes, community:please_review

#3083 Make the ReadOnlyBuilder [un]pickable.
  tensorflow_datasets/core/read_only_builder.py
  tensorflow_datasets/core/read_only_builder_test.py
Labels: cla: no

#3084 Add MoleculeNet reference to ogbg-molpcba description.
  tensorflow_datasets/graphs/ogbg_molpcba/ogbg_molpcba.py
Labels: cla: no

#3093 Add metadata for ogbg-molpcba from TFDS.
  tensorflow_datasets/testing/metadata/ogbg_molpcba/0.1.0/dataset_info.json
  tensorflow_datasets/testing/metadata/ogbg_molpcba/0.1.0/features.json
Labels: cla: no

#3099 Add ogbg_molpcba to BUILD file under tfds/testing/metadata.
  tensorflow_datasets/testing/metadata/supported.txt
Labels: cla: no

#3095 Add constructor to ReadOnlyPath('xyz')
  tensorflow_datasets/core/utils/generic_path_test.py
  tensorflow_datasets/core/utils/type_utils.py
Labels: cla: no

#3102 Change 'ndash' to 'minus' in ogbg_molpcba description so that it can be ASCII encoded.
  tensorflow_datasets/graphs/ogbg_molpcba/ogbg_molpcba.py
Labels: cla: no

#3090 Adding WikiAnn NER to TFDS. The following version of dataset has been added (https://github.com/afshinrahimi/mmner) containing 176 languages.
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/wikiann/__init__.py
  tensorflow_datasets/text/wikiann/checksums.tsv
  tensorflow_datasets/text/wikiann/dummy_data/panx/en.tar.gz
  tensorflow_datasets/text/wikiann/wikiann.py
  tensorflow_datasets/text/wikiann/wikiann_test.py
Labels: cla: no

#3104 Add a `.format()` method to path objects.
  tensorflow_datasets/core/utils/gpath_test.py
  tensorflow_datasets/core/utils/type_utils.py
Labels: cla: no

#3086 adds some helpful information to errors raised during encode_example
  tensorflow_datasets/core/features/features_dict.py
Labels: cla: no

#3107 Add cardinality to mocked datasets.
  tensorflow_datasets/testing/mocking.py
  tensorflow_datasets/testing/mocking_test.py
Labels: cla: no

#3111 Fix multiple tqdm bar issue
  tensorflow_datasets/core/utils/tqdm_utils.py
Labels: cla: yes, tfds:please_review

#3113 Fix radon dataset for windows
  tensorflow_datasets/structured/radon.py
Labels: cla: yes, community:please_review

#3121 remove the redundant + for multi-line str concatenation
  tensorflow_datasets/core/features/features_dict.py
Labels: cla: no

#3098 Create index files for each riegeli dataset shard.
  tensorflow_datasets/core/file_adapters.py
  tensorflow_datasets/core/tfrecords_writer.py
  tensorflow_datasets/core/tfrecords_writer_test.py
Labels: cla: no

#3108 add a logging hook, to be specified through a Logger class.
  tensorflow_datasets/core/dataset_builder.py
  tensorflow_datasets/core/dataset_builder_read_test.py
  tensorflow_datasets/core/logging/__init__.py
  tensorflow_datasets/core/logging/base_logger.py
  tensorflow_datasets/core/logging/logging_logger.py
Labels: cla: no

#3122 Integrated dolphin_word_problems dataset (https://www.microsoft.com/en-us/research/project/sigmadolphin-2/) into tensorflow_datasets.
  tensorflow_datasets/text/__init__.py
  tensorflow_datasets/text/dolphin_number_word/__init__.py
  tensorflow_datasets/text/dolphin_number_word/checksums.tsv
  tensorflow_datasets/text/dolphin_number_word/dolphin_number_word.py
  tensorflow_datasets/text/dolphin_number_word/dolphin_number_word_test.py
  tensorflow_datasets/text/dolphin_number_word/dummy_data/test.dev
  tensorflow_datasets/text/dolphin_number_word/dummy_data/test.test
Labels: cla: no

#3124 Fix typo in FeaturesDict docstring
  tensorflow_datasets/core/features/features_dict.py
Labels: cla: yes, tfds:please_review

#3123 Mini-fix to doc-string in data_builder_testing.py
  tensorflow_datasets/testing/dataset_builder_testing.py
Labels: cla: yes, tfds:please_review

#3114 Fix URL in overview.ipynb
  docs/overview.ipynb
Labels: cla: yes, tfds:please_review

#3134 fix typo in docs (suffle -> shuffle)
  docs/add_dataset.md
Labels: cla: no

#3136 Explicitly include 'id' field in civil_comments TFDS examples
  tensorflow_datasets/text/civil_comments.py
Labels: cla: no

#3139 Rolling back CivilComments change to advance version number
  tensorflow_datasets/text/civil_comments.py
Labels: cla: no

#3126 Flattened the equations string to mitigate error thrown in TFDS pipeline related to the generated RaggedTensors (representing a list of strings).
  tensorflow_datasets/text/dolphin_number_word/dolphin_number_word.py
Labels: cla: no
